	tilepal 0, WATER, RED, RED, RED, RED, BROWN, WATER, WATER
	tilepal 0, GREEN, GREEN, GREEN, GREEN, WATER, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, RED, RED, RED, BROWN, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, GREEN, WATER, WATER, WATER, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN
	tilepal 0, WATER, WATER, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, GRAY, GRAY, WATER, GRAY, BROWN, BROWN, BROWN, WATER
	tilepal 0, RED, RED, BROWN, BROWN, GREEN, YELLOW, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, WATER, RED, RED, RED, RED, BROWN, WATER, WATER
	tilepal 1, GREEN, GREEN, GREEN, GREEN, WATER, WATER, BROWN, BROWN
	tilepal 1, BROWN, BROWN, RED, RED, RED, BROWN, WATER, WATER
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, GREEN, WATER, WATER, WATER, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 1, GRAY, GRAY, WATER, GRAY, BROWN, BROWN, BROWN, WATER
	tilepal 1, RED, RED, BROWN, BROWN, GREEN, YELLOW, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
