	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, RED
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED
	tilepal 1, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, RED
	tilepal 1, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
