	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll WALL, WALL, WALL, WALL ; 02
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 03
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 04
	tilecoll WALL, UP_WALL, WALL, FLOOR ; 05
	tilecoll UP_WALL, UP_WALL, FLOOR, FLOOR ; 06
	tilecoll UP_WALL, WALL, FLOOR, WALL ; 07
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 08
	tilecoll WALL, FLOOR, WALL, FLOOR ; 09
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0a
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0b
	tilecoll WALL, WALL, WALL, WALL ; 0c
	tilecoll WALL, FLOOR, WALL, WALL ; 0d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0e
	tilecoll FLOOR, WALL, WALL, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 11
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 12
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 13
	tilecoll FLOOR, FLOOR, WALL, CAVE ; 14
	tilecoll WALL, WALL, WALL, FLOOR ; 15
	tilecoll WALL, WALL, FLOOR, FLOOR ; 16
	tilecoll WALL, WALL, FLOOR, WALL ; 17
	tilecoll FLOOR, FLOOR, PIT, FLOOR ; 18
	tilecoll WALL, FLOOR, WALL, FLOOR ; 19
	tilecoll WALL, WALL, WALL, WALL ; 1a
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1b
	tilecoll FLOOR, PIT, FLOOR, FLOOR ; 1c
	tilecoll WALL, FLOOR, WALL, WALL ; 1d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 1e
	tilecoll FLOOR, WALL, WALL, WALL ; 1f
	tilecoll ICE, ICE, ICE, ICE ; 20
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 21
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 22
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 23
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 24
	tilecoll WALL, HOP_DOWN_LEFT, WALL, WALL ; 25
	tilecoll HOP_DOWN, HOP_DOWN, WALL, WALL ; 26
	tilecoll HOP_DOWN_RIGHT, WALL, WALL, WALL ; 27
	tilecoll WALL, HOP_LEFT, WALL, HOP_LEFT ; 28
	tilecoll HOP_RIGHT, WALL, HOP_RIGHT, WALL ; 29
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, FLOOR ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2c
	tilecoll WALL, ICE, ICE, ICE ; 2d
	tilecoll ICE, ICE, WALL, ICE ; 2e
	tilecoll ICE, WALL, ICE, ICE ; 2f
	tilecoll ICE, ICE, ICE, WALL ; 30
	tilecoll WALL, WALL, FLOOR, WALL ; 31
	tilecoll WALL, WALL, WALL, WALL ; 32
	tilecoll WALL, WALL, WALL, FLOOR ; 33
	tilecoll WALL, WALL, FLOOR, FLOOR ; 34
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 35
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 36
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 37
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 38
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 39
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3a
	tilecoll FLOOR, WALL, FLOOR, WALL ; 3b
	tilecoll WALL, WALL, WALL, WALL ; 3c
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 3d
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 3e
	tilecoll FLOOR, FLOOR, WALL, WALL ; 3f
	tilecoll ICE, ICE, ICE, LADDER ; 40
