	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll WALL, WALL, WALL, WALL ; 02
	tilecoll WALL, WALL, WALL, WALL ; 03
	tilecoll WALL, WALL, WALL, WALL ; 04
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll FLOOR, FLOOR, WALL, WALL ; 07
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 08
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 09
	tilecoll STAIRCASE, WALL, FLOOR, FLOOR ; 0a
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0c
	tilecoll WALL, WALL, WALL, WALL ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll WALL, WALL, WALL, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll 9C, FLOOR, COUNTER, FLOOR ; 11
	tilecoll WALL, WALL, WALL, WALL ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll WALL, WALL, WALL, WALL ; 14
	tilecoll WALL, WARP_CARPET_DOWN, WALL, WALL ; 15
	tilecoll WALL, WALL, WALL, WALL ; 16
	tilecoll 9C, FLOOR, COUNTER, FLOOR ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
	tilecoll FLOOR, WALL, FLOOR, WALL ; 19
	tilecoll WALL, WALL, WALL, STAIRCASE ; 1a
	tilecoll LADDER, FLOOR, FLOOR, FLOOR ; 1b
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 1c
	tilecoll WALL, WALL, WALL, WALL ; 1d
	tilecoll WALL, WALL, FLOOR, FLOOR ; 1e
	tilecoll WALL, WALL, WALL, WALL ; 1f
	tilecoll WALL, WALL, WALL, WALL ; 20
	tilecoll WALL, FLOOR, WALL, FLOOR ; 21
	tilecoll FLOOR, WALL, FLOOR, WALL ; 22
	tilecoll WALL, FLOOR, WALL, WALL ; 23
	tilecoll FLOOR, WALL, WALL, WALL ; 24
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 25
	tilecoll FLOOR, FLOOR, WALL, WALL ; 26
	tilecoll WALL, WALL, WALL, WALL ; 27
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 28
	tilecoll FLOOR, FLOOR, PIT, PIT ; 29
	tilecoll WALL, WALL, WINDOW, WINDOW ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 2d
	tilecoll WALL, WALL, WALL, WALL ; 2e
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 2f
	tilecoll WALL, WALL, WALL, BOOKSHELF ; 30
	tilecoll WALL, WALL, FLOOR, WALL ; 31
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 32
	tilecoll WALL, WALL, WALL, WALL ; 33
	tilecoll WALL, FLOOR, WALL, FLOOR ; 34
	tilecoll WALL, WALL, PC, FLOOR ; 35
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 36
	tilecoll FLOOR, WALL, FLOOR, WALL ; 37
	tilecoll WALL, WALL, WALL, WALL ; 38
	tilecoll WALL, WALL, FLOOR, WALL ; 39
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 3a
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 3b
	tilecoll WALL, WALL, WALL, WALL ; 3c
	tilecoll WALL, WALL, WALL, WALL ; 3d
	tilecoll WALL, WALL, WINDOW, WALL ; 3e
	tilecoll WALL, WALL, WALL, WALL ; 3f
	tilecoll WALL, WALL, WALL, WALL ; 40
