	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll WALL, WALL, FLOOR, WALL ; 02
	tilecoll WALL, WALL, WALL, FLOOR ; 03
	tilecoll FLOOR, FLOOR, WALL, WALL ; 04
	tilecoll WALL, WALL, WALL, WALL ; 05
	tilecoll WALL, WALL, COUNTER, FLOOR ; 06
	tilecoll COUNTER, FLOOR, COUNTER, FLOOR ; 07
	tilecoll COUNTER, COUNTER, FLOOR, FLOOR ; 08
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 09
	tilecoll WALL, FLOOR, FLOOR, WALL ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll WALL, WALL, LADDER, LADDER ; 0c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 11
	tilecoll WALL, WALL, WALL, FLOOR ; 12
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 13
	tilecoll WALL, WALL, FLOOR, WALL ; 14
	tilecoll WALL, FLOOR, WALL, WALL ; 15
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 16
	tilecoll FLOOR, FLOOR, WALL, WALL ; 17
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 18
	tilecoll WALL, FLOOR, WALL, FLOOR ; 19
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1a
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1b
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1c
	tilecoll WALL, UP_WALL, WALL, FLOOR ; 1d
	tilecoll UP_WALL, UP_WALL, FLOOR, FLOOR ; 1e
	tilecoll UP_WALL, WALL, FLOOR, WALL ; 1f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 20
	tilecoll WALL, FLOOR, WALL, WALL ; 21
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 22
	tilecoll FLOOR, WALL, WALL, WALL ; 23
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 24
	tilecoll WALL, FLOOR, WALL, FLOOR ; 25
	tilecoll WALL, WALL, WALL, WALL ; 26
	tilecoll WALL, WALL, WALL, WALL ; 27
	tilecoll FLOOR, WALL, FLOOR, WALL ; 28
	tilecoll WALL, WALL, WALL, WALL ; 29
	tilecoll WALL, WALL, WALL, WALL ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2c
	tilecoll WALL, WALL, WALL, WALL ; 2d
	tilecoll WALL, WALL, WALL, WALL ; 2e
	tilecoll WALL, WALL, WALL, WALL ; 2f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 30
	tilecoll FLOOR, WALL, FLOOR, WALL ; 31
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 32
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 33
	tilecoll WALL, WALL, FLOOR, FLOOR ; 34
	tilecoll FLOOR, FLOOR, WALL, WALL ; 35
	tilecoll WALL, FLOOR, WALL, FLOOR ; 36
	tilecoll FLOOR, WALL, FLOOR, WALL ; 37
	tilecoll FLOOR, WALL, WALL, WALL ; 38
	tilecoll WALL, FLOOR, WALL, FLOOR ; 39
	tilecoll FLOOR, WALL, FLOOR, WALL ; 3a
	tilecoll WALL, WALL, WALL, WALL ; 3b
	tilecoll WALL, WALL, WALL, WALL ; 3c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3e
	tilecoll WALL, FLOOR, WALL, WALL ; 3f
	tilecoll FLOOR, WALL, WALL, WALL ; 40
