	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll WALL, WALL, WALL, WALL ; 02
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 03
	tilecoll WALL, WALL, TV, BOOKSHELF ; 04
	tilecoll WALL, WALL, FLOOR, FLOOR ; 05
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 06
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 07
	tilecoll WALL, WALL, FLOOR, FLOOR ; 08
	tilecoll WALL, WALL, FLOOR, FLOOR ; 09
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0b
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 10
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 11
	tilecoll WALL, WALL, FLOOR, FLOOR ; 12
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 13
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 14
	tilecoll WALL, WALL, FLOOR, FLOOR ; 15
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 16
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 17
	tilecoll WALL, WALL, FLOOR, FLOOR ; 18
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 19
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1e
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1f
	tilecoll TOWN_MAP, STAIRCASE, FLOOR, FLOOR ; 20
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 21
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 22
	tilecoll FLOOR, WALL, FLOOR, WALL ; 23
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 24
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 25
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 26
	tilecoll FF, FF, FF, FF ; 27
	tilecoll FF, FF, FF, FF ; 28
	tilecoll FF, FF, FF, FF ; 29
	tilecoll FF, FF, FF, FF ; 2a
	tilecoll FF, FF, FF, FF ; 2b
	tilecoll FF, FF, FF, FF ; 2c
	tilecoll FF, FF, FF, FF ; 2d
	tilecoll FF, FF, FF, FF ; 2e
	tilecoll FF, FF, FF, FF ; 2f
	tilecoll FF, FF, FF, FF ; 30
	tilecoll FF, FF, FF, FF ; 31
	tilecoll FF, FF, FF, FF ; 32
	tilecoll FF, FF, FF, FF ; 33
	tilecoll FF, FF, FF, FF ; 34
	tilecoll FF, FF, FF, FF ; 35
	tilecoll FF, FF, FF, FF ; 36
	tilecoll FF, FF, FF, FF ; 37
	tilecoll FF, FF, FF, FF ; 38
	tilecoll FF, FF, FF, FF ; 39
	tilecoll FF, FF, FF, FF ; 3a
	tilecoll FF, FF, FF, FF ; 3b
	tilecoll FF, FF, FF, FF ; 3c
	tilecoll FF, FF, FF, FF ; 3d
	tilecoll FF, FF, FF, FF ; 3e
	tilecoll FF, FF, FF, FF ; 3f
	tilecoll FF, FF, FF, FF ; 40
