	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, RED, RED, GRAY, GRAY, RED, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, RED, RED, GRAY, GRAY, WATER, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, ROOF, ROOF, GRAY, GRAY, YELLOW, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, ROOF, ROOF, WATER, WATER, GREEN, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, YELLOW, YELLOW, WATER, WATER, BROWN, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, YELLOW, YELLOW, GRAY, GRAY, BROWN, YELLOW, YELLOW

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, RED, RED, GRAY, GRAY, RED, RED, RED
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, RED, RED, GRAY, GRAY, WATER, RED, RED
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, ROOF, ROOF, GRAY, GRAY, YELLOW, RED, RED
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, ROOF, ROOF, WATER, WATER, GREEN, RED, RED
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 1, GREEN, YELLOW, YELLOW, WATER, WATER, BROWN, YELLOW, YELLOW
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 1, GREEN, YELLOW, YELLOW, GRAY, GRAY, BROWN, YELLOW, YELLOW
