	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll STAIRCASE, WALL, FLOOR, FLOOR ; 03
	tilecoll WALL, WALL, FLOOR, FLOOR ; 04
	tilecoll WALL, WALL, WALL, FLOOR ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, WALL, FLOOR ; 07
	tilecoll WALL, WALL, FLOOR, PC ; 08
	tilecoll WALL, WALL, WALL, FLOOR ; 09
	tilecoll WALL, COUNTER, FLOOR, FLOOR ; 0a
	tilecoll WALL, COUNTER, FLOOR, FLOOR ; 0b
	tilecoll WALL, WALL, WALL, WALL ; 0c
	tilecoll WALL, WALL, FLOOR, WALL ; 0d
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 0e
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 0f
	tilecoll WALL, WALL, FLOOR, WALL ; 10
	tilecoll WALL, WALL, FLOOR, FLOOR ; 11
	tilecoll WALL, WALL, WALL, FLOOR ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll WALL, WALL, WALL, WALL ; 14
	tilecoll WALL, WALL, WALL, WALL ; 15
	tilecoll WALL, WALL, FLOOR, FLOOR ; 16
	tilecoll WALL, WALL, WALL, WALL ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
	tilecoll WALL, WALL, WALL, WALL ; 19
	tilecoll WALL, WALL, WALL, WALL ; 1a
	tilecoll WALL, WALL, FLOOR, WALL ; 1b
	tilecoll WALL, WALL, WALL, WALL ; 1c
	tilecoll WALL, WALL, WALL, WALL ; 1d
	tilecoll WALL, WALL, WALL, WALL ; 1e
	tilecoll WALL, WALL, WALL, WALL ; 1f
	tilecoll WALL, WALL, WALL, WALL ; 20
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 21
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 22
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 23
	tilecoll WALL, WALL, WALL, WALL ; 24
	tilecoll WALL, WALL, WALL, WALL ; 25
	tilecoll WALL, WALL, WALL, WALL ; 26
	tilecoll WALL, WALL, WALL, WALL ; 27
	tilecoll WALL, WALL, WALL, WALL ; 28
	tilecoll WALL, WALL, WALL, WALL ; 29
	tilecoll WALL, WALL, WALL, WALL ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2c
	tilecoll FLOOR, FLOOR, LADDER, FLOOR ; 2d
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 2e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 2f
	tilecoll WALL, WALL, WALL, WALL ; 30
	tilecoll WALL, WALL, WALL, WALL ; 31
	tilecoll WALL, WALL, WALL, WALL ; 32
	tilecoll WALL, WALL, WALL, WALL ; 33
	tilecoll FLOOR, FLOOR, WALL, WALL ; 34
	tilecoll WALL, WALL, WALL, WALL ; 35
	tilecoll WALL, WALL, FLOOR, FLOOR ; 36
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 37
	tilecoll WALL, WALL, FLOOR, FLOOR ; 38
	tilecoll WALL, WALL, WALL, WALL ; 39
	tilecoll WALL, WALL, WALL, WALL ; 3a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3b
	tilecoll WALL, WALL, FLOOR, FLOOR ; 3c
	tilecoll WALL, WALL, WALL, WALL ; 3d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 3e
	tilecoll WALL, WALL, WALL, WALL ; 3f
	tilecoll WALL, WALL, WALL, WALL ; 40
