	tilecoll FF, FF, FF, FF ; 01
	tilecoll UP_WALL, UP_WALL, FLOOR, FLOOR ; 02
	tilecoll UP_WALL, FLOOR, UP_WALL, FLOOR ; 03
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 04
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 05
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 06
	tilecoll FLOOR, FLOOR, WALL, WALL ; 07
	tilecoll WALL, FLOOR, WALL, FLOOR ; 08
	tilecoll WALL, FLOOR, WALL, WALL ; 09
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll WALL, WALL, WALL, WALL ; 11
	tilecoll WALL, WALL, DOOR, WALL ; 12
	tilecoll WALL, WALL, WALL, DOOR ; 13
	tilecoll WALL, WALL, WALL, WALL ; 14
	tilecoll WALL, WALL, WALL, WALL ; 15
	tilecoll WALL, WALL, WALL, WALL ; 16
	tilecoll WALL, WALL, WALL, WALL ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 19
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1a
	tilecoll WALL, WALL, WALL, WALL ; 1b
	tilecoll WALL, WALL, WALL, WALL ; 1c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1f
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 20
	tilecoll WALL, WALL, WALL, WALL ; 21
	tilecoll WALL, FLOOR, WALL, FLOOR ; 22
	tilecoll FLOOR, WALL, FLOOR, WALL ; 23
	tilecoll WALL, WALL, FLOOR, FLOOR ; 24
	tilecoll WALL, WALL, FLOOR, FLOOR ; 25
	tilecoll WALL, WALL, FLOOR, FLOOR ; 26
	tilecoll WALL, FLOOR, WALL, FLOOR ; 27
	tilecoll FLOOR, WALL, FLOOR, WALL ; 28
	tilecoll WALL, WALL, WALL, FLOOR ; 29
	tilecoll WALL, WALL, FLOOR, WALL ; 2a
	tilecoll WALL, FLOOR, WALL, FLOOR ; 2b
	tilecoll FLOOR, WALL, FLOOR, WALL ; 2c
	tilecoll FLOOR, WALL, FLOOR, WALL ; 2d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 2e
	tilecoll WALL, WALL, WALL, WALL ; 2f
	tilecoll WALL, WALL, FLOOR, FLOOR ; 30
	tilecoll WALL, WALL, FLOOR, FLOOR ; 31
	tilecoll WALL, FLOOR, WALL, FLOOR ; 32
	tilecoll FLOOR, WALL, FLOOR, WALL ; 33
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 34
	tilecoll WALL, FLOOR, WALL, FLOOR ; 35
	tilecoll FLOOR, WALL, FLOOR, WALL ; 36
	tilecoll WALL, WALL, WALL, FLOOR ; 37
	tilecoll WALL, WALL, FLOOR, FLOOR ; 38
	tilecoll WALL, WALL, FLOOR, WALL ; 39
	tilecoll WALL, FLOOR, WALL, WALL ; 3a
	tilecoll WALL, WALL, WALL, WALL ; 3b
	tilecoll FLOOR, WALL, WALL, WALL ; 3c
	tilecoll WALL, WALL, WALL, WALL ; 3d
	tilecoll WALL, WALL, WALL, WALL ; 3e
	tilecoll WALL, WALL, WALL, WALL ; 3f
	tilecoll WALL, WALL, WALL, WALL ; 40
