	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 03
	tilecoll TALL_GRASS_10, TALL_GRASS_10, TALL_GRASS_10, TALL_GRASS_10 ; 04
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 07
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 08
	tilecoll WALL, WALL, WALL, WALL ; 09
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll WARP_CARPET_LEFT, FLOOR, WARP_CARPET_LEFT, FLOOR ; 0c
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 0d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0e
	tilecoll FLOOR, WARP_CARPET_RIGHT, FLOOR, WARP_CARPET_RIGHT ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll WALL, WALL, WALL, WALL ; 11
	tilecoll WALL, WALL, WALL, WALL ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll WALL, WALL, WALL, WALL ; 14
	tilecoll WALL, WALL, WALL, DOOR ; 15
	tilecoll WALL, WALL, WALL, WALL ; 16
	tilecoll WALL, WALL, WALL, DOOR ; 17
	tilecoll WALL, WALL, TOWN_MAP, WALL ; 18
	tilecoll WALL, WALL, WALL, WALL ; 19
	tilecoll WALL, WALL, WALL, WALL ; 1a
	tilecoll WALL, WALL, WALL, DOOR ; 1b
	tilecoll WALL, WALL, TOWN_MAP, WALL ; 1c
	tilecoll WALL, WALL, WALL, WALL ; 1d
	tilecoll WALL, WALL, DOOR, WALL ; 1e
	tilecoll WALL, WALL, WALL, WALL ; 1f
	tilecoll WALL, WALL, WALL, WALL ; 20
	tilecoll WALL, WALL, WALL, WALL ; 21
	tilecoll WALL, WALL, WALL, WALL ; 22
	tilecoll WALL, WALL, WALL, WALL ; 23
	tilecoll WALL, WALL, WALL, WALL ; 24
	tilecoll WALL, WALL, WALL, WALL ; 25
	tilecoll WALL, WALL, WALL, WALL ; 26
	tilecoll WALL, WALL, WALL, WALL ; 27
	tilecoll WALL, WALL, WALL, WALL ; 28
	tilecoll WALL, WALL, WALL, DOOR ; 29
	tilecoll WALL, WALL, WALL, WALL ; 2a
	tilecoll WALL, WALL, WALL, DOOR ; 2b
	tilecoll WALL, WALL, WALL, WALL ; 2c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2e
	tilecoll WALL, WALL, WALL, DOOR ; 2f
	tilecoll WALL, WALL, WALL, WALL ; 30
	tilecoll BUOY, BUOY, BUOY, WATER_21 ; 31
	tilecoll BUOY, BUOY, WATER_21, WATER_21 ; 32
	tilecoll BUOY, BUOY, WATER_21, BUOY ; 33
	tilecoll FLOOR, FLOOR, WALL, WALL ; 34
	tilecoll BUOY, WATER_21, BUOY, WATER_21 ; 35
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 36
	tilecoll WATER_21, BUOY, WATER_21, BUOY ; 37
	tilecoll WALL, WALL, WALL, WALL ; 38
	tilecoll BUOY, WATER_21, BUOY, BUOY ; 39
	tilecoll WATER_21, WATER_21, BUOY, BUOY ; 3a
	tilecoll WATER_21, BUOY, BUOY, BUOY ; 3b
	tilecoll WALL, WALL, WALL, WALL ; 3c
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 3d
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 3e
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 3f
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 40
	tilecoll WALL, WALL, WALL, FLOOR ; 41
	tilecoll WALL, WALL, FLOOR, FLOOR ; 42
	tilecoll WALL, WALL, FLOOR, WALL ; 43
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 44
	tilecoll WALL, FLOOR, WALL, FLOOR ; 45
	tilecoll TOWN_MAP, FLOOR, FLOOR, FLOOR ; 46
	tilecoll FLOOR, WALL, FLOOR, WALL ; 47
	tilecoll FLOOR, FLOOR, FLOOR, TOWN_MAP ; 48
	tilecoll WALL, FLOOR, WALL, WALL ; 49
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4a
	tilecoll FLOOR, WALL, WALL, WALL ; 4b
	tilecoll HOP_DOWN, FLOOR, WALL, FLOOR ; 4c
	tilecoll WALL, HOP_LEFT, WALL, HOP_LEFT ; 4d
	tilecoll HOP_RIGHT, WALL, HOP_RIGHT, WALL ; 4e
	tilecoll WALL, HOP_LEFT, WALL, HOP_LEFT ; 4f
	tilecoll HOP_RIGHT, WALL, HOP_RIGHT, WALL ; 50
	tilecoll WALL, HOP_DOWN_LEFT, WALL, WALL ; 51
	tilecoll HOP_DOWN_RIGHT, WALL, WALL, WALL ; 52
	tilecoll WALL, HOP_DOWN_LEFT, WALL, WALL ; 53
	tilecoll HOP_DOWN_RIGHT, WALL, WALL, WALL ; 54
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 55
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 56
	tilecoll HOP_DOWN, HOP_DOWN, WALL, WALL ; 57
	tilecoll HOP_DOWN, HOP_DOWN, WALL, WALL ; 58
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 59
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 5a
	tilecoll HOP_DOWN, FLOOR, WALL, FLOOR ; 5b
	tilecoll WALL, CUT_TREE, FLOOR, FLOOR ; 5c
	tilecoll WALL, WALL, WALL, FLOOR ; 5d
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5e
	tilecoll WALL, WALL, FLOOR, WALL ; 5f
	tilecoll FLOOR, WALL, FLOOR, CUT_TREE ; 60
	tilecoll WALL, FLOOR, WALL, FLOOR ; 61
	tilecoll WALL, WALL, WALL, WALL ; 62
	tilecoll FLOOR, WALL, FLOOR, WALL ; 63
	tilecoll FLOOR, FLOOR, CUT_TREE, WALL ; 64
	tilecoll WALL, FLOOR, WALL, WALL ; 65
	tilecoll FLOOR, FLOOR, WALL, WALL ; 66
	tilecoll FLOOR, WALL, WALL, WALL ; 67
	tilecoll CUT_TREE, FLOOR, WALL, FLOOR ; 68
	tilecoll WALL, FLOOR, WALL, FLOOR ; 69
	tilecoll FLOOR, WALL, FLOOR, WALL ; 6a
	tilecoll WALL, UP_WALL, WALL, FLOOR ; 6b
	tilecoll UP_WALL, WALL, FLOOR, WALL ; 6c
	tilecoll WALL, FLOOR, WALL, WALL ; 6d
	tilecoll FLOOR, WALL, WALL, WALL ; 6e
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 6f
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 70
	tilecoll UP_WALL, UP_WALL, FLOOR, FLOOR ; 71
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 72
	tilecoll FLOOR, FLOOR, WALL, WALL ; 73
	tilecoll FLOOR, FLOOR, DOOR, WALL ; 74
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 75
	tilecoll WALL, WALL, FLOOR, FLOOR ; 76
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 77
	tilecoll WALL, WALL, WALL, WALL ; 78
	tilecoll WALL, WALL, WALL, WALL ; 79
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 7a
	tilecoll WATER_21, WATER_21, WATER_21, WATER_21 ; 7b
	tilecoll WALL, WALL, WALL, WALL ; 7c
	tilecoll WALL, WALL, WALL, WALL ; 7d
	tilecoll WALL, WALL, WALL, WALL ; 7e
	tilecoll WALL, WALL, WALL, WALL ; 7f
	tilecoll WALL, WALL, WALL, WALL ; 80
