
ANIM_OBJ_BURNED EQU $10
ANIM_OBJ_FROZEN EQU $2a
ANIM_OBJ_GUST EQU $3e
ANIM_OBJ_CHICK EQU $52
ANIM_OBJ_SKULL EQU $55
ANIM_OBJ_PARALYZED EQU $59
ANIM_OBJ_HEART EQU $7e
ANIM_OBJ_FLOWER EQU $b6
ANIM_OBJ_COTTON EQU $b7

ANIM_BG_FLASH_INVERTED EQU $01
ANIM_BG_FLASH_WHITE EQU $02
ANIM_BG_WHITE_HUES EQU $03
ANIM_BG_BLACK_HUES EQU $04
ANIM_BG_ALTERNATE_HUES EQU $05
; ???? EQU $06
; ???? EQU $07
; ???? EQU $08
ANIM_BG_HIDE_MON EQU $09
ANIM_BG_SHOW_MON EQU $0a
ANIM_BG_ENTER_MON EQU $0b
ANIM_BG_RETURN_MON EQU $0c
ANIM_BG_SURF EQU $0d
ANIM_BG_WHIRLPOOL EQU $0e
ANIM_BG_TELEPORT EQU $0f
ANIM_BG_NIGHT_SHADE EQU $10
ANIM_BG_FEET_FOLLOW EQU $11
ANIM_BG_HEAD_FOLLOW EQU $12
ANIM_BG_DOUBLE_TEAM EQU $13
ANIM_BG_ACID_ARMOR EQU $14
ANIM_BG_RAPID_FLASH EQU $15 ; unused

ANIM_BG_TACKLE EQU $24

ANIM_BG_PSYCHIC EQU $29

ANIM_BG_VIBRATE_MON EQU $33
ANIM_BG_WOBBLE_MON EQU $34

	const_def
	const ANIM_MON_SLOW    ; 0
	const ANIM_MON_NORMAL  ; 1
	const ANIM_MON_MENU    ; 2
	const ANIM_MON_TRADE   ; 3
	const ANIM_MON_EVOLVE  ; 4
	const ANIM_MON_HATCH   ; 5
	const ANIM_MON_UNUSED  ; 6
	const ANIM_MON_EGG1    ; 7
	const ANIM_MON_EGG2    ; 8
