	const_def
	const BATTLEANIMSTRUCT_INDEX
	const BATTLEANIMSTRUCT_01
	const BATTLEANIMSTRUCT_02
	const BATTLEANIMSTRUCT_FRAMESET_ID
	const BATTLEANIMSTRUCT_FUNCTION
	const BATTLEANIMSTRUCT_PALETTE
    const BATTLEANIMSTRUCT_TILEID
    const BATTLEANIMSTRUCT_XCOORD
    const BATTLEANIMSTRUCT_YCOORD
    const BATTLEANIMSTRUCT_XOFFSET
    const BATTLEANIMSTRUCT_YOFFSET
    const BATTLEANIMSTRUCT_0B
    const BATTLEANIMSTRUCT_DURATION
    const BATTLEANIMSTRUCT_FRAME
    const BATTLEANIMSTRUCT_ANON_JT_INDEX
    const BATTLEANIMSTRUCT_0F
    const BATTLEANIMSTRUCT_10
    const BATTLEANIMSTRUCT_11
    const BATTLEANIMSTRUCT_12
    const BATTLEANIMSTRUCT_13
    const BATTLEANIMSTRUCT_14
    const BATTLEANIMSTRUCT_15
    const BATTLEANIMSTRUCT_16
    const BATTLEANIMSTRUCT_17
BATTLEANIMSTRUCT_LENGTH EQU const_value

	const_def
	const ANIM_OBJ_00
    const ANIM_OBJ_01
    const ANIM_OBJ_02
    const ANIM_OBJ_03
    const ANIM_OBJ_04
    const ANIM_OBJ_05
    const ANIM_OBJ_06
    const ANIM_OBJ_07
    const ANIM_OBJ_08
    const ANIM_OBJ_09
    const ANIM_OBJ_0A
    const ANIM_OBJ_0B
    const ANIM_OBJ_0C
    const ANIM_OBJ_0D
    const ANIM_OBJ_0E
    const ANIM_OBJ_0F
    const ANIM_OBJ_BURNED
    const ANIM_OBJ_11
    const ANIM_OBJ_12
    const ANIM_OBJ_13
    const ANIM_OBJ_14
    const ANIM_OBJ_POKE_BALL
    const ANIM_OBJ_16
    const ANIM_OBJ_17
    const ANIM_OBJ_18
    const ANIM_OBJ_19
    const ANIM_OBJ_1A
    const ANIM_OBJ_1B
    const ANIM_OBJ_1C
    const ANIM_OBJ_1D
    const ANIM_OBJ_1E
    const ANIM_OBJ_1F
    const ANIM_OBJ_20
    const ANIM_OBJ_21
    const ANIM_OBJ_22
    const ANIM_OBJ_23
    const ANIM_OBJ_24
    const ANIM_OBJ_25
    const ANIM_OBJ_26
    const ANIM_OBJ_27
    const ANIM_OBJ_28
    const ANIM_OBJ_29
    const ANIM_OBJ_FROZEN
    const ANIM_OBJ_2B
    const ANIM_OBJ_2C
    const ANIM_OBJ_2D
    const ANIM_OBJ_2E
    const ANIM_OBJ_2F
    const ANIM_OBJ_30
    const ANIM_OBJ_31
    const ANIM_OBJ_32
    const ANIM_OBJ_33
    const ANIM_OBJ_34
    const ANIM_OBJ_35
    const ANIM_OBJ_36
    const ANIM_OBJ_37
    const ANIM_OBJ_38
    const ANIM_OBJ_39
    const ANIM_OBJ_3A
    const ANIM_OBJ_3B
    const ANIM_OBJ_3C
    const ANIM_OBJ_3D
    const ANIM_OBJ_GUST
    const ANIM_OBJ_3F
    const ANIM_OBJ_40
    const ANIM_OBJ_41
    const ANIM_OBJ_42
    const ANIM_OBJ_43
    const ANIM_OBJ_44
    const ANIM_OBJ_45
    const ANIM_OBJ_46
    const ANIM_OBJ_47
    const ANIM_OBJ_48
    const ANIM_OBJ_49
    const ANIM_OBJ_4A
    const ANIM_OBJ_4B
    const ANIM_OBJ_4C
    const ANIM_OBJ_4D
    const ANIM_OBJ_4E
    const ANIM_OBJ_4F
    const ANIM_OBJ_50
    const ANIM_OBJ_51
    const ANIM_OBJ_CHICK
    const ANIM_OBJ_53
    const ANIM_OBJ_54
    const ANIM_OBJ_SKULL
    const ANIM_OBJ_56
    const ANIM_OBJ_57
    const ANIM_OBJ_58
    const ANIM_OBJ_PARALYZED
    const ANIM_OBJ_5A
    const ANIM_OBJ_5B
    const ANIM_OBJ_5C
    const ANIM_OBJ_5D
    const ANIM_OBJ_5E
    const ANIM_OBJ_5F
    const ANIM_OBJ_60
    const ANIM_OBJ_61
    const ANIM_OBJ_62
    const ANIM_OBJ_63
    const ANIM_OBJ_64
    const ANIM_OBJ_65
    const ANIM_OBJ_66
    const ANIM_OBJ_67
    const ANIM_OBJ_68
    const ANIM_OBJ_69
    const ANIM_OBJ_6A
    const ANIM_OBJ_6B
    const ANIM_OBJ_6C
    const ANIM_OBJ_6D
    const ANIM_OBJ_6E
    const ANIM_OBJ_6F
    const ANIM_OBJ_70
    const ANIM_OBJ_71
    const ANIM_OBJ_72
    const ANIM_OBJ_73
    const ANIM_OBJ_74
    const ANIM_OBJ_75
    const ANIM_OBJ_76
    const ANIM_OBJ_77
    const ANIM_OBJ_78
    const ANIM_OBJ_79
    const ANIM_OBJ_7A
    const ANIM_OBJ_7B
    const ANIM_OBJ_7C
    const ANIM_OBJ_7D
    const ANIM_OBJ_HEART
    const ANIM_OBJ_7F
    const ANIM_OBJ_80
    const ANIM_OBJ_81
    const ANIM_OBJ_82
    const ANIM_OBJ_83
    const ANIM_OBJ_84
    const ANIM_OBJ_85
    const ANIM_OBJ_86
    const ANIM_OBJ_87
    const ANIM_OBJ_88
    const ANIM_OBJ_89
    const ANIM_OBJ_8A
    const ANIM_OBJ_8B
    const ANIM_OBJ_8C
    const ANIM_OBJ_8D
    const ANIM_OBJ_8E
    const ANIM_OBJ_8F
    const ANIM_OBJ_90
    const ANIM_OBJ_91
    const ANIM_OBJ_92
    const ANIM_OBJ_93
    const ANIM_OBJ_94
    const ANIM_OBJ_95
    const ANIM_OBJ_96
    const ANIM_OBJ_97
    const ANIM_OBJ_98
    const ANIM_OBJ_99
    const ANIM_OBJ_9A
    const ANIM_OBJ_9B
    const ANIM_OBJ_9C
    const ANIM_OBJ_9D
    const ANIM_OBJ_9E
    const ANIM_OBJ_9F
    const ANIM_OBJ_A0
    const ANIM_OBJ_A1
    const ANIM_OBJ_A2
    const ANIM_OBJ_A3
    const ANIM_OBJ_A4
    const ANIM_OBJ_A5
    const ANIM_OBJ_A6
    const ANIM_OBJ_A7
    const ANIM_OBJ_A8
    const ANIM_OBJ_A9
    const ANIM_OBJ_AA
    const ANIM_OBJ_AB
    const ANIM_OBJ_AC
    const ANIM_OBJ_AD
    const ANIM_OBJ_AE
    const ANIM_OBJ_AF
    const ANIM_OBJ_B0
    const ANIM_OBJ_B1
    const ANIM_OBJ_B2
    const ANIM_OBJ_B3
    const ANIM_OBJ_B4
    const ANIM_OBJ_B5
    const ANIM_OBJ_FLOWER
    const ANIM_OBJ_COTTON
    const ANIM_OBJ_B8
    const ANIM_OBJ_B9
    const ANIM_OBJ_BA
    const ANIM_OBJ_BB

	const_def
	const BATTLEANIMFUNC_00
    const BATTLEANIMFUNC_01
    const BATTLEANIMFUNC_02
    const BATTLEANIMFUNC_03
    const BATTLEANIMFUNC_04
    const BATTLEANIMFUNC_05
    const BATTLEANIMFUNC_06
    const BATTLEANIMFUNC_07
    const BATTLEANIMFUNC_08
    const BATTLEANIMFUNC_09
    const BATTLEANIMFUNC_0A
    const BATTLEANIMFUNC_0B
    const BATTLEANIMFUNC_0C
    const BATTLEANIMFUNC_0D
    const BATTLEANIMFUNC_0E
    const BATTLEANIMFUNC_0F
    const BATTLEANIMFUNC_10
    const BATTLEANIMFUNC_11
    const BATTLEANIMFUNC_12
    const BATTLEANIMFUNC_13
    const BATTLEANIMFUNC_14
    const BATTLEANIMFUNC_15
    const BATTLEANIMFUNC_16
    const BATTLEANIMFUNC_17
    const BATTLEANIMFUNC_18
    const BATTLEANIMFUNC_19
    const BATTLEANIMFUNC_1A
    const BATTLEANIMFUNC_1B
    const BATTLEANIMFUNC_1C
    const BATTLEANIMFUNC_1D
    const BATTLEANIMFUNC_1E
    const BATTLEANIMFUNC_1F
    const BATTLEANIMFUNC_20
    const BATTLEANIMFUNC_21
    const BATTLEANIMFUNC_22
    const BATTLEANIMFUNC_23
    const BATTLEANIMFUNC_24
    const BATTLEANIMFUNC_25
    const BATTLEANIMFUNC_26
    const BATTLEANIMFUNC_27
    const BATTLEANIMFUNC_28
    const BATTLEANIMFUNC_29
    const BATTLEANIMFUNC_2A
    const BATTLEANIMFUNC_2B
    const BATTLEANIMFUNC_2C
    const BATTLEANIMFUNC_2D
    const BATTLEANIMFUNC_2E
    const BATTLEANIMFUNC_2F
    const BATTLEANIMFUNC_30
    const BATTLEANIMFUNC_31
    const BATTLEANIMFUNC_32
    const BATTLEANIMFUNC_33
    const BATTLEANIMFUNC_34
    const BATTLEANIMFUNC_35
    const BATTLEANIMFUNC_36
    const BATTLEANIMFUNC_37
    const BATTLEANIMFUNC_38
    const BATTLEANIMFUNC_39
    const BATTLEANIMFUNC_3A
    const BATTLEANIMFUNC_3B
    const BATTLEANIMFUNC_3C
    const BATTLEANIMFUNC_3D
    const BATTLEANIMFUNC_3E
    const BATTLEANIMFUNC_3F
    const BATTLEANIMFUNC_40
    const BATTLEANIMFUNC_41
    const BATTLEANIMFUNC_42
    const BATTLEANIMFUNC_43
    const BATTLEANIMFUNC_44
    const BATTLEANIMFUNC_45
    const BATTLEANIMFUNC_46
    const BATTLEANIMFUNC_47
    const BATTLEANIMFUNC_48
    const BATTLEANIMFUNC_49
    const BATTLEANIMFUNC_4A
    const BATTLEANIMFUNC_4B
    const BATTLEANIMFUNC_4C
    const BATTLEANIMFUNC_4D
    const BATTLEANIMFUNC_4E
    const BATTLEANIMFUNC_4F



const_value SET 1
	const ANIM_BG_FLASH_INVERTED
	const ANIM_BG_FLASH_WHITE
	const ANIM_BG_WHITE_HUES
	const ANIM_BG_BLACK_HUES
	const ANIM_BG_ALTERNATE_HUES
	const ANIM_BG_06
	const ANIM_BG_07
	const ANIM_BG_08
	const ANIM_BG_HIDE_MON
	const ANIM_BG_SHOW_MON
	const ANIM_BG_ENTER_MON
	const ANIM_BG_RETURN_MON
	const ANIM_BG_SURF
	const ANIM_BG_WHIRLPOOL
	const ANIM_BG_TELEPORT
	const ANIM_BG_NIGHT_SHADE
	const ANIM_BG_FEET_FOLLOW
	const ANIM_BG_HEAD_FOLLOW
	const ANIM_BG_DOUBLE_TEAM
	const ANIM_BG_ACID_ARMOR
	const ANIM_BG_RAPID_FLASH
	const ANIM_BG_16
	const ANIM_BG_17
	const ANIM_BG_18
	const ANIM_BG_19
	const ANIM_BG_1A
	const ANIM_BG_1B
	const ANIM_BG_1C
	const ANIM_BG_1D
	const ANIM_BG_1E
	const ANIM_BG_1F
	const ANIM_BG_20
	const ANIM_BG_21
	const ANIM_BG_22
	const ANIM_BG_23
	const ANIM_BG_TACKLE
	const ANIM_BG_25
	const ANIM_BG_26
	const ANIM_BG_27
	const ANIM_BG_28
	const ANIM_BG_PSYCHIC
	const ANIM_BG_2A
	const ANIM_BG_2B
	const ANIM_BG_2C
	const ANIM_BG_2D
	const ANIM_BG_2E
	const ANIM_BG_2F
	const ANIM_BG_30
	const ANIM_BG_31
	const ANIM_BG_32
	const ANIM_BG_VIBRATE_MON
	const ANIM_BG_WOBBLE_MON
	const ANIM_BG_35

	const_def
	const ANIM_MON_SLOW    ; 0
	const ANIM_MON_NORMAL  ; 1
	const ANIM_MON_MENU    ; 2
	const ANIM_MON_TRADE   ; 3
	const ANIM_MON_EVOLVE  ; 4
	const ANIM_MON_HATCH   ; 5
	const ANIM_MON_UNUSED  ; 6
	const ANIM_MON_EGG1    ; 7
	const ANIM_MON_EGG2    ; 8

	const_def
	const BG_EFFECT_STRUCT_FUNCTION
	const BG_EFFECT_STRUCT_JT_INDEX
	const BG_EFFECT_STRUCT_02
	const BG_EFFECT_STRUCT_03
