	const_def
	const SCGB_BATTLE_GRAYSCALE
	const SCGB_BATTLE_COLORS
	const SCGB_POKEGEAR_PALS
	const SCGB_STATS_SCREEN_HP_PALS
	const SCGB_POKEDEX
	const SCGB_SLOT_MACHINE
	const SCGB_06
	const SCGB_07
	const SCGB_08
	const SCGB_MAPPALS
	const SCGB_0A
	const SCGB_0B
	const SCGB_0C
	const SCGB_0D
	const SCGB_0E
	const SCGB_0F
	const SCGB_POKEDEX_SEARCH_OPTION
	const SCGB_11
	const SCGB_POKEPIC
	const SCGB_13
	const SCGB_PACKPALS
	const SCGB_TRAINER_CARD
	const SCGB_POKEDEX_UNOWN_MODE
	const SCGB_17
	const SCGB_18
	const SCGB_19
	const SCGB_1A
	const SCGB_1B
	const SCGB_FRONTPICPALS
	const SCGB_1D
	const SCGB_1E

SCGB_PARTY_MENU_HP_PALS  EQU -4
SCGB_RAM EQU -1
