ENGINE_RADIO_CARD                            EQU $00
ENGINE_MAP_CARD                              EQU $01
ENGINE_PHONE_CARD                            EQU $02
ENGINE_EXPN_CARD                             EQU $03
ENGINE_POKEGEAR                              EQU $04
ENGINE_DAYCARE_MONS_ARE_COMPATIBLE           EQU $05
ENGINE_DAYCARE_MAN_HAS_MON                   EQU $06
ENGINE_DAYCARE_LADY_HAS_MON                  EQU $07
ENGINE_MOM_SAVING_MONEY                      EQU $08
ENGINE_DST                                   EQU $09
ENGINE_0A                                    EQU $0a
ENGINE_POKEDEX                               EQU $0b
ENGINE_UNOWN_DEX                             EQU $0c
ENGINE_POKERUS                               EQU $0d
ENGINE_ROCKET_SIGNAL_ON_CH20                 EQU $0e
ENGINE_CREDITS_SKIP                          EQU $0f
ENGINE_BUG_CONTEST_ON                        EQU $10
ENGINE_BUG_CONTEST_TIMER                     EQU $11
ENGINE_ROCKETS_IN_RADIO_TOWER                EQU $12
ENGINE_BIKE_SHOP_CALL_ENABLED                EQU $13
ENGINE_14                                    EQU $14
ENGINE_GIVE_POKERUS                          EQU $15
ENGINE_16                                    EQU $16
ENGINE_ROCKETS_IN_MAHOGANY                   EQU $17
ENGINE_STRENGTH_ACTIVE                       EQU $18
ENGINE_ALWAYS_ON_BIKE                        EQU $19
ENGINE_DOWNHILL                              EQU $1a
ENGINE_ZEPHYRBADGE                           EQU $1b
ENGINE_HIVEBADGE                             EQU $1c
ENGINE_PLAINBADGE                            EQU $1d
ENGINE_FOGBADGE                              EQU $1e
ENGINE_MINERALBADGE                          EQU $1f
ENGINE_STORMBADGE                            EQU $20
ENGINE_GLACIERBADGE                          EQU $21
ENGINE_RISINGBADGE                           EQU $22
ENGINE_BOULDERBADGE                          EQU $23
ENGINE_CASCADEBADGE                          EQU $24
ENGINE_THUNDERBADGE                          EQU $25
ENGINE_RAINBOWBADGE                          EQU $26
ENGINE_SOULBADGE                             EQU $27
ENGINE_MARSHBADGE                            EQU $28
ENGINE_VOLCANOBADGE                          EQU $29
ENGINE_EARTHBADGE                            EQU $2a
ENGINE_UNLOCKED_UNOWNS_1                     EQU $2b
ENGINE_UNLOCKED_UNOWNS_2                     EQU $2c
ENGINE_UNLOCKED_UNOWNS_3                     EQU $2d
ENGINE_UNLOCKED_UNOWNS_4                     EQU $2e
ENGINE_UNLOCKED_UNOWNS_5                     EQU $2f
ENGINE_UNLOCKED_UNOWNS_6                     EQU $30
ENGINE_UNLOCKED_UNOWNS_7                     EQU $31
ENGINE_UNLOCKED_UNOWNS_8                     EQU $32
ENGINE_FLYPOINT_KRISS_HOUSE                  EQU $33
ENGINE_FLYPOINT_VIRIDIAN_POKECENTER          EQU $34
ENGINE_FLYPOINT_PALLET                       EQU $35
ENGINE_FLYPOINT_VIRIDIAN                     EQU $36
ENGINE_FLYPOINT_PEWTER                       EQU $37
ENGINE_FLYPOINT_CERULEAN                     EQU $38
ENGINE_FLYPOINT_ROCK_TUNNEL                  EQU $39
ENGINE_FLYPOINT_VERMILION                    EQU $3a
ENGINE_FLYPOINT_LAVENDER                     EQU $3b
ENGINE_FLYPOINT_SAFFRON                      EQU $3c
ENGINE_FLYPOINT_CELADON                      EQU $3d
ENGINE_FLYPOINT_FUCHSIA                      EQU $3e
ENGINE_FLYPOINT_CINNABAR                     EQU $3f
ENGINE_FLYPOINT_INDIGO_PLATEAU               EQU $40
ENGINE_FLYPOINT_NEW_BARK                     EQU $41
ENGINE_FLYPOINT_CHERRYGROVE                  EQU $42
ENGINE_FLYPOINT_VIOLET                       EQU $43
ENGINE_FLYPOINT_AZALEA                       EQU $44
ENGINE_FLYPOINT_CIANWOOD                     EQU $45
ENGINE_FLYPOINT_GOLDENROD                    EQU $46
ENGINE_FLYPOINT_OLIVINE                      EQU $47
ENGINE_FLYPOINT_ECRUTEAK                     EQU $48
ENGINE_FLYPOINT_MAHOGANY                     EQU $49
ENGINE_FLYPOINT_LAKE_OF_RAGE                 EQU $4a
ENGINE_FLYPOINT_BLACKTHORN                   EQU $4b
ENGINE_FLYPOINT_SILVER_CAVE                  EQU $4c
ENGINE_FLYPOINT_UNUSED                       EQU $4d
ENGINE_LUCKY_NUMBER_SHOW                     EQU $4e
ENGINE_4F                                    EQU $4f
ENGINE_KURT_MAKING_BALLS                     EQU $50
ENGINE_51                                    EQU $51
ENGINE_SPECIAL_WILDDATA                      EQU $52
ENGINE_TIME_CAPSULE                          EQU $53
ENGINE_ALL_FRUIT_TREES                       EQU $54
ENGINE_SHUCKLE_GIVEN                         EQU $55
ENGINE_GOLDENROD_UNDERGROUND_MERCHANT_CLOSED EQU $56
ENGINE_FOUGHT_IN_TRAINER_HALL_TODAY          EQU $57
ENGINE_MT_MOON_SQUARE_CLEFAIRY               EQU $58
ENGINE_UNION_CAVE_LAPRAS                     EQU $59
ENGINE_GOLDENROD_UNDERGROUND_GOT_HAIRCUT     EQU $5a
ENGINE_GOLDENROD_MALL_5F_HAPPINESS_EVENT     EQU $5b
ENGINE_TEA_IN_BLUES_HOUSE                    EQU $5c
ENGINE_INDIGO_PLATEAU_RIVAL_FIGHT            EQU $5d
ENGINE_5E                                    EQU $5e
ENGINE_5F                                    EQU $5f
ENGINE_60                                    EQU $60
ENGINE_GOLDENROD_DEPT_STORE_SALE_IS_ON       EQU $61
ENGINE_62                                    EQU $62
ENGINE_PLAYER_IS_FEMALE                      EQU $63
ENGINE_HAVE_EXAMINED_GS_BALL                 EQU $64
ENGINE_JACK                                  EQU $65
ENGINE_HUEY                                  EQU $66
ENGINE_GAVEN                                 EQU $67
ENGINE_BETH                                  EQU $68
ENGINE_JOSE                                  EQU $69
ENGINE_REENA                                 EQU $6a
ENGINE_JOEY                                  EQU $6b
ENGINE_WADE                                  EQU $6c
ENGINE_RALPH                                 EQU $6d
ENGINE_LIZ                                   EQU $6e
ENGINE_ANTHONY                               EQU $6f
ENGINE_TODD                                  EQU $70
ENGINE_GINA                                  EQU $71
ENGINE_ARNIE                                 EQU $72
ENGINE_ALAN                                  EQU $73
ENGINE_DANA                                  EQU $74
ENGINE_CHAD                                  EQU $75
ENGINE_TULLY                                 EQU $76
ENGINE_BRENT                                 EQU $77
ENGINE_TIFFANY                               EQU $78
ENGINE_VANCE                                 EQU $79
ENGINE_WILTON                                EQU $7a
ENGINE_PARRY                                 EQU $7b
ENGINE_ERIN                                  EQU $7c
ENGINE_BEVERLY_HAS_NUGGET                    EQU $7d
ENGINE_JOSE_HAS_STAR_PIECE                   EQU $7e
ENGINE_WADE_HAS_ITEM                         EQU $7f
ENGINE_GINA_HAS_LEAF_STONE                   EQU $80
ENGINE_ALAN_HAS_FIRE_STONE                   EQU $81
ENGINE_LIZ_HAS_THUNDERSTONE                  EQU $82
ENGINE_DEREK_HAS_NUGGET                      EQU $83
ENGINE_TULLY_HAS_WATER_STONE                 EQU $84
ENGINE_TIFFANY_HAS_PINK_BOW                  EQU $85
ENGINE_WILTON_HAS_ITEM                       EQU $86
ENGINE_87                                    EQU $87
ENGINE_88                                    EQU $88
ENGINE_89                                    EQU $89
ENGINE_8A                                    EQU $8a
ENGINE_8B                                    EQU $8b
ENGINE_8C                                    EQU $8c
ENGINE_8D                                    EQU $8d
ENGINE_8E                                    EQU $8e
ENGINE_8F                                    EQU $8f
ENGINE_90                                    EQU $90
ENGINE_91                                    EQU $91
ENGINE_92                                    EQU $92
ENGINE_93                                    EQU $93
ENGINE_94                                    EQU $94
ENGINE_95                                    EQU $95
ENGINE_96                                    EQU $96
ENGINE_97                                    EQU $97
ENGINE_98                                    EQU $98
ENGINE_99                                    EQU $99
ENGINE_9A                                    EQU $9a
ENGINE_9B                                    EQU $9b
ENGINE_9C                                    EQU $9c
ENGINE_9D                                    EQU $9d
ENGINE_9E                                    EQU $9e
ENGINE_KRIS_IN_CABLE_CLUB                    EQU $9f
ENGINE_DUNSPARCE_SWARM                       EQU $a0
ENGINE_YANMA_SWARM                           EQU $a1
