EVENT_GOT_TM31_MUD_SLAP                                EQU $008
EVENT_GOT_TM49_FURY_CUTTER                             EQU $009
EVENT_GOT_TM01_DYNAMICPUNCH                            EQU $00a
EVENT_GOT_TM45_ATTRACT                                 EQU $00b
EVENT_GOT_TM30_SHADOW_BALL                             EQU $00c
EVENT_GOT_TM23_IRON_TAIL                               EQU $00d
EVENT_GOT_TM16_ICY_WIND                                EQU $00e
EVENT_GOT_TM24_DRAGONBREATH                            EQU $00f
EVENT_GOT_HM01_CUT                                     EQU $010
EVENT_GOT_HM02_FLY                                     EQU $011
EVENT_GOT_HM03_SURF                                    EQU $012
EVENT_GOT_HM04_STRENGTH                                EQU $013
EVENT_GOT_HM05_FLASH                                   EQU $014
EVENT_GOT_HM06_WHIRLPOOL                               EQU $015
EVENT_GOT_OLD_ROD                                      EQU $017
EVENT_GOT_GOOD_ROD                                     EQU $018
EVENT_GOT_SUPER_ROD                                    EQU $019
EVENT_GOT_A_POKEMON_FROM_ELM                           EQU $01a
EVENT_GOT_CYNDAQUIL_FROM_ELM                           EQU $01b
EVENT_GOT_TOTODILE_FROM_ELM                            EQU $01c
EVENT_GOT_CHIKORITA_FROM_ELM                           EQU $01d
EVENT_GOT_MYSTERY_EGG_FROM_MR_POKEMON                  EQU $01e
EVENT_GAVE_MYSTERY_EGG_TO_ELM                          EQU $01f
EVENT_JASMINE_RETURNED_TO_GYM                          EQU $020
EVENT_CLEARED_RADIO_TOWER                              EQU $021
EVENT_CLEARED_ROCKET_HIDEOUT                           EQU $022
EVENT_GOT_SECRETPOTION_FROM_PHARMACY                   EQU $023
EVENT_GOT_SS_TICKET_FROM_ELM                           EQU $024
EVENT_USED_THE_CARD_KEY_IN_THE_RADIO_TOWER             EQU $025
EVENT_REFUSED_TO_HELP_LANCE_AT_LAKE_OF_RAGE            EQU $026
EVENT_GOT_BERRY_FROM_ROUTE_30_HOUSE                    EQU $027
EVENT_MADE_WHITNEY_CRY                                 EQU $028
EVENT_FOUGHT_SUDOWOODO                                 EQU $02a
EVENT_CLEARED_SLOWPOKE_WELL                            EQU $02b
EVENT_REFUSED_TO_TAKE_EGG_FROM_ELMS_AIDE               EQU $02c
EVENT_GOT_TOGEPI_EGG_FROM_ELMS_AIDE                    EQU $02d
EVENT_MADE_UNOWN_APPEAR_IN_RUINS                       EQU $02e
EVENT_HEALED_MOOMOO                                    EQU $03d
EVENT_GOT_TM13_SNORE_FROM_MOOMOO_FARM                  EQU $03e
EVENT_TALKED_TO_FARMER_ABOUT_MOOMOO                    EQU $03f
EVENT_TALKED_TO_MOM_AFTER_MYSTERY_EGG_QUEST            EQU $040
EVENT_DUDE_TALKED_TO_YOU                               EQU $041
EVENT_LEARNED_TO_CATCH_POKEMON                         EQU $042
EVENT_ELM_CALLED_ABOUT_STOLEN_POKEMON                  EQU $043
EVENT_GOT_SHUCKIE                                      EQU $045
EVENT_MANIA_TOOK_SHUCKIE_OR_LET_YOU_KEEP_HIM           EQU $046
EVENT_GOT_SUNNY_DAY_FROM_RADIO_TOWER                   EQU $047
EVENT_GOT_PINK_BOW_FROM_MARY                           EQU $048
EVENT_USED_BASEMENT_KEY                                EQU $049
EVENT_GOT_TM08_ROCK_SMASH                              EQU $04b
EVENT_GOT_MYSTIC_WATER_IN_CHERRYGROVE                  EQU $04d
EVENT_GOT_TM05_ROAR                                    EQU $04e
EVENT_GOT_EEVEE                                        EQU $04f
EVENT_GOT_KENYA                                        EQU $050
EVENT_GAVE_KENYA                                       EQU $051
EVENT_GOT_HP_UP_FROM_RANDY                             EQU $052
EVENT_GOT_TM50_NIGHTMARE                               EQU $053
EVENT_TOGEPI_HATCHED                                   EQU $054
EVENT_SHOWED_TOGEPI_TO_ELM                             EQU $055
EVENT_GOT_EVERSTONE_FROM_ELM                           EQU $056
EVENT_GOT_QUICK_CLAW                                   EQU $057
EVENT_GOT_TM10_HIDDEN_POWER                            EQU $058
EVENT_GOT_TM36_SLUDGE_BOMB                             EQU $059
EVENT_GOT_ITEMFINDER                                   EQU $05a
EVENT_GOT_BICYCLE                                      EQU $05b
EVENT_GOT_SQUIRTBOTTLE                                 EQU $05c
EVENT_GOT_MIRACLE_SEED_IN_ROUTE_32                     EQU $05d
EVENT_GOT_CHARCOAL_IN_CHARCOAL_KILN                    EQU $05e
EVENT_GOT_TM02_HEADBUTT                                EQU $05f
EVENT_DECIDED_TO_HELP_LANCE                            EQU $060
EVENT_GOT_TYROGUE_FROM_KIYO                            EQU $061
EVENT_MET_FRIEDA_OF_FRIDAY                             EQU $062
EVENT_GOT_POISON_BARB_FROM_FRIEDA                      EQU $063
EVENT_MET_TUSCANY_OF_TUESDAY                           EQU $064
EVENT_GOT_PINK_BOW_FROM_TUSCANY                        EQU $065
EVENT_MET_ARTHUR_OF_THURSDAY                           EQU $066
EVENT_GOT_HARD_STONE_FROM_ARTHUR                       EQU $067
EVENT_MET_SUNNY_OF_SUNDAY                              EQU $068
EVENT_GOT_MAGNET_FROM_SUNNY                            EQU $069
EVENT_MET_WESLEY_OF_WEDNESDAY                          EQU $06a
EVENT_GOT_BLACKBELT_FROM_WESLEY                        EQU $06b
EVENT_MET_SANTOS_OF_SATURDAY                           EQU $06c
EVENT_GOT_SPELL_TAG_FROM_SANTOS                        EQU $06d
EVENT_MET_MONICA_OF_MONDAY                             EQU $06e
EVENT_GOT_SHARP_BEAK_FROM_MONICA                       EQU $06f
EVENT_GOT_SOFT_SAND_FROM_KATE                          EQU $070
EVENT_GOT_METAL_COAT_FROM_GRANDPA_ON_SS_AQUA           EQU $071
EVENT_GOT_BLACKGLASSES_IN_DARK_CAVE                    EQU $072
EVENT_GOT_KINGS_ROCK_IN_SLOWPOKE_WELL                  EQU $073
EVENT_GOT_TM47_STEEL_WING                              EQU $074
EVENT_GOT_TM37_SANDSTORM                               EQU $075
EVENT_TOLD_ELM_ABOUT_TOGEPI_OVER_THE_PHONE             EQU $077
EVENT_GOT_CLEAR_BELL                                   EQU $078
EVENT_GOT_SILVER_WING                                  EQU $079
EVENT_GOT_TM12_SWEET_SCENT                             EQU $07a
EVENT_RELEASED_THE_BEASTS                              EQU $07b
EVENT_GOT_MASTER_BALL_FROM_ELM                         EQU $07c
EVENT_FOUND_REVIVE_IN_ROCKET_BASE_B1F                  EQU $086
EVENT_CAN_GIVE_GS_BALL_TO_KURT                         EQU $0be
EVENT_RETURNED_MACHINE_PART                            EQU $0c9
EVENT_MET_MANAGER_AT_POWER_PLANT                       EQU $0ca
EVENT_MET_ROCKET_GRUNT_AT_CERULEAN_GYM                 EQU $0cb
EVENT_MET_REDS_MOM                                     EQU $0cc
EVENT_RESTORED_POWER_TO_KANTO                          EQU $0cd
EVENT_GOT_COINS_FROM_GAMBLER_AT_CELADON                EQU $0ce
EVENT_MET_COPYCAT_FOUND_OUT_ABOUT_LOST_ITEM            EQU $0cf
EVENT_RETURNED_LOST_ITEM_TO_COPYCAT                    EQU $0d0
EVENT_GOT_PASS_FROM_COPYCAT                            EQU $0d1
EVENT_GOT_LOST_ITEM_FROM_FAN_CLUB                      EQU $0d2
EVENT_LISTENED_TO_FAN_CLUB_PRESIDENT_BUT_BAG_WAS_FULL  EQU $0d3
EVENT_LISTENED_TO_FAN_CLUB_PRESIDENT                   EQU $0d4
EVENT_TALKED_TO_SEAFOAM_GYM_GUY_ONCE                   EQU $0d5
EVENT_ENABLE_DIPLOMA_PRINTING                          EQU $0d6
EVENT_CLEARED_NUGGET_BRIDGE                            EQU $0d8
EVENT_TALKED_TO_WARDENS_GRANDDAUGHTER                  EQU $0d9
EVENT_GOT_TM03_CURSE                                   EQU $0da
EVENT_GOT_CLEANSE_TAG                                  EQU $0db
EVENT_GOT_TM19_GIGA_DRAIN                              EQU $0dc
EVENT_GOT_TM06_TOXIC                                   EQU $0dd
EVENT_GOT_UP_GRADE                                     EQU $0de
EVENT_GOT_TM07_ZAP_CANNON                              EQU $0df
EVENT_GOT_TM42_DREAM_EATER                             EQU $0e0
EVENT_GOT_TM29_PSYCHIC                                 EQU $0e3
EVENT_FOUND_LEFTOVERS_IN_CELADON_CAFE                  EQU $0f9
EVENT_FOUND_MACHINE_PART_IN_CERULEAN_GYM               EQU $0fb
EVENT_SHOWED_BEVERLY_MARILL                            EQU $261
EVENT_SHOWED_DEREK_PIKACHU                             EQU $28d
EVENT_SHOWED_TIFFANY_CLEFAIRY                          EQU $293
EVENT_BUENA_OFFERED_HER_PHONE_NUMBER_NO_BLUE_CARD      EQU $29e
EVENT_SWITCH_1                                         EQU $2d3
EVENT_SWITCH_2                                         EQU $2d4
EVENT_SWITCH_3                                         EQU $2d5
EVENT_EMERGENCY_SWITCH                                 EQU $2d6
EVENT_SWITCH_4                                         EQU $2d7
EVENT_SWITCH_5                                         EQU $2d8
EVENT_SWITCH_6                                         EQU $2d9
EVENT_SWITCH_7                                         EQU $2da
EVENT_SWITCH_8                                         EQU $2db
EVENT_SWITCH_9                                         EQU $2dc
EVENT_SWITCH_10                                        EQU $2dd
EVENT_SWITCH_11                                        EQU $2de
EVENT_SWITCH_12                                        EQU $2df
EVENT_SWITCH_13                                        EQU $2e0
EVENT_SWITCH_14                                        EQU $2e1
EVENT_UNCOVERED_STAIRCASE_IN_MAHOGANY_MART             EQU $2e2
EVENT_TURNED_OFF_SECURITY_CAMERAS                      EQU $2e3
EVENT_SECURITY_CAMERA_1                                EQU $2e4
EVENT_SECURITY_CAMERA_2                                EQU $2e5
EVENT_SECURITY_CAMERA_3                                EQU $2e6
EVENT_SECURITY_CAMERA_4                                EQU $2e7
EVENT_SECURITY_CAMERA_5                                EQU $2e8
EVENT_EXPLODING_TRAP_1                                 EQU $2e9
EVENT_EXPLODING_TRAP_2                                 EQU $2ea
EVENT_EXPLODING_TRAP_3                                 EQU $2eb
EVENT_EXPLODING_TRAP_4                                 EQU $2ec
EVENT_EXPLODING_TRAP_5                                 EQU $2ed
EVENT_EXPLODING_TRAP_6                                 EQU $2ee
EVENT_EXPLODING_TRAP_7                                 EQU $2ef
EVENT_EXPLODING_TRAP_8                                 EQU $2f0
EVENT_EXPLODING_TRAP_9                                 EQU $2f1
EVENT_EXPLODING_TRAP_10                                EQU $2f2
EVENT_EXPLODING_TRAP_11                                EQU $2f3
EVENT_EXPLODING_TRAP_12                                EQU $2f4
EVENT_EXPLODING_TRAP_13                                EQU $2f5
EVENT_EXPLODING_TRAP_14                                EQU $2f6
EVENT_EXPLODING_TRAP_15                                EQU $2f7
EVENT_EXPLODING_TRAP_16                                EQU $2f8
EVENT_EXPLODING_TRAP_17                                EQU $2f9
EVENT_EXPLODING_TRAP_18                                EQU $2fa
EVENT_EXPLODING_TRAP_19                                EQU $2fb
EVENT_EXPLODING_TRAP_20                                EQU $2fc
EVENT_EXPLODING_TRAP_21                                EQU $2fd
EVENT_EXPLODING_TRAP_22                                EQU $2fe
EVENT_LEARNED_HAIL_GIOVANNI                            EQU $2ff
EVENT_OPENED_DOOR_TO_ROCKET_HIDEOUT_TRANSMITTER        EQU $300
EVENT_WILLS_ROOM_EXIT_OPEN                             EQU $30a
EVENT_WILLS_ROOM_ENTRANCE_CLOSED                       EQU $30b
EVENT_KOGAS_ROOM_EXIT_OPEN                             EQU $30c
EVENT_KOGAS_ROOM_ENTRANCE_CLOSED                       EQU $30d
EVENT_BRUNOS_ROOM_EXIT_OPEN                            EQU $30e
EVENT_KARENS_ROOM_ENTRANCE_CLOSED                      EQU $30f
EVENT_KARENS_ROOM_EXIT_OPEN                            EQU $310
EVENT_LANCES_ROOM_ENTRANCE_CLOSED                      EQU $311
EVENT_FOUGHT_HO_OH                                     EQU $317
EVENT_FOUGHT_LUGIA                                     EQU $318
EVENT_BEAT_RIVAL_IN_MT_MOON                            EQU $319
EVENT_MET_BILLS_GRANDPA                                EQU $31a
EVENT_SHOWED_LICKITUNG_TO_BILLS_GRANDPA                EQU $31b
EVENT_SHOWED_ODDISH_TO_BILLS_GRANDPA                   EQU $31c
EVENT_SHOWED_STARYU_TO_BILLS_GRANDPA                   EQU $31d
EVENT_SHOWED_GROWLITHE_VULPIX_TO_BILLS_GRANDPA         EQU $31e
EVENT_SHOWED_PICHU_TO_BILLS_GRANDPA                    EQU $31f
EVENT_GOT_EVERSTONE_FROM_BILLS_GRANDPA                 EQU $320
EVENT_GOT_LEAF_STONE_FROM_BILLS_GRANDPA                EQU $321
EVENT_GOT_WATER_STONE_FROM_BILLS_GRANDPA               EQU $322
EVENT_GOT_FIRE_STONE_FROM_BILLS_GRANDPA                EQU $323
EVENT_GOT_THUNDERSTONE_FROM_BILLS_GRANDPA              EQU $324
EVENT_LISTENED_TO_RADIO_IN_NEIGHBORS_HOUSE             EQU $325
EVENT_WALL_OPENED_IN_HO_OH_CHAMBER                     EQU $326
EVENT_WALL_OPENED_IN_KABUTO_CHAMBER                    EQU $327
EVENT_WALL_OPENED_IN_OMANYTE_CHAMBER                   EQU $328
EVENT_WALL_OPENED_IN_AERODACTYL_CHAMBER                EQU $329
EVENT_WADE_HAS_BERRY                                   EQU $32b
EVENT_WADE_HAS_PSNCUREBERRY                            EQU $32c
EVENT_WADE_HAS_PRZCUREBERRY                            EQU $32d
EVENT_WADE_HAS_BITTER_BERRY                            EQU $32e
EVENT_WILTON_HAS_ULTRA_BALL                            EQU $32f
EVENT_WILTON_HAS_GREAT_BALL                            EQU $330
EVENT_WILTON_HAS_POKE_BALL                             EQU $331
EVENT_KOJI_ALLOWS_YOU_PASSAGE_TO_TIN_TOWER             EQU $334
EVENT_FOUGHT_SUICUNE                                   EQU $335
EVENT_GOT_RAINBOW_WING                                 EQU $336
EVENT_HUEY_PROTEIN                                     EQU $337
EVENT_JOEY_HP_UP                                       EQU $338
EVENT_VANCE_CARBOS                                     EQU $339
EVENT_PARRY_IRON                                       EQU $33a
EVENT_ERIN_CALCIUM                                     EQU $33b
EVENT_BUENA_OFFERED_HER_PHONE_NUMBER                   EQU $33c
EVENT_MET_BUENA                                        EQU $33d
EVENT_GOT_ODD_EGG                                      EQU $33e
EVENT_GOT_GS_BALL_FROM_POKECOM_CENTER                  EQU $340
EVENT_BEAT_SWIMMERF_ELAINE                             EQU $3e8
EVENT_BEAT_SWIMMERF_PAULA                              EQU $3e9
EVENT_BEAT_SWIMMERF_KAYLEE                             EQU $3ea
EVENT_BEAT_SWIMMERF_SUSIE                              EQU $3eb
EVENT_BEAT_SWIMMERF_DENISE                             EQU $3ec
EVENT_BEAT_SWIMMERF_KARA                               EQU $3ed
EVENT_BEAT_SWIMMERF_WENDY                              EQU $3ee
EVENT_BEAT_SWIMMERF_DAWN                               EQU $3f3
EVENT_BEAT_SWIMMERF_NICOLE                             EQU $3f5
EVENT_BEAT_SWIMMERF_LORI                               EQU $3f6
EVENT_BEAT_SWIMMERF_NIKKI                              EQU $3f8
EVENT_BEAT_SWIMMERF_DIANA                              EQU $3f9
EVENT_BEAT_SWIMMERF_BRIANA                             EQU $3fa
EVENT_BEAT_BIRD_KEEPER_ROD                             EQU $3fb
EVENT_BEAT_BIRD_KEEPER_ABE                             EQU $3fc
EVENT_BEAT_BIRD_KEEPER_BRYAN                           EQU $3fd
EVENT_BEAT_BIRD_KEEPER_THEO                            EQU $3fe
EVENT_BEAT_BIRD_KEEPER_TOBY                            EQU $3ff
EVENT_BEAT_BIRD_KEEPER_DENIS                           EQU $400
EVENT_BEAT_BIRD_KEEPER_VANCE_1                         EQU $401
EVENT_BEAT_BIRD_KEEPER_HANK                            EQU $402
EVENT_BEAT_BIRD_KEEPER_ROY                             EQU $403
EVENT_BEAT_BIRD_KEEPER_BORIS                           EQU $404
EVENT_BEAT_BIRD_KEEPER_BOB                             EQU $405
EVENT_BEAT_BIRD_KEEPER_PETER                           EQU $407
EVENT_BEAT_BIRD_KEEPER_JOSE                            EQU $408
EVENT_BEAT_BIRD_KEEPER_PERRY                           EQU $409
EVENT_BEAT_BIRD_KEEPER_BRET                            EQU $40a
EVENT_BEAT_BOARDER_RONALD                              EQU $40e
EVENT_BEAT_BOARDER_BRAD                                EQU $40f
EVENT_BEAT_BOARDER_DOUGLAS                             EQU $410
EVENT_BEAT_SAGE_CHOW                                   EQU $411
EVENT_BEAT_SAGE_NICO                                   EQU $412
EVENT_BEAT_SAGE_JIN                                    EQU $413
EVENT_BEAT_SAGE_TROY                                   EQU $414
EVENT_BEAT_SAGE_JEFFREY                                EQU $415
EVENT_BEAT_SAGE_PING                                   EQU $416
EVENT_BEAT_SAGE_EDMOND                                 EQU $417
EVENT_BEAT_SAGE_NEAL                                   EQU $418
EVENT_BEAT_SAGE_LI                                     EQU $419
EVENT_BEAT_CAMPER_ROLAND                               EQU $41a
EVENT_BEAT_CAMPER_TODD_1                               EQU $41b
EVENT_BEAT_CAMPER_IVAN                                 EQU $41c
EVENT_BEAT_CAMPER_ELLIOT                               EQU $41d
EVENT_BEAT_CAMPER_LLOYD                                EQU $41f
EVENT_BEAT_CAMPER_DEAN                                 EQU $420
EVENT_BEAT_CAMPER_SID                                  EQU $421
EVENT_BEAT_CAMPER_TED                                  EQU $424
EVENT_BEAT_CAMPER_JERRY                                EQU $42b
EVENT_BEAT_CAMPER_SPENCER                              EQU $42c
EVENT_BEAT_BURGLAR_DUNCAN                              EQU $42d
EVENT_BEAT_BURGLAR_EDDIE                               EQU $42e
EVENT_BEAT_BURGLAR_COREY                               EQU $42f
EVENT_BEAT_BIKER_DWAYNE                                EQU $433
EVENT_BEAT_BIKER_HARRIS                                EQU $434
EVENT_BEAT_BIKER_ZEKE                                  EQU $435
EVENT_BEAT_BIKER_CHARLES                               EQU $436
EVENT_BEAT_BIKER_RILEY                                 EQU $437
EVENT_BEAT_BIKER_JOEL                                  EQU $438
EVENT_BEAT_BIKER_GLENN                                 EQU $439
EVENT_BEAT_PSYCHIC_NATHAN                              EQU $43a
EVENT_BEAT_PSYCHIC_FRANKLIN                            EQU $43b
EVENT_BEAT_PSYCHIC_HERMAN                              EQU $43c
EVENT_BEAT_PSYCHIC_FIDEL                               EQU $43d
EVENT_BEAT_PSYCHIC_GREG                                EQU $43e
EVENT_BEAT_PSYCHIC_NORMAN                              EQU $43f
EVENT_BEAT_PSYCHIC_MARK                                EQU $440
EVENT_BEAT_PSYCHIC_PHIL                                EQU $441
EVENT_BEAT_PSYCHIC_RICHARD                             EQU $442
EVENT_BEAT_PSYCHIC_GILBERT                             EQU $443
EVENT_BEAT_PSYCHIC_JARED                               EQU $444
EVENT_BEAT_PSYCHIC_RODNEY                              EQU $445
EVENT_BEAT_FIREBREATHER_OTIS                           EQU $446
EVENT_BEAT_FIREBREATHER_BURT                           EQU $449
EVENT_BEAT_FIREBREATHER_BILL                           EQU $44a
EVENT_BEAT_FIREBREATHER_WALT                           EQU $44b
EVENT_BEAT_FIREBREATHER_RAY                            EQU $44c
EVENT_BEAT_FIREBREATHER_LYLE                           EQU $44d
EVENT_BEAT_FISHER_JUSTIN                               EQU $44e
EVENT_BEAT_FISHER_RALPH_1                              EQU $44f
EVENT_BEAT_FISHER_ARNOLD                               EQU $450
EVENT_BEAT_FISHER_KYLE                                 EQU $451
EVENT_BEAT_FISHER_HENRY                                EQU $452
EVENT_BEAT_FISHER_MARVIN                               EQU $453
EVENT_BEAT_FISHER_TULLY_1                              EQU $454
EVENT_BEAT_FISHER_ANDRE                                EQU $455
EVENT_BEAT_FISHER_RAYMOND                              EQU $456
EVENT_BEAT_FISHER_WILTON_1                             EQU $457
EVENT_BEAT_FISHER_EDGAR                                EQU $458
EVENT_BEAT_FISHER_JONAH                                EQU $459
EVENT_BEAT_FISHER_MARTIN                               EQU $45a
EVENT_BEAT_FISHER_STEPHEN                              EQU $45b
EVENT_BEAT_FISHER_BARNEY                               EQU $45c
EVENT_BEAT_FISHER_SCOTT                                EQU $462
EVENT_BEAT_TWINS_AMY_AND_MAY                           EQU $464
EVENT_BEAT_TWINS_ANN_AND_ANNE                          EQU $465
EVENT_BEAT_TWINS_JO_AND_ZOE                            EQU $468
EVENT_BEAT_TWINS_MEG_AND_PEG                           EQU $46a
EVENT_BEAT_SCHOOLBOY_JACK_1                            EQU $46c
EVENT_BEAT_SCHOOLBOY_KIP                               EQU $46d
EVENT_BEAT_SCHOOLBOY_ALAN                              EQU $46e
EVENT_BEAT_SCHOOLBOY_JOHNNY                            EQU $46f
EVENT_BEAT_SCHOOLBOY_DANNY                             EQU $470
EVENT_BEAT_SCHOOLBOY_TOMMY                             EQU $471
EVENT_BEAT_SCHOOLBOY_DUDLEY                            EQU $472
EVENT_BEAT_SCHOOLBOY_JOE                               EQU $473
EVENT_BEAT_SCHOOLBOY_BILLY                             EQU $474
EVENT_BEAT_SCHOOLBOY_CHAD_1                            EQU $475
EVENT_BEAT_SCHOOLBOY_NATE                              EQU $476
EVENT_BEAT_SCHOOLBOY_RICKY                             EQU $477
EVENT_BEAT_PICNICKER_LIZ_1                             EQU $47e
EVENT_BEAT_PICNICKER_GINA_1                            EQU $47f
EVENT_BEAT_PICNICKER_BROOKE                            EQU $480
EVENT_BEAT_PICNICKER_KIM                               EQU $481
EVENT_BEAT_PICNICKER_HOPE                              EQU $483
EVENT_BEAT_PICNICKER_SHARON                            EQU $484
EVENT_BEAT_PICNICKER_DEBRA                             EQU $485
EVENT_BEAT_PICNICKER_ERIN_1                            EQU $487
EVENT_BEAT_PICNICKER_HEIDI                             EQU $48a
EVENT_BEAT_PICNICKER_EDNA                              EQU $48b
EVENT_BEAT_PICNICKER_TANYA                             EQU $490
EVENT_BEAT_PICNICKER_TIFFANY_3                         EQU $491
EVENT_BEAT_GUITARIST_CLYDE                             EQU $493
EVENT_BEAT_GUITARIST_VINCENT                           EQU $494
EVENT_BEAT_JUGGLER_IRWIN_1                             EQU $495
EVENT_BEAT_JUGGLER_FRITZ                               EQU $496
EVENT_BEAT_JUGGLER_HORTON                              EQU $497
EVENT_BEAT_GENTLEMAN_PRESTON                           EQU $49a
EVENT_BEAT_GENTLEMAN_EDWARD                            EQU $49b
EVENT_BEAT_GENTLEMAN_GREGORY                           EQU $49c
EVENT_BEAT_GENTLEMAN_ALFRED                            EQU $49e
EVENT_BEAT_SCIENTIST_ROSS                              EQU $49f
EVENT_BEAT_SCIENTIST_MITCH                             EQU $4a0
EVENT_BEAT_SCIENTIST_JED                               EQU $4a1
EVENT_BEAT_SCIENTIST_MARC                              EQU $4a2
EVENT_BEAT_SCIENTIST_RICH                              EQU $4a3
EVENT_BEAT_BLACKBELT_YOSHI                             EQU $4a5
EVENT_BEAT_BLACKBELT_LAO                               EQU $4a7
EVENT_BEAT_BLACKBELT_NOB                               EQU $4a8
EVENT_BEAT_BLACKBELT_LUNG                              EQU $4aa
EVENT_BEAT_BLACKBELT_KENJI_3                           EQU $4ab
EVENT_BEAT_BLACKBELT_WAI                               EQU $4ac
EVENT_BEAT_BEAUTY_VICTORIA                             EQU $4ad
EVENT_BEAT_BEAUTY_SAMANTHA                             EQU $4ae
EVENT_BEAT_BEAUTY_CASSIE                               EQU $4b2
EVENT_BEAT_BEAUTY_JULIA                                EQU $4ba
EVENT_BEAT_BEAUTY_VALERIE                              EQU $4bc
EVENT_BEAT_FALKNER                                     EQU $4bd
EVENT_BEAT_BUGSY                                       EQU $4be
EVENT_BEAT_WHITNEY                                     EQU $4bf
EVENT_BEAT_MORTY                                       EQU $4c0
EVENT_BEAT_JASMINE                                     EQU $4c1
EVENT_BEAT_CHUCK                                       EQU $4c2
EVENT_BEAT_PRYCE                                       EQU $4c3
EVENT_BEAT_CLAIR                                       EQU $4c4
EVENT_BEAT_BROCK                                       EQU $4c5
EVENT_BEAT_MISTY                                       EQU $4c6
EVENT_BEAT_LTSURGE                                     EQU $4c7
EVENT_BEAT_JANINE                                      EQU $4c9
EVENT_BEAT_SABRINA                                     EQU $4ca
EVENT_BEAT_BLUE                                        EQU $4cc
EVENT_BEAT_POKEFANM_WILLIAM                            EQU $4cd
EVENT_BEAT_POKEFANM_DEREK                              EQU $4ce
EVENT_BEAT_POKEFANM_ROBERT                             EQU $4cf
EVENT_BEAT_POKEFANM_JOSHUA                             EQU $4d0
EVENT_BEAT_POKEFANM_CARTER                             EQU $4d1
EVENT_BEAT_POKEFANM_TREVOR                             EQU $4d2
EVENT_BEAT_POKEFANM_BRANDON                            EQU $4d3
EVENT_BEAT_POKEFANM_JEREMY                             EQU $4d4
EVENT_BEAT_POKEFANM_COLIN                              EQU $4d5
EVENT_BEAT_POKEFANM_ALEX                               EQU $4d8
EVENT_BEAT_POKEFANF_BEVERLY                            EQU $4d9
EVENT_BEAT_POKEFANF_RUTH                               EQU $4da
EVENT_BEAT_POKEFANF_GEORGIA                            EQU $4dd
EVENT_BEAT_KIMONO_GIRL_NAOKO                           EQU $4df
EVENT_BEAT_KIMONO_GIRL_SAYO                            EQU $4e0
EVENT_BEAT_KIMONO_GIRL_ZUKI                            EQU $4e1
EVENT_BEAT_KIMONO_GIRL_KUNI                            EQU $4e2
EVENT_BEAT_KIMONO_GIRL_MIKI                            EQU $4e3
EVENT_BEAT_POKEMANIAC_LARRY                            EQU $4e4
EVENT_BEAT_POKEMANIAC_ANDREW                           EQU $4e5
EVENT_BEAT_POKEMANIAC_CALVIN                           EQU $4e6
EVENT_BEAT_POKEMANIAC_SHANE                            EQU $4e7
EVENT_BEAT_POKEMANIAC_BEN                              EQU $4e8
EVENT_BEAT_POKEMANIAC_BRENT                            EQU $4e9
EVENT_BEAT_POKEMANIAC_RON                              EQU $4ea
EVENT_BEAT_POKEMANIAC_ETHAN                            EQU $4eb
EVENT_BEAT_POKEMANIAC_ISSAC                            EQU $4ee
EVENT_BEAT_POKEMANIAC_DONALD                           EQU $4ef
EVENT_BEAT_POKEMANIAC_ZACH                             EQU $4f0
EVENT_BEAT_ROCKET_GRUNTM_1                             EQU $4f1
EVENT_BEAT_ROCKET_GRUNTM_2                             EQU $4f2
EVENT_BEAT_ROCKET_GRUNTM_3                             EQU $4f3
EVENT_BEAT_ROCKET_GRUNTM_4                             EQU $4f4
EVENT_BEAT_ROCKET_GRUNTM_5                             EQU $4f5
EVENT_BEAT_ROCKET_GRUNTM_6                             EQU $4f6
EVENT_BEAT_ROCKET_GRUNTM_7                             EQU $4f7
EVENT_BEAT_ROCKET_GRUNTM_8                             EQU $4f8
EVENT_BEAT_ROCKET_GRUNTM_9                             EQU $4f9
EVENT_BEAT_ROCKET_GRUNTM_10                            EQU $4fa
EVENT_BEAT_ROCKET_GRUNTM_11                            EQU $4fb
EVENT_BEAT_ROCKET_GRUNTM_12                            EQU $4fd
EVENT_BEAT_ROCKET_GRUNTM_13                            EQU $4fe
EVENT_BEAT_ROCKET_GRUNTM_14                            EQU $4ff
EVENT_BEAT_ROCKET_GRUNTM_15                            EQU $500
EVENT_BEAT_ROCKET_GRUNTM_16                            EQU $501
EVENT_BEAT_ROCKET_GRUNTM_17                            EQU $502
EVENT_BEAT_ROCKET_GRUNTM_18                            EQU $503
EVENT_BEAT_ROCKET_GRUNTM_19                            EQU $508
EVENT_BEAT_ROCKET_GRUNTM_20                            EQU $509
EVENT_BEAT_ROCKET_GRUNTM_21                            EQU $50c
EVENT_BEAT_ROCKET_GRUNTM_22                            EQU $50d
EVENT_BEAT_ROCKET_GRUNTF_1                             EQU $510
EVENT_BEAT_ROCKET_GRUNTF_2                             EQU $511
EVENT_BEAT_ROCKET_GRUNTF_3                             EQU $512
EVENT_BEAT_ROCKET_GRUNTF_4                             EQU $513
EVENT_BEAT_ROCKET_GRUNTF_5                             EQU $514
EVENT_BEAT_LASS_CARRIE                                 EQU $515
EVENT_BEAT_LASS_BRIDGET                                EQU $516
EVENT_BEAT_LASS_KRISE                                  EQU $518
EVENT_BEAT_LASS_CONNIE_1                               EQU $519
EVENT_BEAT_LASS_LAURA                                  EQU $51b
EVENT_BEAT_LASS_SHANNON                                EQU $51c
EVENT_BEAT_LASS_MICHELLE                               EQU $51d
EVENT_BEAT_LASS_DANA                                   EQU $51e
EVENT_BEAT_LASS_ELLEN                                  EQU $51f
EVENT_BEAT_HIKER_RUSSELL                               EQU $525
EVENT_BEAT_HIKER_PHILLIP                               EQU $526
EVENT_BEAT_HIKER_LEONARD                               EQU $527
EVENT_BEAT_HIKER_ANTHONY_2                             EQU $528
EVENT_BEAT_HIKER_BENJAMIN                              EQU $529
EVENT_BEAT_HIKER_ERIK                                  EQU $52a
EVENT_BEAT_HIKER_MICHAEL                               EQU $52b
EVENT_BEAT_HIKER_PARRY_3                               EQU $52c
EVENT_BEAT_HIKER_TIMOTHY                               EQU $52d
EVENT_BEAT_HIKER_BAILEY                                EQU $52e
EVENT_BEAT_HIKER_TIM                                   EQU $530
EVENT_BEAT_HIKER_NOLAND                                EQU $531
EVENT_BEAT_HIKER_SIDNEY                                EQU $532
EVENT_BEAT_HIKER_KENNY                                 EQU $533
EVENT_BEAT_HIKER_JIM                                   EQU $534
EVENT_BEAT_HIKER_DANIEL                                EQU $535
EVENT_BEAT_BUG_CATCHER_DON                             EQU $538
EVENT_BEAT_BUG_CATCHER_ROB                             EQU $539
EVENT_BEAT_BUG_CATCHER_ED                              EQU $53a
EVENT_BEAT_BUG_CATCHER_WADE_1                          EQU $53b
EVENT_BEAT_BUG_CATCHER_BENNY                           EQU $53c
EVENT_BEAT_BUG_CATCHER_AL                              EQU $53d
EVENT_BEAT_BUG_CATCHER_JOSH                            EQU $53e
EVENT_BEAT_BUG_CATCHER_ARNIE_1                         EQU $53f
EVENT_BEAT_BUG_CATCHER_KEN                             EQU $540
EVENT_BEAT_BUG_CATCHER_DOUG                            EQU $543
EVENT_BEAT_COOLTRAINERM_NICK                           EQU $548
EVENT_BEAT_COOLTRAINERM_AARON                          EQU $549
EVENT_BEAT_COOLTRAINERM_PAUL                           EQU $54a
EVENT_BEAT_COOLTRAINERM_CODY                           EQU $54b
EVENT_BEAT_COOLTRAINERM_MIKE                           EQU $54c
EVENT_BEAT_COOLTRAINERM_RYAN                           EQU $54f
EVENT_BEAT_COOLTRAINERM_JAKE                           EQU $550
EVENT_BEAT_COOLTRAINERM_GAVEN_3                        EQU $551
EVENT_BEAT_COOLTRAINERM_BLAKE                          EQU $552
EVENT_BEAT_COOLTRAINERM_BRIAN                          EQU $553
EVENT_BEAT_COOLTRAINERM_SEAN                           EQU $557
EVENT_BEAT_COOLTRAINERM_ALLEN                          EQU $55a
EVENT_BEAT_COOLTRAINERF_GWEN                           EQU $55b
EVENT_BEAT_COOLTRAINERF_LOIS                           EQU $55c
EVENT_BEAT_COOLTRAINERF_FRAN                           EQU $55d
EVENT_BEAT_COOLTRAINERF_LOLA                           EQU $55e
EVENT_BEAT_COOLTRAINERF_KATE                           EQU $55f
EVENT_BEAT_COOLTRAINERF_IRENE                          EQU $560
EVENT_BEAT_COOLTRAINERF_KELLY                          EQU $561
EVENT_BEAT_COOLTRAINERF_JOYCE                          EQU $562
EVENT_BEAT_COOLTRAINERF_BETH_1                         EQU $563
EVENT_BEAT_COOLTRAINERF_REENA_1                        EQU $564
EVENT_BEAT_COOLTRAINERF_MEGAN                          EQU $565
EVENT_BEAT_COOLTRAINERF_CAROL                          EQU $567
EVENT_BEAT_COOLTRAINERF_QUINN                          EQU $568
EVENT_BEAT_COOLTRAINERF_EMMA                           EQU $569
EVENT_BEAT_COOLTRAINERF_CYBIL                          EQU $56a
EVENT_BEAT_COOLTRAINERF_JENN                           EQU $56b
EVENT_BEAT_ROCKET_EXECUTIVEF                           EQU $56f
EVENT_BEAT_ROCKET_EXECUTIVEM                           EQU $572
EVENT_BEAT_SAILOR_EUGENE                               EQU $575
EVENT_BEAT_SAILOR_HUEY_1                               EQU $576
EVENT_BEAT_SAILOR_TERRELL                              EQU $577
EVENT_BEAT_SAILOR_KENT                                 EQU $578
EVENT_BEAT_SAILOR_ERNEST                               EQU $579
EVENT_BEAT_SAILOR_JEFF                                 EQU $57a
EVENT_BEAT_SAILOR_GARRETT                              EQU $57b
EVENT_BEAT_SAILOR_KENNETH                              EQU $57c
EVENT_BEAT_SAILOR_HARRY                                EQU $57e
EVENT_BEAT_SUPER_NERD_ERIC                             EQU $582
EVENT_BEAT_SUPER_NERD_SAM                              EQU $586
EVENT_BEAT_SUPER_NERD_TOM                              EQU $587
EVENT_BEAT_SUPER_NERD_PAT                              EQU $588
EVENT_BEAT_SUPER_NERD_SHAWN                            EQU $589
EVENT_BEAT_SUPER_NERD_TERU                             EQU $58a
EVENT_BEAT_MEDIUM_MARTHA                               EQU $58b
EVENT_BEAT_MEDIUM_GRACE                                EQU $58c
EVENT_BEAT_MEDIUM_REBECCA                              EQU $590
EVENT_BEAT_MEDIUM_DORIS                                EQU $591
EVENT_BEAT_SKIER_ROXANNE                               EQU $592
EVENT_BEAT_SKIER_CLARISSA                              EQU $593
EVENT_BEAT_SWIMMERM_HAROLD                             EQU $594
EVENT_BEAT_SWIMMERM_SIMON                              EQU $595
EVENT_BEAT_SWIMMERM_RANDALL                            EQU $596
EVENT_BEAT_SWIMMERM_CHARLIE                            EQU $597
EVENT_BEAT_SWIMMERM_GEORGE                             EQU $598
EVENT_BEAT_SWIMMERM_BERKE                              EQU $599
EVENT_BEAT_SWIMMERM_KIRK                               EQU $59a
EVENT_BEAT_SWIMMERM_MATHEW                             EQU $59b
EVENT_BEAT_SWIMMERM_JEROME                             EQU $5a1
EVENT_BEAT_SWIMMERM_TUCKER                             EQU $5a2
EVENT_BEAT_SWIMMERM_CAMERON                            EQU $5a4
EVENT_BEAT_SWIMMERM_SETH                               EQU $5a5
EVENT_BEAT_SWIMMERM_PARKER                             EQU $5a8
EVENT_BEAT_YOUNGSTER_JOEY_1                            EQU $5a9
EVENT_BEAT_YOUNGSTER_MIKEY                             EQU $5aa
EVENT_BEAT_YOUNGSTER_ALBERT                            EQU $5ab
EVENT_BEAT_YOUNGSTER_GORDON                            EQU $5ac
EVENT_BEAT_YOUNGSTER_SAMUEL                            EQU $5ad
EVENT_BEAT_YOUNGSTER_IAN                               EQU $5ae
EVENT_BEAT_YOUNGSTER_WARREN                            EQU $5b1
EVENT_BEAT_YOUNGSTER_JIMMY                             EQU $5b2
EVENT_BEAT_YOUNGSTER_OWEN                              EQU $5b3
EVENT_BEAT_YOUNGSTER_JASON                             EQU $5b4
EVENT_BEAT_TEACHER_COLETTE                             EQU $5b5
EVENT_BEAT_TEACHER_HILLARY                             EQU $5b6
EVENT_BEAT_TEACHER_SHIRLEY                             EQU $5b7
EVENT_BEAT_ELITE_4_KAREN                               EQU $5bb
EVENT_BEAT_CHAMPION_LANCE                              EQU $5bc
EVENT_BEAT_COOLTRAINERM_DARIN                          EQU $5bd
EVENT_BEAT_COOLTRAINERF_CARA                           EQU $5be
EVENT_BEAT_TWINS_LEA_AND_PIA                           EQU $5bf
EVENT_BEAT_BUG_CATCHER_WAYNE                           EQU $5c0
EVENT_BEAT_BEAUTY_OLIVIA                               EQU $5c1
EVENT_BEAT_POKEMANIAC_MILER                            EQU $5c4
EVENT_BEAT_SUPER_NERD_HUGH                             EQU $5c5
EVENT_BEAT_SUPER_NERD_MARKUS                           EQU $5c6
EVENT_BEAT_POKEFANM_REX                                EQU $5c7
EVENT_BEAT_POKEFANM_ALLAN                              EQU $5c8
EVENT_BEAT_SAGE_GAKU                                   EQU $5c9
EVENT_BEAT_SAGE_MASA                                   EQU $5ca
EVENT_BEAT_SAGE_KOJI                                   EQU $5cb
EVENT_GUIDE_GENT_VISIBLE_IN_CHERRYGROVE                EQU $6ff
EVENT_ELMS_AIDE_IN_VIOLET_POKEMON_CENTER               EQU $700
EVENT_ELMS_AIDE_IN_LAB                                 EQU $701
EVENT_BOULDER_IN_ICE_PATH_1                            EQU $70d
EVENT_BOULDER_IN_ICE_PATH_2                            EQU $70e
EVENT_BOULDER_IN_ICE_PATH_3                            EQU $70f
EVENT_BOULDER_IN_ICE_PATH_4                            EQU $710
EVENT_FOUGHT_SNORLAX                                   EQU $750
EVENT_PICKED_UP_FOCUS_BAND                             EQU $77d
EVENT_PICKED_UP_GOLD_BERRY_FROM_HO_OH_ITEM_ROOM        EQU $794
EVENT_PICKED_UP_MYSTERYBERRY_FROM_HO_OH_ITEM_ROOM      EQU $795
EVENT_PICKED_UP_REVIVAL_HERB_FROM_HO_OH_ITEM_ROOM      EQU $796
EVENT_PICKED_UP_CHARCOAL_FROM_HO_OH_ITEM_ROOM          EQU $797
EVENT_PICKED_UP_BERRY_FROM_KABUTO_ITEM_ROOM            EQU $798
EVENT_PICKED_UP_PSNCUREBERRY_FROM_KABUTO_ITEM_ROOM     EQU $799
EVENT_PICKED_UP_HEAL_POWDER_FROM_KABUTO_ITEM_ROOM      EQU $79a
EVENT_PICKED_UP_ENERGYPOWDER_FROM_KABUTO_ITEM_ROOM     EQU $79b
EVENT_PICKED_UP_MYSTERYBERRY_FROM_OMANYTE_ITEM_ROOM    EQU $79c
EVENT_PICKED_UP_MYSTIC_WATER_FROM_OMANYTE_ITEM_ROOM    EQU $79d
EVENT_PICKED_UP_STARDUST_FROM_OMANYTE_ITEM_ROOM        EQU $79e
EVENT_PICKED_UP_STAR_PIECE_FROM_OMANYTE_ITEM_ROOM      EQU $79f
EVENT_PICKED_UP_GOLD_BERRY_FROM_AERODACTYL_ITEM_ROOM   EQU $7a0
EVENT_PICKED_UP_MOON_STONE_FROM_AERODACTYL_ITEM_ROOM   EQU $7a1
EVENT_PICKED_UP_HEAL_POWDER_FROM_AERODACTYL_ITEM_ROOM  EQU $7a2
EVENT_PICKED_UP_ENERGY_ROOT_FROM_AERODACTYL_ITEM_ROOM  EQU $7a3
EVENT_SAW_SUICUNE_AT_CIANWOOD_CITY                     EQU $7ae
EVENT_SAW_SUICUNE_ON_ROUTE_42                          EQU $7af
EVENT_SAW_SUICUNE_ON_ROUTE_36                          EQU $7b0
EVENT_SET_WHEN_FOUGHT_HO_OH                            EQU $7b7
