; IconPointers indexes (see data/icon_pointers.asm)
	const_def
	const ICON_NULL
	
	const ICON_BULBASAUR
	const ICON_IVYSAUR
	const ICON_VENUSAUR
	const ICON_CHARMANDER
	const ICON_CHARMELEON
	const ICON_CHARIZARD
	const ICON_SQUIRTLE
	const ICON_WARTORTLE
	const ICON_BLASTOISE
	const ICON_CATERPIE
	const ICON_METAPOD
	const ICON_BUTTERFREE
	const ICON_WEEDLE
	const ICON_KAKUNA
	const ICON_BEEDRILL
	const ICON_PIDGEY
	const ICON_PIDGEOTTO
	const ICON_PIDGEOT
	const ICON_RATTATA
	const ICON_RATICATE
	const ICON_SPEAROW
	const ICON_FEAROW
	const ICON_EKANS
	const ICON_ARBOK
	const ICON_PIKACHU
	const ICON_RAICHU
	const ICON_SANDSHREW
	const ICON_SANDSLASH
	const ICON_NIDORANF
	const ICON_NIDORINA
	const ICON_NIDOQUEEN
	const ICON_NIDORANM
	const ICON_NIDORINO
	const ICON_NIDOKING
	const ICON_CLEFAIRY
	const ICON_CLEFABLE
	const ICON_VULPIX
	const ICON_NINETALES
	const ICON_JIGGLYPUFF
	const ICON_WIGGLYTUFF
	const ICON_ZUBAT
	const ICON_GOLBAT
	const ICON_ODDISH
	const ICON_GLOOM
	const ICON_VILEPLUME
	const ICON_PARAS
	const ICON_PARASECT
	const ICON_VENONAT
	const ICON_VENOMOTH
	const ICON_DIGLETT
	const ICON_DUGTRIO
	const ICON_MEOWTH
	const ICON_PERSIAN
	const ICON_PSYDUCK
	const ICON_GOLDUCK
	const ICON_MANKEY
	const ICON_PRIMEAPE
	const ICON_GROWLITHE
	const ICON_ARCANINE
	const ICON_POLIWAG
	const ICON_POLIWHIRL
	const ICON_POLIWRATH
	const ICON_ABRA
	const ICON_KADABRA
	const ICON_ALAKAZAM
	const ICON_MACHOP
	const ICON_MACHOKE
	const ICON_MACHAMP
	const ICON_BELLSPROUT
	const ICON_WEEPINBELL
	const ICON_VICTREEBEL
	const ICON_TENTACOOL
	const ICON_TENTACRUEL
	const ICON_GEODUDE
	const ICON_GRAVELER
	const ICON_GOLEM
	const ICON_PONYTA
	const ICON_RAPIDASH
	const ICON_SLOWPOKE
	const ICON_SLOWBRO
	const ICON_MAGNEMITE
	const ICON_MAGNETON
	const ICON_FARFETCHD
	const ICON_DODUO
	const ICON_DODRIO
	const ICON_SEEL
	const ICON_DEWGONG
	const ICON_GRIMER
	const ICON_MUK
	const ICON_SHELLDER
	const ICON_CLOYSTER
	const ICON_GASTLY
	const ICON_HAUNTER
	const ICON_GENGAR
	const ICON_ONIX
	const ICON_DROWZEE
	const ICON_HYPNO
	const ICON_KRABBY
	const ICON_KINGLER
	const ICON_VOLTORB
	const ICON_ELECTRODE
	const ICON_EXEGGCUTE
	const ICON_EXEGGUTOR
	const ICON_CUBONE
	const ICON_MAROWAK
	const ICON_HITMONLEE
	const ICON_HITMONCHAN
	const ICON_LICKITUNG
	const ICON_KOFFING
	const ICON_WEEZING
	const ICON_RHYHORN
	const ICON_RHYDON
	const ICON_CHANSEY
	const ICON_TANGELA
	const ICON_KANGASKHAN
	const ICON_HORSEA
	const ICON_SEADRA
	const ICON_GOLDEEN
	const ICON_SEAKING
	const ICON_STARYU
	const ICON_STARMIE
	const ICON_MRMIME
	const ICON_SCYTHER
	const ICON_JYNX
	const ICON_ELECTABUZZ
	const ICON_MAGMAR
	const ICON_PINSIR
	const ICON_TAUROS
	const ICON_MAGIKARP
	const ICON_GYARADOS
	const ICON_LAPRAS
	const ICON_DITTO
	const ICON_EEVEE
	const ICON_VAPOREON
	const ICON_JOLTEON
	const ICON_FLAREON
	const ICON_PORYGON
	const ICON_OMANYTE
	const ICON_OMASTAR
	const ICON_KABUTO
	const ICON_KABUTOPS
	const ICON_AERODACTYL
	const ICON_SNORLAX
	const ICON_ARTICUNO
	const ICON_ZAPDOS
	const ICON_MOLTRES
	const ICON_DRATINI
	const ICON_DRAGONAIR
	const ICON_DRAGONITE
	const ICON_MEWTWO
	const ICON_MEW
	const ICON_CHIKORITA
	const ICON_BAYLEEF
	const ICON_MEGANIUM
	const ICON_CYNDAQUIL
	const ICON_QUILAVA
	const ICON_TYPHLOSION
	const ICON_TOTODILE
	const ICON_CROCONAW
	const ICON_FERALIGATR
	const ICON_SENTRET
	const ICON_FURRET
	const ICON_HOOTHOOT
	const ICON_NOCTOWL
	const ICON_LEDYBA
	const ICON_LEDIAN         ; LEDIAN
	const ICON_SPINARAK         ; SPINARAK
	const ICON_ARIADOS         ; ARIADOS
	const ICON_CROBAT         ; CROBAT
	const ICON_CHINCHOU        ; CHINCHOU
	const ICON_LANTURN        ; LANTURN
	const ICON_PICHU     ; PICHU
	const ICON_CLEFFA    ; CLEFFA
	const ICON_IGGLYBUFF  ; IGGLYBUFF
	const ICON_TOGEPI    ; TOGEPI
	const ICON_TOGETIC        ; TOGETIC
	const ICON_NATU        ; NATU
	const ICON_XATU        ; XATU
	const ICON_MAREEP         ; MAREEP
	const ICON_FLAAFFY     ; FLAAFFY
	const ICON_AMPHAROS     ; AMPHAROS
	const ICON_BELLOSSOM      ; BELLOSSOM
	const ICON_MARILL  ; MARILL
	const ICON_AZUMARILL  ; AZUMARILL
	const ICON_SUDOWOODO   ; SUDOWOODO
	const ICON_POLITOED     ; POLITOED
	const ICON_HOPPIP      ; HOPPIP
	const ICON_SKIPLOOM      ; SKIPLOOM
	const ICON_JUMPLUFF      ; JUMPLUFF
	const ICON_AIPOM     ; AIPOM
	const ICON_SUNKERN      ; SUNKERN
	const ICON_SUNFLORA      ; SUNFLORA
	const ICON_YANMA         ; YANMA
	const ICON_WOOPER     ; WOOPER
	const ICON_QUAGSIRE     ; QUAGSIRE
	const ICON_ESPEON         ; ESPEON
	const ICON_UMBREON         ; UMBREON
	const ICON_MURKROW        ; MURKROW
	const ICON_SLOWKING    ; SLOWKING
	const ICON_MISDREAVUS       ; MISDREAVUS
	const ICON_UNOWN       ; UNOWN
	const ICON_WOBBUFFET       ; WOBBUFFET
	const ICON_GIRAFARIG      ; GIRAFARIG
	const ICON_PINECO         ; PINECO
	const ICON_FORRETRESS         ; FORRETRESS
	const ICON_DUNSPARCE     ; DUNSPARCE
	const ICON_GLIGAR         ; GLIGAR
	const ICON_STEELIX     ; STEELIX
	const ICON_SNUBBULL     ; SNUBBULL
	const ICON_GRANBULL     ; GRANBULL
	const ICON_QWILFISH        ; QWILFISH
	const ICON_SCIZOR         ; SCIZOR
	const ICON_SHUCKLE         ; SHUCKLE
	const ICON_HERACROSS         ; HERACROSS
	const ICON_SNEASEL         ; SNEASEL
	const ICON_TEDDIURSA     ; TEDDIURSA
	const ICON_URSARING     ; URSARING
	const ICON_SLUGMA        ; SLUGMA
	const ICON_MAGCARGO        ; MAGCARGO
	const ICON_SWINUB      ; SWINUB
	const ICON_PILOSWINE      ; PILOSWINE
	const ICON_CORSOLA       ; CORSOLA
	const ICON_REMORAID        ; REMORAID
	const ICON_OCTILLERY        ; OCTILLERY
	const ICON_DELIBIRD     ; DELIBIRD
	const ICON_MANTINE        ; MANTINE
	const ICON_SKARMORY        ; SKARMORY
	const ICON_HOUNDOUR         ; HOUNDOUR
	const ICON_HOUNDOOM         ; HOUNDOOM
	const ICON_KINGDRA      ; KINGDRA
	const ICON_PHANPY      ; PHANPY
	const ICON_DONPHAN      ; DONPHAN
	const ICON_PORYGON2     ; PORYGON2
	const ICON_STANTLER      ; STANTLER
	const ICON_SMEARGLE     ; SMEARGLE
	const ICON_TYROGUE     ; TYROGUE
	const ICON_HITMONTOP     ; HITMONTOP
	const ICON_SMOOCHUM  ; SMOOCHUM
	const ICON_ELEKID  ; ELEKID
	const ICON_MAGBY  ; MAGBY
	const ICON_MILTANK      ; MILTANK
	const ICON_BLISSEY    ; BLISSEY
	const ICON_RAIKOU         ; RAIKOU
	const ICON_ENTEI         ; ENTEI
	const ICON_SUICUNE         ; SUICUNE
	const ICON_LARVITAR     ; LARVITAR
	const ICON_PUPITAR     ; PUPITAR
	const ICON_TYRANITAR     ; TYRANITAR
	const ICON_LUGIA       ; LUGIA
	const ICON_HO_OH       ; HO_OH
	const ICON_CELEBI  ; CELEBI

	const ICON_EGG

; LoadMenuMonIcon.Jumptable indexes (see engine/gfx/mon_icons.asm)
	const_def
	const MONICON_PARTYMENU
	const MONICON_NAMINGSCREEN
	const MONICON_MOVES
	const MONICON_TRADE
	const MONICON_MOBILE1
	const MONICON_MOBILE2
	const MONICON_UNUSED
