
	const_def

	const SPECIAL_MAP
	const NEW_BARK_TOWN
	const ROUTE_29
	const CHERRYGROVE_CITY
	const ROUTE_30
	const ROUTE_31
	const VIOLET_CITY
	const SPROUT_TOWER
	const ROUTE_32
	const RUINS_OF_ALPH
	const UNION_CAVE
	const ROUTE_33
	const AZALEA_TOWN
	const SLOWPOKE_WELL
	const ILEX_FOREST
	const ROUTE_34
	const GOLDENROD_CITY
	const RADIO_TOWER
	const ROUTE_35
	const NATIONAL_PARK
	const ROUTE_36
	const ROUTE_37
	const ECRUTEAK_CITY
	const TIN_TOWER
	const BURNED_TOWER
	const ROUTE_38
	const ROUTE_39
	const OLIVINE_CITY
	const LIGHTHOUSE
	const BATTLE_TOWER
	const ROUTE_40
	const WHIRL_ISLANDS
	const ROUTE_41
	const CIANWOOD_CITY
	const ROUTE_42
	const MT_MORTAR
	const MAHOGANY_TOWN
	const ROUTE_43
	const LAKE_OF_RAGE
	const ROUTE_44
	const ICE_PATH
	const BLACKTHORN_CITY
	const DRAGONS_DEN
	const ROUTE_45
	const DARK_CAVE
	const ROUTE_46
	const SILVER_CAVE

KANTO_LANDMARK EQU const_value

	const PALLET_TOWN
	const ROUTE_1
	const VIRIDIAN_CITY
	const ROUTE_2
	const PEWTER_CITY
	const ROUTE_3
	const MT_MOON
	const ROUTE_4
	const CERULEAN_CITY
	const ROUTE_24
	const ROUTE_25
	const ROUTE_5
	const UNDERGROUND
	const ROUTE_6
	const VERMILION_CITY
	const DIGLETTS_CAVE
	const ROUTE_7
	const ROUTE_8
	const ROUTE_9
	const ROCK_TUNNEL
	const ROUTE_10
	const POWER_PLANT
	const LAVENDER_TOWN
	const LAV_RADIO_TOWER
	const CELADON_CITY
	const SAFFRON_CITY
	const ROUTE_11
	const ROUTE_12
	const ROUTE_13
	const ROUTE_14
	const ROUTE_15
	const ROUTE_16
	const ROUTE_17
	const ROUTE_18
	const FUCHSIA_CITY
	const ROUTE_19
	const ROUTE_20
	const SEAFOAM_ISLANDS
	const CINNABAR_ISLAND
	const ROUTE_21
	const ROUTE_22
	const VICTORY_ROAD
	const ROUTE_23
	const INDIGO_PLATEAU
	const ROUTE_26
	const ROUTE_27
	const TOHJO_FALLS
	const ROUTE_28
	const FAST_SHIP
