GROUP_N_A  EQU -1
MAP_N_A    EQU -1

GROUP_NONE EQU 0
MAP_NONE   EQU 0

; map group ids
	const_def
	newgroup
	mapgroup OLIVINE_POKECENTER_1F, 4, 5
	mapgroup OLIVINE_GYM, 8, 5
	mapgroup OLIVINE_VOLTORB_HOUSE, 4, 4
	mapgroup OLIVINE_HOUSE_BETA, 4, 4
	mapgroup OLIVINE_PUNISHMENT_SPEECH_HOUSE, 4, 4
	mapgroup OLIVINE_GOOD_ROD_HOUSE, 4, 4
	mapgroup OLIVINE_CAFE, 4, 4
	mapgroup OLIVINE_MART, 4, 6
	mapgroup ROUTE_38_ECRUTEAK_GATE, 4, 5
	mapgroup ROUTE_39_BARN, 4, 4
	mapgroup ROUTE_39_FARMHOUSE, 4, 4
	mapgroup ROUTE_38, 9, 20
	mapgroup ROUTE_39, 18, 10
	mapgroup OLIVINE_CITY, 18, 20

	newgroup
	mapgroup MAHOGANY_RED_GYARADOS_SPEECH_HOUSE, 4, 4
	mapgroup MAHOGANY_GYM, 9, 5
	mapgroup MAHOGANY_POKECENTER_1F, 4, 5
	mapgroup ROUTE_42_ECRUTEAK_GATE, 4, 5
	mapgroup ROUTE_42, 9, 30
	mapgroup ROUTE_44, 9, 30
	mapgroup MAHOGANY_TOWN, 9, 10

	newgroup
	mapgroup SPROUT_TOWER_1F, 8, 10
	mapgroup SPROUT_TOWER_2F, 8, 10
	mapgroup SPROUT_TOWER_3F, 8, 10
	mapgroup TIN_TOWER_1F, 9, 10
	mapgroup TIN_TOWER_2F, 9, 10
	mapgroup TIN_TOWER_3F, 9, 10
	mapgroup TIN_TOWER_4F, 9, 10
	mapgroup TIN_TOWER_5F, 9, 10
	mapgroup TIN_TOWER_6F, 9, 10
	mapgroup TIN_TOWER_7F, 9, 10
	mapgroup TIN_TOWER_8F, 9, 10
	mapgroup TIN_TOWER_9F, 9, 10
	mapgroup BURNED_TOWER_1F, 9, 10
	mapgroup BURNED_TOWER_B1F, 9, 10
	mapgroup NATIONAL_PARK, 27, 20
	mapgroup NATIONAL_PARK_BUG_CONTEST, 27, 20
	mapgroup RADIO_TOWER_1F, 4, 9
	mapgroup RADIO_TOWER_2F, 4, 9
	mapgroup RADIO_TOWER_3F, 4, 9
	mapgroup RADIO_TOWER_4F, 4, 9
	mapgroup RADIO_TOWER_5F, 4, 9
	mapgroup RUINS_OF_ALPH_OUTSIDE, 18, 10
	mapgroup RUINS_OF_ALPH_HO_OH_CHAMBER, 5, 4
	mapgroup RUINS_OF_ALPH_KABUTO_CHAMBER, 5, 4
	mapgroup RUINS_OF_ALPH_OMANYTE_CHAMBER, 5, 4
	mapgroup RUINS_OF_ALPH_AERODACTYL_CHAMBER, 5, 4
	mapgroup RUINS_OF_ALPH_INNER_CHAMBER, 14, 10
	mapgroup RUINS_OF_ALPH_RESEARCH_CENTER, 4, 4
	mapgroup RUINS_OF_ALPH_HO_OH_ITEM_ROOM, 5, 4
	mapgroup RUINS_OF_ALPH_KABUTO_ITEM_ROOM, 5, 4
	mapgroup RUINS_OF_ALPH_OMANYTE_ITEM_ROOM, 5, 4
	mapgroup RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM, 5, 4
	mapgroup RUINS_OF_ALPH_HO_OH_WORD_ROOM, 12, 10
	mapgroup RUINS_OF_ALPH_KABUTO_WORD_ROOM, 7, 10
	mapgroup RUINS_OF_ALPH_OMANYTE_WORD_ROOM, 8, 10
	mapgroup RUINS_OF_ALPH_AERODACTYL_WORD_ROOM, 7, 10
	mapgroup UNION_CAVE_1F, 18, 10
	mapgroup UNION_CAVE_B1F, 18, 10
	mapgroup UNION_CAVE_B2F, 18, 10
	mapgroup SLOWPOKE_WELL_B1F, 9, 10
	mapgroup SLOWPOKE_WELL_B2F, 9, 10
	mapgroup OLIVINE_LIGHTHOUSE_1F, 9, 10
	mapgroup OLIVINE_LIGHTHOUSE_2F, 9, 10
	mapgroup OLIVINE_LIGHTHOUSE_3F, 9, 10
	mapgroup OLIVINE_LIGHTHOUSE_4F, 9, 10
	mapgroup OLIVINE_LIGHTHOUSE_5F, 9, 10
	mapgroup OLIVINE_LIGHTHOUSE_6F, 9, 10
	mapgroup MAHOGANY_MART_1F, 4, 4
	mapgroup TEAM_ROCKET_BASE_B1F, 9, 15
	mapgroup TEAM_ROCKET_BASE_B2F, 9, 15
	mapgroup TEAM_ROCKET_BASE_B3F, 9, 15
	mapgroup ILEX_FOREST, 27, 15
	mapgroup WAREHOUSE_ENTRANCE, 18, 15
	mapgroup UNDERGROUND_PATH_SWITCH_ROOM_ENTRANCES, 18, 15
	mapgroup GOLDENROD_DEPT_STORE_B1F, 9, 10
	mapgroup UNDERGROUND_WAREHOUSE, 9, 10
	mapgroup MOUNT_MORTAR_1F_OUTSIDE, 18, 20
	mapgroup MOUNT_MORTAR_1F_INSIDE, 27, 20
	mapgroup MOUNT_MORTAR_2F_INSIDE, 18, 20
	mapgroup MOUNT_MORTAR_B1F, 18, 20
	mapgroup ICE_PATH_1F, 18, 20
	mapgroup ICE_PATH_B1F, 18, 10
	mapgroup ICE_PATH_B2F_MAHOGANY_SIDE, 9, 10
	mapgroup ICE_PATH_B2F_BLACKTHORN_SIDE, 9, 5
	mapgroup ICE_PATH_B3F, 9, 10
	mapgroup WHIRL_ISLAND_NW, 9, 5
	mapgroup WHIRL_ISLAND_NE, 9, 10
	mapgroup WHIRL_ISLAND_SW, 9, 10
	mapgroup WHIRL_ISLAND_CAVE, 9, 5
	mapgroup WHIRL_ISLAND_SE, 9, 5
	mapgroup WHIRL_ISLAND_B1F, 18, 20
	mapgroup WHIRL_ISLAND_B2F, 18, 10
	mapgroup WHIRL_ISLAND_LUGIA_CHAMBER, 9, 10
	mapgroup SILVER_CAVE_ROOM_1, 18, 10
	mapgroup SILVER_CAVE_ROOM_2, 18, 15
	mapgroup SILVER_CAVE_ROOM_3, 18, 10
	mapgroup SILVER_CAVE_ITEM_ROOMS, 9, 10
	mapgroup DARK_CAVE_VIOLET_ENTRANCE, 18, 20
	mapgroup DARK_CAVE_BLACKTHORN_ENTRANCE, 18, 15
	mapgroup DRAGONS_DEN_1F, 9, 5
	mapgroup DRAGONS_DEN_B1F, 18, 20
	mapgroup DRAGON_SHRINE, 5, 5
	mapgroup TOHJO_FALLS, 9, 15
	mapgroup DIGLETTS_CAVE, 18, 10
	mapgroup MOUNT_MOON, 9, 15
	mapgroup UNDERGROUND, 14, 3
	mapgroup ROCK_TUNNEL_1F, 18, 15
	mapgroup ROCK_TUNNEL_B1F, 18, 15
	mapgroup SAFARI_ZONE_FUCHSIA_GATE_BETA, 4, 5
	mapgroup SAFARI_ZONE_BETA, 18, 10
	mapgroup VICTORY_ROAD, 36, 10

	newgroup
	mapgroup ECRUTEAK_HOUSE, 9, 10
	mapgroup WISE_TRIOS_ROOM, 4, 4
	mapgroup ECRUTEAK_POKECENTER_1F, 4, 5
	mapgroup ECRUTEAK_LUGIA_SPEECH_HOUSE, 4, 4
	mapgroup DANCE_THEATRE, 7, 6
	mapgroup ECRUTEAK_MART, 4, 6
	mapgroup ECRUTEAK_GYM, 9, 5
	mapgroup ECRUTEAK_ITEMFINDER_HOUSE, 4, 4
	mapgroup ECRUTEAK_CITY, 18, 20

	newgroup
	mapgroup BLACKTHORN_GYM_1F, 9, 5
	mapgroup BLACKTHORN_GYM_2F, 9, 5
	mapgroup BLACKTHORN_DRAGON_SPEECH_HOUSE, 4, 4
	mapgroup BLACKTHORN_DODRIO_TRADE_HOUSE, 4, 4
	mapgroup BLACKTHORN_MART, 4, 6
	mapgroup BLACKTHORN_POKECENTER_1F, 4, 5
	mapgroup MOVE_DELETERS_HOUSE, 4, 4
	mapgroup ROUTE_45, 45, 10
	mapgroup ROUTE_46, 18, 10
	mapgroup BLACKTHORN_CITY, 18, 20

	newgroup
	mapgroup CINNABAR_POKECENTER_1F, 4, 5
	mapgroup CINNABAR_POKECENTER_2F_BETA, 4, 8
	mapgroup ROUTE_19___FUCHSIA_GATE, 4, 5
	mapgroup SEAFOAM_GYM, 4, 5
	mapgroup ROUTE_19, 18, 10
	mapgroup ROUTE_20, 9, 30
	mapgroup ROUTE_21, 18, 10
	mapgroup CINNABAR_ISLAND, 9, 10

	newgroup
	mapgroup CERULEAN_GYM_BADGE_SPEECH_HOUSE, 4, 4
	mapgroup CERULEAN_POLICE_STATION, 4, 4
	mapgroup CERULEAN_TRADE_SPEECH_HOUSE, 4, 4
	mapgroup CERULEAN_POKECENTER_1F, 4, 5
	mapgroup CERULEAN_POKECENTER_2F_BETA, 4, 8
	mapgroup CERULEAN_GYM, 8, 5
	mapgroup CERULEAN_MART, 4, 6
	mapgroup ROUTE_10_POKECENTER_1F, 4, 5
	mapgroup ROUTE_10_POKECENTER_2F_BETA, 4, 8
	mapgroup POWER_PLANT, 9, 10
	mapgroup BILLS_HOUSE, 4, 4
	mapgroup ROUTE_4, 9, 20
	mapgroup ROUTE_9, 9, 30
	mapgroup ROUTE_10_NORTH, 9, 10
	mapgroup ROUTE_24, 9, 10
	mapgroup ROUTE_25, 9, 30
	mapgroup CERULEAN_CITY, 18, 20

	newgroup
	mapgroup AZALEA_POKECENTER_1F, 4, 5
	mapgroup CHARCOAL_KILN, 4, 4
	mapgroup AZALEA_MART, 4, 6
	mapgroup KURTS_HOUSE, 4, 8
	mapgroup AZALEA_GYM, 8, 5
	mapgroup ROUTE_33, 9, 10
	mapgroup AZALEA_TOWN, 9, 20

	newgroup
	mapgroup LAKE_OF_RAGE_HIDDEN_POWER_HOUSE, 4, 4
	mapgroup LAKE_OF_RAGE_MAGIKARP_HOUSE, 4, 4
	mapgroup ROUTE_43_MAHOGANY_GATE, 4, 5
	mapgroup ROUTE_43_GATE, 4, 5
	mapgroup ROUTE_43, 27, 10
	mapgroup LAKE_OF_RAGE, 18, 20

	newgroup
	mapgroup ROUTE_32, 45, 10
	mapgroup ROUTE_35, 18, 10
	mapgroup ROUTE_36, 9, 30
	mapgroup ROUTE_37, 9, 10
	mapgroup VIOLET_CITY, 18, 20
	mapgroup VIOLET_MART, 4, 6
	mapgroup VIOLET_GYM, 8, 5
	mapgroup EARLS_POKEMON_ACADEMY, 8, 4
	mapgroup VIOLET_NICKNAME_SPEECH_HOUSE, 4, 4
	mapgroup VIOLET_POKECENTER_1F, 4, 5
	mapgroup VIOLET_ONIX_TRADE_HOUSE, 4, 4
	mapgroup ROUTE_32_RUINS_OF_ALPH_GATE, 4, 5
	mapgroup ROUTE_32_POKECENTER_1F, 4, 5
	mapgroup ROUTE_35_GOLDENROD_GATE, 4, 5
	mapgroup ROUTE_35_NATIONAL_PARK_GATE, 4, 4
	mapgroup ROUTE_36_RUINS_OF_ALPH_GATE, 4, 5
	mapgroup ROUTE_36_NATIONAL_PARK_GATE, 4, 5

	newgroup
	mapgroup ROUTE_34, 27, 10
	mapgroup GOLDENROD_CITY, 18, 20
	mapgroup GOLDENROD_GYM, 9, 10
	mapgroup GOLDENROD_BIKE_SHOP, 4, 4
	mapgroup GOLDENROD_HAPPINESS_RATER, 4, 4
	mapgroup GOLDENROD_BILLS_HOUSE, 4, 4
	mapgroup GOLDENROD_MAGNET_TRAIN_STATION, 9, 10
	mapgroup GOLDENROD_FLOWER_SHOP, 4, 4
	mapgroup GOLDENROD_PP_SPEECH_HOUSE, 4, 4
	mapgroup GOLDENROD_NAME_RATERS_HOUSE, 4, 4
	mapgroup GOLDENROD_DEPT_STORE_1F, 4, 8
	mapgroup GOLDENROD_DEPT_STORE_2F, 4, 8
	mapgroup GOLDENROD_DEPT_STORE_3F, 4, 8
	mapgroup GOLDENROD_DEPT_STORE_4F, 4, 8
	mapgroup GOLDENROD_DEPT_STORE_5F, 4, 8
	mapgroup GOLDENROD_DEPT_STORE_6F, 4, 8
	mapgroup GOLDENROD_DEPT_STORE_ELEVATOR, 2, 2
	mapgroup GOLDENROD_DEPT_STORE_ROOF, 4, 8
	mapgroup GOLDENROD_GAME_CORNER, 7, 10
	mapgroup GOLDENROD_POKECENTER_1F, 4, 5
	mapgroup GOLDENROD_POKECOM_CENTER_2F_MOBILE, 16, 16
	mapgroup ILEX_FOREST_AZALEA_GATE, 4, 5
	mapgroup ROUTE_34_ILEX_FOREST_GATE, 4, 5
	mapgroup DAYCARE, 4, 5

	newgroup
	mapgroup ROUTE_6, 9, 10
	mapgroup ROUTE_11, 9, 20
	mapgroup VERMILION_CITY, 18, 20
	mapgroup VERMILION_HOUSE_FISHING_SPEECH_HOUSE, 4, 4
	mapgroup VERMILION_POKECENTER_1F, 4, 5
	mapgroup VERMILION_POKECENTER_2F_BETA, 4, 8
	mapgroup POKEMON_FAN_CLUB, 4, 5
	mapgroup VERMILION_MAGNET_TRAIN_SPEECH_HOUSE, 4, 4
	mapgroup VERMILION_MART, 4, 6
	mapgroup VERMILION_HOUSE_DIGLETTS_CAVE_SPEECH_HOUSE, 4, 4
	mapgroup VERMILION_GYM, 9, 5
	mapgroup ROUTE_6_SAFFRON_GATE, 4, 5
	mapgroup ROUTE_6_UNDERGROUND_ENTRANCE, 4, 4

	newgroup
	mapgroup ROUTE_1, 18, 10
	mapgroup PALLET_TOWN, 9, 10
	mapgroup REDS_HOUSE_1F, 4, 4
	mapgroup REDS_HOUSE_2F, 4, 4
	mapgroup BLUES_HOUSE, 4, 4
	mapgroup OAKS_LAB, 6, 5

	newgroup
	mapgroup ROUTE_3, 9, 30
	mapgroup PEWTER_CITY, 18, 20
	mapgroup PEWTER_NIDORAN_SPEECH_HOUSE, 4, 4
	mapgroup PEWTER_GYM, 7, 5
	mapgroup PEWTER_MART, 4, 6
	mapgroup PEWTER_POKECENTER_1F, 4, 5
	mapgroup PEWTER_POKECENTER_2F_BETA, 4, 8
	mapgroup PEWTER_SNOOZE_SPEECH_HOUSE, 4, 4

	newgroup
	mapgroup OLIVINE_PORT, 18, 10
	mapgroup VERMILION_PORT, 18, 10
	mapgroup FAST_SHIP_1F, 9, 16
	mapgroup FAST_SHIP_CABINS_NNW_NNE_NE, 16, 4
	mapgroup FAST_SHIP_CABINS_SW_SSW_NW, 16, 4
	mapgroup FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN, 17, 5
	mapgroup FAST_SHIP_B1F, 8, 16
	mapgroup OLIVINE_PORT_PASSAGE, 9, 10
	mapgroup VERMILION_PORT_PASSAGE, 9, 10
	mapgroup MOUNT_MOON_SQUARE, 9, 15
	mapgroup MOUNT_MOON_GIFT_SHOP, 4, 4
	mapgroup TIN_TOWER_ROOF, 9, 10

	newgroup
	mapgroup ROUTE_23, 9, 10
	mapgroup INDIGO_PLATEAU_POKECENTER_1F, 7, 9
	mapgroup WILLS_ROOM, 9, 5
	mapgroup KOGAS_ROOM, 9, 5
	mapgroup BRUNOS_ROOM, 9, 5
	mapgroup KARENS_ROOM, 9, 5
	mapgroup LANCES_ROOM, 12, 5
	mapgroup HALL_OF_FAME, 7, 5

	newgroup
	mapgroup ROUTE_13, 9, 30
	mapgroup ROUTE_14, 18, 10
	mapgroup ROUTE_15, 9, 20
	mapgroup ROUTE_18, 9, 10
	mapgroup FUCHSIA_CITY, 18, 20
	mapgroup FUCHSIA_MART, 4, 6
	mapgroup SAFARI_ZONE_MAIN_OFFICE, 4, 4
	mapgroup FUCHSIA_GYM, 9, 5
	mapgroup FUCHSIA_BILL_SPEECH_HOUSE, 4, 4
	mapgroup FUCHSIA_POKECENTER_1F, 4, 5
	mapgroup FUCHSIA_POKECENTER_2F_BETA, 4, 8
	mapgroup SAFARI_ZONE_WARDENS_HOME, 4, 5
	mapgroup ROUTE_15_FUCHSIA_GATE, 4, 5

	newgroup
	mapgroup ROUTE_8, 9, 20
	mapgroup ROUTE_12, 27, 10
	mapgroup ROUTE_10_SOUTH, 9, 10
	mapgroup LAVENDER_TOWN, 9, 10
	mapgroup LAVENDER_POKECENTER_1F, 4, 5
	mapgroup LAVENDER_POKECENTER_2F_BETA, 4, 8
	mapgroup MR_FUJIS_HOUSE, 4, 5
	mapgroup LAVENDER_TOWN_SPEECH_HOUSE, 4, 4
	mapgroup LAVENDER_NAME_RATER, 4, 4
	mapgroup LAVENDER_MART, 4, 6
	mapgroup SOUL_HOUSE, 4, 5
	mapgroup LAV_RADIO_TOWER_1F, 4, 10
	mapgroup ROUTE_8_SAFFRON_GATE, 4, 5
	mapgroup ROUTE_12_SUPER_ROD_HOUSE, 4, 4

	newgroup
	mapgroup ROUTE_28, 9, 20
	mapgroup SILVER_CAVE_OUTSIDE, 18, 20
	mapgroup SILVER_CAVE_POKECENTER_1F, 4, 5
	mapgroup ROUTE_28_FAMOUS_SPEECH_HOUSE, 4, 4

	newgroup
	mapgroup POKECENTER_2F, 4, 8
	mapgroup TRADE_CENTER, 4, 5
	mapgroup COLOSSEUM, 4, 5
	mapgroup TIME_CAPSULE, 4, 5
	mapgroup MOBILE_TRADE_ROOM_MOBILE, 4, 5
	mapgroup MOBILE_BATTLE_ROOM, 4, 5

	newgroup
	mapgroup ROUTE_7, 9, 10
	mapgroup ROUTE_16, 9, 10
	mapgroup ROUTE_17, 45, 10
	mapgroup CELADON_CITY, 18, 20
	mapgroup CELADON_DEPT_STORE_1F, 4, 8
	mapgroup CELADON_DEPT_STORE_2F, 4, 8
	mapgroup CELADON_DEPT_STORE_3F, 4, 8
	mapgroup CELADON_DEPT_STORE_4F, 4, 8
	mapgroup CELADON_DEPT_STORE_5F, 4, 8
	mapgroup CELADON_DEPT_STORE_6F, 4, 8
	mapgroup CELADON_DEPT_STORE_ELEVATOR, 2, 2
	mapgroup CELADON_MANSION_1F, 5, 4
	mapgroup CELADON_MANSION_2F, 5, 4
	mapgroup CELADON_MANSION_3F, 5, 4
	mapgroup CELADON_MANSION_ROOF, 5, 4
	mapgroup CELADON_MANSION_ROOF_HOUSE, 4, 4
	mapgroup CELADON_POKECENTER_1F, 4, 5
	mapgroup CELADON_POKECENTER_2F_BETA, 4, 8
	mapgroup CELADON_GAME_CORNER, 7, 10
	mapgroup CELADON_GAME_CORNER_PRIZE_ROOM, 3, 3
	mapgroup CELADON_GYM, 9, 5
	mapgroup CELADON_CAFE, 4, 6
	mapgroup ROUTE_16_FUCHSIA_SPEECH_HOUSE, 4, 4
	mapgroup ROUTE_16_GATE, 4, 5
	mapgroup ROUTE_7_SAFFRON_GATE, 4, 5
	mapgroup ROUTE_17_18_GATE, 4, 5

	newgroup
	mapgroup ROUTE_40, 18, 10
	mapgroup ROUTE_41, 27, 25
	mapgroup CIANWOOD_CITY, 27, 15
	mapgroup MANIAS_HOUSE, 4, 4
	mapgroup CIANWOOD_GYM, 9, 5
	mapgroup CIANWOOD_POKECENTER_1F, 4, 5
	mapgroup CIANWOOD_PHARMACY, 4, 4
	mapgroup CIANWOOD_CITY_PHOTO_STUDIO, 4, 4
	mapgroup CIANWOOD_LUGIA_SPEECH_HOUSE, 4, 4
	mapgroup POKE_SEERS_HOUSE, 4, 4
	mapgroup BATTLE_TOWER_1F, 5, 8
	mapgroup BATTLE_TOWER_BATTLE_ROOM, 4, 4
	mapgroup BATTLE_TOWER_ELEVATOR, 2, 2
	mapgroup BATTLE_TOWER_HALLWAY, 2, 11
	mapgroup ROUTE_40_BATTLE_TOWER_GATE, 4, 5
	mapgroup BATTLE_TOWER_OUTSIDE, 14, 10

	newgroup
	mapgroup ROUTE_2, 27, 10
	mapgroup ROUTE_22, 9, 20
	mapgroup VIRIDIAN_CITY, 18, 20
	mapgroup VIRIDIAN_GYM, 9, 5
	mapgroup VIRIDIAN_NICKNAME_SPEECH_HOUSE, 4, 4
	mapgroup TRAINER_HOUSE_1F, 7, 5
	mapgroup TRAINER_HOUSE_B1F, 8, 5
	mapgroup VIRIDIAN_MART, 4, 6
	mapgroup VIRIDIAN_POKECENTER_1F, 4, 5
	mapgroup VIRIDIAN_POKECENTER_2F_BETA, 4, 8
	mapgroup ROUTE_2_NUGGET_SPEECH_HOUSE, 4, 4
	mapgroup ROUTE_2_GATE, 4, 5
	mapgroup VICTORY_ROAD_GATE, 9, 10

	newgroup
	mapgroup ROUTE_26, 54, 10
	mapgroup ROUTE_27, 9, 40
	mapgroup ROUTE_29, 9, 30
	mapgroup NEW_BARK_TOWN, 9, 10
	mapgroup ELMS_LAB, 6, 5
	mapgroup KRISS_HOUSE_1F, 4, 5
	mapgroup KRISS_HOUSE_2F, 3, 4
	mapgroup KRISS_NEIGHBORS_HOUSE, 4, 4
	mapgroup ELMS_HOUSE, 4, 4
	mapgroup ROUTE_26_HEAL_SPEECH_HOUSE, 4, 4
	mapgroup ROUTE_26_DAY_OF_WEEK_SIBLINGS_HOUSE, 4, 4
	mapgroup ROUTE_27_SANDSTORM_HOUSE, 4, 4
	mapgroup ROUTE_29_46_GATE, 4, 5

	newgroup
	mapgroup ROUTE_5, 9, 10
	mapgroup SAFFRON_CITY, 18, 20
	mapgroup FIGHTING_DOJO, 6, 5
	mapgroup SAFFRON_GYM, 9, 10
	mapgroup SAFFRON_MART, 4, 6
	mapgroup SAFFRON_POKECENTER_1F, 4, 5
	mapgroup SAFFRON_POKECENTER_2F_BETA, 4, 8
	mapgroup MR_PSYCHICS_HOUSE, 4, 4
	mapgroup SAFFRON_TRAIN_STATION, 9, 10
	mapgroup SILPH_CO_1F, 4, 8
	mapgroup COPYCATS_HOUSE_1F, 4, 4
	mapgroup COPYCATS_HOUSE_2F, 3, 5
	mapgroup ROUTE_5_UNDERGROUND_ENTRANCE, 4, 4
	mapgroup ROUTE_5_SAFFRON_CITY_GATE, 4, 5
	mapgroup ROUTE_5_CLEANSE_TAG_SPEECH_HOUSE, 4, 4

	newgroup
	mapgroup ROUTE_30, 27, 10
	mapgroup ROUTE_31, 9, 20
	mapgroup CHERRYGROVE_CITY, 9, 20
	mapgroup CHERRYGROVE_MART, 4, 6
	mapgroup CHERRYGROVE_POKECENTER_1F, 4, 5
	mapgroup CHERRYGROVE_GYM_SPEECH_HOUSE, 4, 4
	mapgroup GUIDE_GENTS_HOUSE, 4, 4
	mapgroup CHERRYGROVE_EVOLUTION_SPEECH_HOUSE, 4, 4
	mapgroup ROUTE_30_BERRY_SPEECH_HOUSE, 4, 4
	mapgroup MR_POKEMONS_HOUSE, 4, 4
	mapgroup ROUTE_31_VIOLET_GATE, 4, 5

; elevator floors

	const_def
	const _B4F
	const _B3F
	const _B2F
	const _B1F
	const _1F
	const _2F
	const _3F
	const _4F
	const _5F
	const _6F
	const _7F
	const _8F
	const _9F
	const _10F
	const _11F
	const _ROOF

; connection directions

	const_def
	shift_const EAST
	shift_const WEST
	shift_const SOUTH
	shift_const NORTH

; permissions
const_value SET 1
	const TOWN
	const ROUTE
	const INDOOR
	const CAVE
	const PERM_5
	const GATE
	const DUNGEON

; object struct
	const_def
	const OBJECT_SPRITE
	const OBJECT_MAP_OBJECT_INDEX
	const OBJECT_SPRITE_TILE
	const OBJECT_03
	const OBJECT_04
	const OBJECT_FLAGS
	const OBJECT_PALETTE
	const OBJECT_DIRECTION_WALKING
	const OBJECT_FACING
	const OBJECT_09
	const OBJECT_STEP_DURATION
	const OBJECT_11
	const OBJECT_12
	const OBJECT_FACING_STEP
	const OBJECT_STANDING_TILE
	const OBJECT_NEXT_TILE
	const OBJECT_MAP_X
	const OBJECT_MAP_Y
	const OBJECT_NEXT_MAP_X
	const OBJECT_NEXT_MAP_Y
	const OBJECT_20
	const OBJECT_21
	const OBJECT_22
	const OBJECT_SPRITE_X
	const OBJECT_SPRITE_Y
	const OBJECT_SPRITE_X_OFFSET
	const OBJECT_SPRITE_Y_OFFSET
	const OBJECT_27
	const OBJECT_28
	const OBJECT_29
	const OBJECT_30
	const OBJECT_31
	const OBJECT_32
; 33-39 are not used

; map object struct
	const_def
	const MAPOBJECT_OBJECT_STRUCT_ID ; 0
	const MAPOBJECT_SPRITE ; 1
	const MAPOBJECT_Y_COORD ; 2
	const MAPOBJECT_X_COORD ; 3
	const MAPOBJECT_MOVEMENT ; 4
	const MAPOBJECT_RADIUS ; 5
	const MAPOBJECT_HOUR ; 6
	const MAPOBJECT_TIMEOFDAY ; 7
	const MAPOBJECT_COLOR ; 8
	const MAPOBJECT_RANGE ; 9
	const MAPOBJECT_SCRIPT_POINTER ; a
	const MAPOBJECT_POINTER_HI ; b
	const MAPOBJECT_EVENT_FLAG ; c
	const MAPOBJECT_FLAG_HI ; d
	const MAPOBJECT_E ; unused
	const MAPOBJECT_F ; unused

MAPOBJECT_SCREEN_HEIGHT EQU 11
MAPOBJECT_SCREEN_WIDTH EQU 12
OBJECT_STRUCT_3_DATA_WIDTH EQU 6
OBJECT_STRUCT_3_DATA_HEIGHT EQU 37

OW_DOWN  EQU $0
OW_UP    EQU $4
OW_LEFT  EQU $8
OW_RIGHT EQU $c

	const_def
	const EMOTE_SHOCK ; 0
	const EMOTE_QUESTION ; 1
	const EMOTE_HAPPY ; 2
	const EMOTE_SAD ; 3
	const EMOTE_HEART ; 4
	const EMOTE_BOLT ; 5
	const EMOTE_SLEEP ; 6
	const EMOTE_FISH ; 7
	const EMOTE_ROD_DOWN ; 8
	const EMOTE_ROD_UP ; 9
	const EMOTE_ROD_LEFT ; a
	const EMOTE_ROD_RIGHT ; b

	const_def
	const SIGNPOST_READ
	const SIGNPOST_UP
	const SIGNPOST_DOWN
	const SIGNPOST_RIGHT
	const SIGNPOST_LEFT
	const SIGNPOST_IFSET
	const SIGNPOST_IFNOTSET
	const SIGNPOST_ITEM
	const SIGNPOST_COPY

; I'm relocating spawn constants here, so that they can be used anywhere in the disassembly.


const_value = -1
	const SPAWN_N_A

	const SPAWN_HOME
	const SPAWN_DEBUG

	const SPAWN_PALLET
	const SPAWN_VIRIDIAN
	const SPAWN_PEWTER
	const SPAWN_CERULEAN
	const SPAWN_ROCK_TUNNEL
	const SPAWN_VERMILION
	const SPAWN_LAVENDER
	const SPAWN_SAFFRON
	const SPAWN_CELADON
	const SPAWN_FUCHSIA
	const SPAWN_CINNABAR
	const SPAWN_INDIGO

	const SPAWN_NEW_BARK
	const SPAWN_CHERRYGROVE
	const SPAWN_VIOLET
	const SPAWN_UNION_CAVE
	const SPAWN_AZALEA
	const SPAWN_CIANWOOD
	const SPAWN_GOLDENROD
	const SPAWN_OLIVINE
	const SPAWN_ECRUTEAK
	const SPAWN_MAHOGANY
	const SPAWN_LAKE
	const SPAWN_BLACKTHORN
	const SPAWN_MT_SILVER
	const SPAWN_FAST_SHIP
NUM_SPAWNS EQU const_value

	const_def
	const PALETTE_AUTO
	const PALETTE_DAY
	const PALETTE_NITE
	const PALETTE_MORN
	const PALETTE_DARK
