
	const_def
	const NO_MOVE
	const POUND
	const KARATE_CHOP
	const DOUBLESLAP
	const COMET_PUNCH
	const MEGA_PUNCH
	const PAY_DAY
	const FIRE_PUNCH
	const ICE_PUNCH
	const THUNDERPUNCH
	const SCRATCH
	const VICEGRIP
	const GUILLOTINE
	const RAZOR_WIND
	const SWORDS_DANCE
	const CUT
	const GUST
	const WING_ATTACK
	const WHIRLWIND
	const FLY
	const BIND
	const SLAM
	const VINE_WHIP
	const STOMP
	const DOUBLE_KICK
	const MEGA_KICK
	const JUMP_KICK
	const ROLLING_KICK
	const SAND_ATTACK
	const HEADBUTT
	const HORN_ATTACK
	const FURY_ATTACK
	const HORN_DRILL
	const TACKLE
	const BODY_SLAM
	const WRAP
	const TAKE_DOWN
	const THRASH
	const DOUBLE_EDGE
	const TAIL_WHIP
	const POISON_STING
	const TWINEEDLE
	const PIN_MISSILE
	const LEER
	const BITE
	const GROWL
	const ROAR
	const SING
	const SUPERSONIC
	const SONICBOOM
	const DISABLE
	const ACID
	const EMBER
	const FLAMETHROWER
	const MIST
	const WATER_GUN
	const HYDRO_PUMP
	const SURF
	const ICE_BEAM
	const BLIZZARD
	const PSYBEAM
	const BUBBLEBEAM
	const AURORA_BEAM
	const HYPER_BEAM
	const PECK
	const DRILL_PECK
	const SUBMISSION
	const LOW_KICK
	const COUNTER
	const SEISMIC_TOSS
	const STRENGTH
	const ABSORB
	const MEGA_DRAIN
	const LEECH_SEED
	const GROWTH
	const RAZOR_LEAF
	const SOLARBEAM
	const POISONPOWDER
	const STUN_SPORE
	const SLEEP_POWDER
	const PETAL_DANCE
	const STRING_SHOT
	const DRAGON_RAGE
	const FIRE_SPIN
	const THUNDERSHOCK
	const THUNDERBOLT
	const THUNDER_WAVE
	const THUNDER
	const ROCK_THROW
	const EARTHQUAKE
	const FISSURE
	const DIG
	const TOXIC
	const CONFUSION
	const PSYCHIC_M
	const HYPNOSIS
	const MEDITATE
	const AGILITY
	const QUICK_ATTACK
	const RAGE
	const TELEPORT
	const NIGHT_SHADE
	const MIMIC
	const SCREECH
	const DOUBLE_TEAM
	const RECOVER
	const HARDEN
	const MINIMIZE
	const SMOKESCREEN
	const CONFUSE_RAY
	const WITHDRAW
	const DEFENSE_CURL
	const BARRIER
	const LIGHT_SCREEN
	const HAZE
	const REFLECT
	const FOCUS_ENERGY
	const BIDE
	const METRONOME
	const MIRROR_MOVE
	const SELFDESTRUCT
	const EGG_BOMB
	const LICK
	const SMOG
	const SLUDGE
	const BONE_CLUB
	const FIRE_BLAST
	const WATERFALL
	const CLAMP
	const SWIFT
	const SKULL_BASH
	const SPIKE_CANNON
	const CONSTRICT
	const AMNESIA
	const KINESIS
	const SOFTBOILED
	const HI_JUMP_KICK
	const GLARE
	const DREAM_EATER
	const POISON_GAS
	const BARRAGE
	const LEECH_LIFE
	const LOVELY_KISS
	const SKY_ATTACK
	const TRANSFORM
	const BUBBLE
	const DIZZY_PUNCH
	const SPORE
	const FLASH
	const PSYWAVE
	const SPLASH
	const ACID_ARMOR
	const CRABHAMMER
	const EXPLOSION
	const FURY_SWIPES
	const BONEMERANG
	const REST
	const ROCK_SLIDE
	const HYPER_FANG
	const SHARPEN
	const CONVERSION
	const TRI_ATTACK
	const SUPER_FANG
	const SLASH
	const SUBSTITUTE
	const STRUGGLE
	const SKETCH
	const TRIPLE_KICK
	const THIEF
	const SPIDER_WEB
	const MIND_READER
	const NIGHTMARE
	const FLAME_WHEEL
	const SNORE
	const CURSE
	const FLAIL
	const CONVERSION2
	const AEROBLAST
	const COTTON_SPORE
	const REVERSAL
	const SPITE
	const POWDER_SNOW
	const PROTECT
	const MACH_PUNCH
	const SCARY_FACE
	const FAINT_ATTACK
	const SWEET_KISS
	const BELLY_DRUM
	const SLUDGE_BOMB
	const MUD_SLAP
	const OCTAZOOKA
	const SPIKES
	const ZAP_CANNON
	const FORESIGHT
	const DESTINY_BOND
	const PERISH_SONG
	const ICY_WIND
	const DETECT
	const BONE_RUSH
	const LOCK_ON
	const OUTRAGE
	const SANDSTORM
	const GIGA_DRAIN
	const ENDURE
	const CHARM
	const ROLLOUT
	const FALSE_SWIPE
	const SWAGGER
	const MILK_DRINK
	const SPARK
	const FURY_CUTTER
	const STEEL_WING
	const MEAN_LOOK
	const ATTRACT
	const SLEEP_TALK
	const HEAL_BELL
	const RETURN
	const PRESENT
	const FRUSTRATION
	const SAFEGUARD
	const PAIN_SPLIT
	const SACRED_FIRE
	const MAGNITUDE
	const DYNAMICPUNCH
	const MEGAHORN
	const DRAGONBREATH
	const BATON_PASS
	const ENCORE
	const PURSUIT
	const RAPID_SPIN
	const SWEET_SCENT
	const IRON_TAIL
	const METAL_CLAW
	const VITAL_THROW
	const MORNING_SUN
	const SYNTHESIS
	const MOONLIGHT
	const HIDDEN_POWER
	const CROSS_CHOP
	const TWISTER
	const RAIN_DANCE
	const SUNNY_DAY
	const CRUNCH
	const MIRROR_COAT
	const PSYCH_UP
	const EXTREMESPEED
	const ANCIENTPOWER
	const SHADOW_BALL
	const FUTURE_SIGHT
	const ROCK_SMASH
	const WHIRLPOOL
	const BEAT_UP

const_value SET const_value + -1

	const NUM_ATTACKS

