NUM_POKEMON EQU 251

const_value set 1
	const BULBASAUR
	const IVYSAUR
	const VENUSAUR
	const CHARMANDER
	const CHARMELEON
	const CHARIZARD
	const SQUIRTLE
	const WARTORTLE
	const BLASTOISE
	const CATERPIE
	const METAPOD
	const BUTTERFREE
	const WEEDLE
	const KAKUNA
	const BEEDRILL
	const PIDGEY
	const PIDGEOTTO
	const PIDGEOT
	const RATTATA
	const RATICATE
	const SPEAROW
	const FEAROW
	const EKANS
	const ARBOK
	const PIKACHU
	const RAICHU
	const SANDSHREW
	const SANDSLASH
	const NIDORAN_F
	const NIDORINA
	const NIDOQUEEN
	const NIDORAN_M
	const NIDORINO
	const NIDOKING
	const CLEFAIRY
	const CLEFABLE
	const VULPIX
	const NINETALES
	const JIGGLYPUFF
	const WIGGLYTUFF
	const ZUBAT
	const GOLBAT
	const ODDISH
	const GLOOM
	const VILEPLUME
	const PARAS
	const PARASECT
	const VENONAT
	const VENOMOTH
	const DIGLETT
	const DUGTRIO
	const MEOWTH
	const PERSIAN
	const PSYDUCK
	const GOLDUCK
	const MANKEY
	const PRIMEAPE
	const GROWLITHE
	const ARCANINE
	const POLIWAG
	const POLIWHIRL
	const POLIWRATH
	const ABRA
	const KADABRA
	const ALAKAZAM
	const MACHOP
	const MACHOKE
	const MACHAMP
	const BELLSPROUT
	const WEEPINBELL
	const VICTREEBEL
	const TENTACOOL
	const TENTACRUEL
	const GEODUDE
	const GRAVELER
	const GOLEM
	const PONYTA
	const RAPIDASH
	const SLOWPOKE
	const SLOWBRO
	const MAGNEMITE
	const MAGNETON
	const FARFETCH_D
	const DODUO
	const DODRIO
	const SEEL
	const DEWGONG
	const GRIMER
	const MUK
	const SHELLDER
	const CLOYSTER
	const GASTLY
	const HAUNTER
	const GENGAR
	const ONIX
	const DROWZEE
	const HYPNO
	const KRABBY
	const KINGLER
	const VOLTORB
	const ELECTRODE
	const EXEGGCUTE
	const EXEGGUTOR
	const CUBONE
	const MAROWAK
	const HITMONLEE
	const HITMONCHAN
	const LICKITUNG
	const KOFFING
	const WEEZING
	const RHYHORN
	const RHYDON
	const CHANSEY
	const TANGELA
	const KANGASKHAN
	const HORSEA
	const SEADRA
	const GOLDEEN
	const SEAKING
	const STARYU
	const STARMIE
	const MR__MIME
	const SCYTHER
	const JYNX
	const ELECTABUZZ
	const MAGMAR
	const PINSIR
	const TAUROS
	const MAGIKARP
	const GYARADOS
	const LAPRAS
	const DITTO
	const EEVEE
	const VAPOREON
	const JOLTEON
	const FLAREON
	const PORYGON
	const OMANYTE
	const OMASTAR
	const KABUTO
	const KABUTOPS
	const AERODACTYL
	const SNORLAX
	const ARTICUNO
	const ZAPDOS
	const MOLTRES
	const DRATINI
	const DRAGONAIR
	const DRAGONITE
	const MEWTWO
	const MEW
	const CHIKORITA
	const BAYLEEF
	const MEGANIUM
	const CYNDAQUIL
	const QUILAVA
	const TYPHLOSION
	const TOTODILE
	const CROCONAW
	const FERALIGATR
	const SENTRET
	const FURRET
	const HOOTHOOT
	const NOCTOWL
	const LEDYBA
	const LEDIAN
	const SPINARAK
	const ARIADOS
	const CROBAT
	const CHINCHOU
	const LANTURN
	const PICHU
	const CLEFFA
	const IGGLYBUFF
	const TOGEPI
	const TOGETIC
	const NATU
	const XATU
	const MAREEP
	const FLAAFFY
	const AMPHAROS
	const BELLOSSOM
	const MARILL
	const AZUMARILL
	const SUDOWOODO
	const POLITOED
	const HOPPIP
	const SKIPLOOM
	const JUMPLUFF
	const AIPOM
	const SUNKERN
	const SUNFLORA
	const YANMA
	const WOOPER
	const QUAGSIRE
	const ESPEON
	const UMBREON
	const MURKROW
	const SLOWKING
	const MISDREAVUS
	const UNOWN
	const WOBBUFFET
	const GIRAFARIG
	const PINECO
	const FORRETRESS
	const DUNSPARCE
	const GLIGAR
	const STEELIX
	const SNUBBULL
	const GRANBULL
	const QWILFISH
	const SCIZOR
	const SHUCKLE
	const HERACROSS
	const SNEASEL
	const TEDDIURSA
	const URSARING
	const SLUGMA
	const MAGCARGO
	const SWINUB
	const PILOSWINE
	const CORSOLA
	const REMORAID
	const OCTILLERY
	const DELIBIRD
	const MANTINE
	const SKARMORY
	const HOUNDOUR
	const HOUNDOOM
	const KINGDRA
	const PHANPY
	const DONPHAN
	const PORYGON2
	const STANTLER
	const SMEARGLE
	const TYROGUE
	const HITMONTOP
	const SMOOCHUM
	const ELEKID
	const MAGBY
	const MILTANK
	const BLISSEY
	const RAIKOU
	const ENTEI
	const SUICUNE
	const LARVITAR
	const PUPITAR
	const TYRANITAR
	const LUGIA
	const HO_OH
	const CELEBI

EGG EQU 253
