; script vars
PLAYER      EQU  0
LAST_TALKED EQU -2

	const_def
	const VAR_STRINGBUFFER2
	const VAR_PARTYCOUNT
	const VAR_BATTLERESULT
	const VAR_BATTLETYPE
	const VAR_TIMEOFDAY
	const VAR_DEXCAUGHT
	const VAR_DEXSEEN
	const VAR_BADGES
	const VAR_MOVEMENT
	const VAR_FACING
	const VAR_HOUR
	const VAR_WEEKDAY
	const VAR_MAPGROUP
	const VAR_MAPNUMBER
	const VAR_UNOWNCOUNT
	const VAR_ROOFPALETTE
	const VAR_BOXSPACE
	const VAR_CONTESTMINUTES
	const VAR_XCOORD
	const VAR_YCOORD
	const VAR_SPECIALPHONECALL
	const VAR_15
	const VAR_KURT_APRICORNS
	const VAR_CALLERID
	const VAR_BLUECARDBALANCE
	const VAR_BUENASPASSWORD
	const VAR_KENJI_BREAK
NUM_VARS EQU const_value

RETVAR_STRBUF2 EQU (0 << 6)
RETVAR_ADDR_DE EQU (1 << 6)
RETVAR_EXECUTE EQU (2 << 6)

const_value SET -1
	const PLAYEREVENT_MAPSCRIPT
	const PLAYEREVENT_NONE
	const PLAYEREVENT_SEENBYTRAINER
	const PLAYEREVENT_TALKTOTRAINER
	const PLAYEREVENT_ITEMBALL
	const PLAYEREVENT_CONNECTION
	const PLAYEREVENT_WARP
	const PLAYEREVENT_FALL
	const PLAYEREVENT_WHITEOUT
	const PLAYEREVENT_HATCH
	const PLAYEREVENT_JOYCHANGEFACING
NUM_PLAYER_EVENTS EQU const_value
