; script vars

	const_def
	const VAR_STRINGBUFFER2
	const VAR_PARTYCOUNT
	const VAR_02
	const VAR_BATTLETYPE
	const VAR_TIMEOFDAY
	const VAR_DEXCAUGHT
	const VAR_DEXSEEN
	const VAR_BADGES
	const VAR_MOVEMENT
	const VAR_FACING
	const VAR_HOUR
	const VAR_WEEKDAY
	const VAR_MAPGROUP
	const VAR_MAPNUMBER
	const VAR_UNOWNCOUNT
	const VAR_ROOFPALETTE
	const VAR_BOXSPACE
	const VAR_CONTESTMINUTES
	const VAR_XCOORD
	const VAR_YCOORD
	const VAR_POKERUS
	const VAR_15
	const VAR_16
	const VAR_CALLERID
	const VAR_BLUECARDBALANCE
	const VAR_19
	const VAR_KENJI_BREAK
NUM_VARS EQU const_value
