; SFX indexes (see audio/sfx_pointers.asm)
	const_def

	const SFX_DEX_FANFARE_50_79           ; 00
	const SFX_ITEM                        ; 01
	const SFX_CAUGHT_MON                  ; 02
	const SFX_POKEBALLS_PLACED_ON_TABLE   ; 03
	const SFX_POTION                      ; 04
	const SFX_FULL_HEAL                   ; 05
	const SFX_MENU                        ; 06
	const SFX_READ_TEXT                   ; 07
	const SFX_READ_TEXT_2                 ; 08
	const SFX_DEX_FANFARE_20_49           ; 09
	const SFX_DEX_FANFARE_80_109          ; 0a
	const SFX_POISON                      ; 0b
	const SFX_GOT_SAFARI_BALLS            ; 0c
	const SFX_BOOT_PC                     ; 0d
	const SFX_SHUT_DOWN_PC                ; 0e
	const SFX_CHOOSE_PC_OPTION            ; 0f
	const SFX_ESCAPE_ROPE                 ; 10
	const SFX_PUSH_BUTTON                 ; 11
	const SFX_SECOND_PART_OF_ITEMFINDER   ; 12
	const SFX_WARP_TO                     ; 13
	const SFX_WARP_FROM                   ; 14
	const SFX_CHANGE_DEX_MODE             ; 15
	const SFX_JUMP_OVER_LEDGE             ; 16
	const SFX_GRASS_RUSTLE                ; 17
	const SFX_FLY                         ; 18
	const SFX_WRONG                       ; 19
	const SFX_SQUEAK                      ; 1a
	const SFX_STRENGTH                    ; 1b
	const SFX_BOAT                        ; 1c
	const SFX_WALL_OPEN                   ; 1d
	const SFX_PLACE_PUZZLE_PIECE_DOWN     ; 1e
	const SFX_ENTER_DOOR                  ; 1f
	const SFX_SWITCH_POKEMON              ; 20
	const SFX_TALLY                       ; 21
	const SFX_TRANSACTION                 ; 22
	const SFX_EXIT_BUILDING               ; 23
	const SFX_BUMP                        ; 24
	const SFX_SAVE                        ; 25
	const SFX_POKEFLUTE                   ; 26
	const SFX_ELEVATOR_END                ; 27
	const SFX_THROW_BALL                  ; 28
	const SFX_BALL_POOF                   ; 29
	const SFX_FAINT                       ; 2a
	const SFX_RUN                         ; 2b
	const SFX_SLOT_MACHINE_START          ; 2c
	const SFX_FANFARE                     ; 2d
	const SFX_PECK                        ; 2e
	const SFX_KINESIS                     ; 2f
	const SFX_LICK                        ; 30
	const SFX_POUND                       ; 31
	const SFX_MOVE_PUZZLE_PIECE           ; 32
	const SFX_COMET_PUNCH                 ; 33
	const SFX_MEGA_PUNCH                  ; 34
	const SFX_SCRATCH                     ; 35
	const SFX_VICEGRIP                    ; 36
	const SFX_RAZOR_WIND                  ; 37
	const SFX_CUT                         ; 38
	const SFX_WING_ATTACK                 ; 39
	const SFX_WHIRLWIND                   ; 3a
	const SFX_BIND                        ; 3b
	const SFX_VINE_WHIP                   ; 3c
	const SFX_DOUBLE_KICK                 ; 3d
	const SFX_MEGA_KICK                   ; 3e
	const SFX_HEADBUTT                    ; 3f
	const SFX_HORN_ATTACK                 ; 40
	const SFX_TACKLE                      ; 41
	const SFX_POISON_STING                ; 42
	const SFX_POWDER                      ; 43
	const SFX_DOUBLESLAP                  ; 44
	const SFX_BITE                        ; 45
	const SFX_JUMP_KICK                   ; 46
	const SFX_STOMP                       ; 47
	const SFX_TAIL_WHIP                   ; 48
	const SFX_KARATE_CHOP                 ; 49
	const SFX_SUBMISSION                  ; 4a
	const SFX_WATER_GUN                   ; 4b
	const SFX_SWORDS_DANCE                ; 4c
	const SFX_THUNDER                     ; 4d
	const SFX_SUPERSONIC                  ; 4e
	const SFX_LEER                        ; 4f
	const SFX_EMBER                       ; 50
	const SFX_BUBBLEBEAM                  ; 51
	const SFX_HYDRO_PUMP                  ; 52
	const SFX_SURF                        ; 53
	const SFX_PSYBEAM                     ; 54
	const SFX_CHARGE                      ; 55
	const SFX_THUNDERSHOCK                ; 56
	const SFX_PSYCHIC                     ; 57
	const SFX_SCREECH                     ; 58
	const SFX_BONE_CLUB                   ; 59
	const SFX_SHARPEN                     ; 5a
	const SFX_EGG_BOMB                    ; 5b
	const SFX_SING                        ; 5c
	const SFX_HYPER_BEAM                  ; 5d
	const SFX_SHINE                       ; 5e
	const SFX_UNKNOWN_5F                  ; 5f
	const SFX_UNKNOWN_60                  ; 60
	const SFX_UNKNOWN_61                  ; 61
	const SFX_SWITCH_POCKETS              ; 62
	const SFX_UNKNOWN_63                  ; 63
	const SFX_BURN                        ; 64
	const SFX_TITLE_SCREEN_ENTRANCE       ; 65
	const SFX_UNKNOWN_66                  ; 66
	const SFX_GET_COIN_FROM_SLOTS         ; 67
	const SFX_PAY_DAY                     ; 68
	const SFX_METRONOME                   ; 69
	const SFX_CALL                        ; 6a
	const SFX_HANG_UP                     ; 6b
	const SFX_NO_SIGNAL                   ; 6c
	const SFX_SANDSTORM                   ; 6d
	const SFX_ELEVATOR                    ; 6e
	const SFX_PROTECT                     ; 6f
	const SFX_SKETCH                      ; 70
	const SFX_RAIN_DANCE                  ; 71
	const SFX_AEROBLAST                   ; 72
	const SFX_SPARK                       ; 73
	const SFX_CURSE                       ; 74
	const SFX_RAGE                        ; 75
	const SFX_THIEF                       ; 76
	const SFX_THIEF_2                     ; 77
	const SFX_SPIDER_WEB                  ; 78
	const SFX_MIND_READER                 ; 79
	const SFX_NIGHTMARE                   ; 7a
	const SFX_SNORE                       ; 7b
	const SFX_SWEET_KISS                  ; 7c
	const SFX_SWEET_KISS_2                ; 7d
	const SFX_BELLY_DRUM                  ; 7e
	const SFX_TOXIC                       ; 7f
	const SFX_SLUDGE_BOMB                 ; 80
	const SFX_FORESIGHT                   ; 81
	const SFX_SPITE                       ; 82
	const SFX_OUTRAGE                     ; 83
	const SFX_PERISH_SONG                 ; 84
	const SFX_GIGA_DRAIN                  ; 85
	const SFX_ATTRACT                     ; 86
	const SFX_KINESIS_2                   ; 87
	const SFX_ZAP_CANNON                  ; 88
	const SFX_MEAN_LOOK                   ; 89
	const SFX_HEAL_BELL                   ; 8a
	const SFX_RETURN                      ; 8b
	const SFX_EXP_BAR                     ; 8c
	const SFX_MILK_DRINK                  ; 8d
	const SFX_PRESENT                     ; 8e
	const SFX_MORNING_SUN                 ; 8f
	const SFX_LEVEL_UP                    ; 90
	const SFX_KEY_ITEM                    ; 91
	const SFX_FANFARE_2                   ; 92
	const SFX_REGISTER_PHONE_NUMBER       ; 93
	const SFX_3RD_PLACE                   ; 94
	const SFX_GET_EGG_FROM_DAY_CARE_MAN   ; 95
	const SFX_GET_EGG_FROM_DAY_CARE_LADY  ; 96
	const SFX_MOVE_DELETED                ; 97
	const SFX_2ND_PLACE                   ; 98
	const SFX_1ST_PLACE                   ; 99
	const SFX_CHOOSE_A_CARD               ; 9a
	const SFX_GET_TM                      ; 9b
	const SFX_GET_BADGE                   ; 9c
	const SFX_QUIT_SLOTS                  ; 9d
	const SFX_EGG_CRACK                   ; 9e
	const SFX_DEX_FANFARE_LESS_THAN_20    ; 9f
	const SFX_DEX_FANFARE_140_169         ; a0
	const SFX_DEX_FANFARE_170_199         ; a1
	const SFX_DEX_FANFARE_200_229         ; a2
	const SFX_DEX_FANFARE_230_PLUS        ; a3
	const SFX_EVOLVED                     ; a4
	const SFX_MASTER_BALL                 ; a5
	const SFX_EGG_HATCH                   ; a6
	const SFX_GS_INTRO_CHARIZARD_FIREBALL ; a7
	const SFX_GS_INTRO_POKEMON_APPEARS    ; a8
	const SFX_FLASH                       ; a9
	const SFX_GAME_FREAK_LOGO_GS          ; aa
	const SFX_NOT_VERY_EFFECTIVE          ; ab
	const SFX_DAMAGE                      ; ac
	const SFX_SUPER_EFFECTIVE             ; ad
	const SFX_BALL_BOUNCE                 ; ae
	const SFX_MOONLIGHT                   ; af
	const SFX_ENCORE                      ; b0
	const SFX_BEAT_UP                     ; b1
	const SFX_BATON_PASS                  ; b2
	const SFX_BALL_WOBBLE                 ; b3
	const SFX_SWEET_SCENT                 ; b4
	const SFX_SWEET_SCENT_2               ; b5
	const SFX_HIT_END_OF_EXP_BAR          ; b6
	const SFX_GIVE_TRADEMON               ; b7
	const SFX_GET_TRADEMON                ; b8
	const SFX_TRAIN_ARRIVED               ; b9
	const SFX_STOP_SLOT                   ; ba
	const SFX_2_BOOPS                     ; bb

; new to Crystal
	const SFX_GLASS_TING                  ; bc
	const SFX_GLASS_TING_2                ; bd
	const SFX_INTRO_UNOWN_1               ; be
	const SFX_INTRO_UNOWN_2               ; bf
	const SFX_INTRO_UNOWN_3               ; c0
	const SFX_DITTO_POP_UP                ; c1
	const SFX_DITTO_TRANSFORM             ; c2
	const SFX_INTRO_SUICUNE_1             ; c3
	const SFX_INTRO_PICHU                 ; c4
	const SFX_INTRO_SUICUNE_2             ; c5
	const SFX_INTRO_SUICUNE_3             ; c6
	const SFX_DITTO_BOUNCE                ; c7
	const SFX_INTRO_SUICUNE_4             ; c8
	const SFX_GAME_FREAK_PRESENTS         ; c9
	const SFX_TINGLE                      ; ca
	const SFX_INTRO_WHOOSH                ; cb
	const SFX_TWO_PC_BEEPS                ; cc
	const SFX_4_NOTE_DITTY                ; cd
	const SFX_TWINKLE                     ; ce
