; StdScripts indexes (see engine/events/std_scripts.asm)
; also used in TileCollisionStdScripts (see data/events/collision_stdscripts.asm)
	enum_start
	enum pokecenternurse
	enum difficultbookshelf
	enum picturebookshelf
	enum magazinebookshelf
	enum teamrocketoath
	enum incenseburner
	enum merchandiseshelf
	enum townmap
	enum window
	enum tv
	enum homepage
	enum radio1
	enum radio2
	enum trashcan
	enum strengthboulder
	enum smashrock
	enum pokecentersign
	enum martsign
	enum goldenrodrockets
	enum radiotowerrockets
	enum elevatorbutton
	enum daytotext
	enum bugcontestresultswarp
	enum bugcontestresults
	enum initializeevents
	enum asknumber1m
	enum asknumber2m
	enum registerednumberm
	enum numberacceptedm
	enum numberdeclinedm
	enum phonefullm
	enum rematchm
	enum giftm
	enum packfullm
	enum rematchgiftm
	enum asknumber1f
	enum asknumber2f
	enum registerednumberf
	enum numberacceptedf
	enum numberdeclinedf
	enum phonefullf
	enum rematchf
	enum giftf
	enum packfullf
	enum rematchgiftf
	enum gymstatue1
	enum gymstatue2
	enum receiveitem
	enum receivetogepiegg
	enum pcscript
	enum gamecornercoinvendor
	enum happinesschecknpc
