gfx/battle_anims/aeroblast.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/battle_anims/angels.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/beam.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/bubble.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/charge.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/cut.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/egg.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/explosion.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/fire.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/flower.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/globe.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/haze.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/hit.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/horn.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/ice.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/lightning.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/misc.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/noise.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/objects.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/plant.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/poison.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/pokeball.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/powder.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/psychic.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/reflect.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/rocks.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/rope.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/sand.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/shapes.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/battle_anims/shine.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/battle_anims/skyattack.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/smoke.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/speed.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/status.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/water.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/wave.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/web.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/whip.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle_anims/wind.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/battle/dude.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/card_flip/card_flip_1.2bpp.lz: LZFLAGS = --method 80
gfx/card_flip/card_flip_2.2bpp.lz: LZFLAGS = --method 80
gfx/card_flip/card_flip_3.2bpp.lz: LZFLAGS = --method 80
gfx/diploma/diploma.2bpp.lz: LZFLAGS = --method 88 --align 1
gfx/dummy_game/dummy_game.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/intro/background.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/intro/background.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/background.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/crystal_unowns.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/intro/crystal_unowns.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/crystal_unowns.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/logo.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/intro/pichu_wooper.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/intro/pulse.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_back.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_back.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_back.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_close.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/intro/suicune_close.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_close.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_jump.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_jump.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_jump.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/suicune_run.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/intro/unown_a.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/unown_a.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/unown_back.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/intro/unown_hi.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/unown_hi.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/unowns.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/intro/unowns.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/intro/unowns.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/mobile/electro_ball.2bpp.lz: LZFLAGS = --method 80
gfx/mobile/mobile_trade.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/mobile/mobile_trade.attrmap.lz: LZFLAGS = --method 80 --align 4
gfx/mobile/mobile_trade_sprites.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/mobile/mobile_trade.tilemap.lz: LZFLAGS = --method 80 --align 4
gfx/mobile/pichu_animated.2bpp.lz: LZFLAGS = --method 80
gfx/new_game/shrink1.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/new_game/shrink2.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/pc/pc.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/player/chris_back.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/pokedex/pokedex.2bpp.lz: LZFLAGS = --method 88
gfx/pokedex/pokedex_sgb.2bpp.lz: LZFLAGS = --method 88 --align 1
gfx/pokedex/question_mark.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/pokedex/slowpoke.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/pokegear/pokegear.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/pokegear/pokegear_sprites.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/pokegear/town_map.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/pokemon/abra/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/abra/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/aerodactyl/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/aerodactyl/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/aipom/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/aipom/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/alakazam/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/alakazam/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ampharos/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ampharos/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/arbok/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/arbok/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/arcanine/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/arcanine/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ariados/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ariados/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/articuno/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/articuno/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/azumarill/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/azumarill/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/bayleef/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/bayleef/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/beedrill/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/beedrill/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/bellossom/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/bellossom/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/bellsprout/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/bellsprout/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/blastoise/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/blastoise/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/blissey/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/blissey/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/bulbasaur/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/bulbasaur/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/butterfree/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/butterfree/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/caterpie/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/caterpie/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/celebi/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/celebi/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/chansey/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/chansey/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/charizard/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/charizard/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/charmander/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/charmander/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/charmeleon/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/charmeleon/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/chikorita/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/chikorita/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/chinchou/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/chinchou/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/clefable/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/clefable/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/clefairy/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/clefairy/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/cleffa/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/cleffa/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/cloyster/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/cloyster/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/corsola/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/corsola/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/crobat/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/crobat/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/croconaw/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/croconaw/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/cubone/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/cubone/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/cyndaquil/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/cyndaquil/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/delibird/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/delibird/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dewgong/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dewgong/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/diglett/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/diglett/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ditto/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ditto/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dodrio/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dodrio/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/doduo/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/doduo/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/donphan/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/donphan/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dragonair/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dragonair/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dragonite/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dragonite/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dratini/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dratini/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/drowzee/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/drowzee/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dugtrio/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dugtrio/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dunsparce/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/dunsparce/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/eevee/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/eevee/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/egg/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/egg/unused_front.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ekans/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ekans/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/electabuzz/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/electabuzz/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/electrode/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/electrode/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/elekid/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/elekid/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/entei/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/entei/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/espeon/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/espeon/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/exeggcute/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/exeggcute/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/exeggutor/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/exeggutor/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/farfetch_d/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/farfetch_d/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/fearow/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/fearow/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/feraligatr/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/feraligatr/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/flaaffy/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/flaaffy/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/flareon/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/flareon/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/forretress/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/forretress/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/furret/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/furret/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gastly/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gastly/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gengar/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gengar/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/geodude/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/geodude/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/girafarig/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/girafarig/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gligar/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gligar/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gloom/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gloom/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/golbat/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/golbat/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/goldeen/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/goldeen/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/golduck/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/golduck/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/golem/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/golem/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/granbull/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/granbull/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/graveler/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/graveler/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/grimer/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/grimer/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/growlithe/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/growlithe/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gyarados/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/gyarados/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/haunter/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/haunter/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/heracross/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/heracross/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hitmonchan/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hitmonchan/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hitmonlee/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hitmonlee/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hitmontop/back.2bpp.lz: LZFLAGS = --method 84
gfx/pokemon/hitmontop/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ho_oh/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ho_oh/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hoothoot/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hoothoot/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hoppip/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hoppip/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/horsea/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/horsea/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/houndoom/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/houndoom/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/houndour/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/houndour/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hypno/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/hypno/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/igglybuff/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/igglybuff/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ivysaur/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ivysaur/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/jigglypuff/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/jigglypuff/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/jolteon/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/jolteon/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/jumpluff/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/jumpluff/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/jynx/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/jynx/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kabuto/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kabuto/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kabutops/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kabutops/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kadabra/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kadabra/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kakuna/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kakuna/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kangaskhan/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kangaskhan/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kingdra/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kingdra/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kingler/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/kingler/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/koffing/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/koffing/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/krabby/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/krabby/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/lanturn/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/lanturn/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/lapras/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/lapras/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/larvitar/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/larvitar/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ledian/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ledian/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ledyba/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ledyba/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/lickitung/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/lickitung/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/lugia/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/lugia/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/machamp/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/machamp/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/machoke/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/machoke/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/machop/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/machop/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magby/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magby/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magcargo/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magcargo/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magikarp/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magikarp/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magmar/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magmar/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magnemite/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magnemite/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magneton/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/magneton/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mankey/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mankey/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mantine/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mantine/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mareep/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mareep/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/marill/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/marill/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/marowak/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/marowak/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/meganium/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/meganium/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/meowth/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/meowth/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/metapod/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/metapod/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mew/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mew/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mewtwo/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mewtwo/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/miltank/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/miltank/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/misdreavus/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/misdreavus/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/moltres/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/moltres/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mr__mime/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/mr__mime/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/muk/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/muk/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/murkrow/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/murkrow/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/natu/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/natu/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidoking/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidoking/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidoqueen/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidoqueen/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidoran_f/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidoran_f/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidoran_m/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidoran_m/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidorina/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidorina/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidorino/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/nidorino/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ninetales/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ninetales/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/noctowl/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/noctowl/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/octillery/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/octillery/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/oddish/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/oddish/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/omanyte/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/omanyte/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/omastar/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/omastar/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/onix/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/onix/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/paras/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/parasect/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/parasect/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/paras/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/persian/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/persian/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/phanpy/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/phanpy/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pichu/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pichu/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pidgeot/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pidgeot/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pidgeotto/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pidgeotto/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pidgey/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pidgey/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pikachu/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pikachu/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/piloswine/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/piloswine/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pineco/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pineco/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pinsir/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pinsir/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/politoed/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/politoed/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/poliwag/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/poliwag/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/poliwhirl/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/poliwhirl/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/poliwrath/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/poliwrath/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ponyta/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ponyta/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/porygon2/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/porygon2/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/porygon/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/porygon/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/primeape/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/primeape/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/psyduck/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/psyduck/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pupitar/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/pupitar/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/quagsire/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/quagsire/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/quilava/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/quilava/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/qwilfish/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/qwilfish/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/raichu/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/raichu/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/raikou/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/raikou/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/rapidash/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/rapidash/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/raticate/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/raticate/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/rattata/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/rattata/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/remoraid/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/remoraid/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/rhydon/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/rhydon/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/rhyhorn/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/rhyhorn/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sandshrew/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sandshrew/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sandslash/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sandslash/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/scizor/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/scizor/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/scyther/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/scyther/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/seadra/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/seadra/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/seaking/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/seaking/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/seel/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/seel/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sentret/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sentret/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/shellder/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/shellder/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/shuckle/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/shuckle/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/skarmory/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/skarmory/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/skiploom/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/skiploom/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/slowbro/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/slowbro/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/slowking/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/slowking/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/slowpoke/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/slowpoke/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/slugma/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/slugma/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/smeargle/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/smeargle/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/smoochum/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/smoochum/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sneasel/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sneasel/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/snorlax/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/snorlax/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/snubbull/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/snubbull/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/spearow/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/spearow/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/spinarak/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/spinarak/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/squirtle/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/squirtle/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/stantler/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/stantler/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/starmie/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/starmie/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/staryu/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/staryu/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/steelix/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/steelix/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sudowoodo/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sudowoodo/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/suicune/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/suicune/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sunflora/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sunflora/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sunkern/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/sunkern/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/swinub/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/swinub/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tangela/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tangela/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tauros/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tauros/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/teddiursa/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/teddiursa/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tentacool/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tentacool/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tentacruel/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tentacruel/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/togepi/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/togepi/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/togetic/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/togetic/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/totodile/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/totodile/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/typhlosion/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/typhlosion/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tyranitar/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tyranitar/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tyrogue/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/tyrogue/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/umbreon/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/umbreon/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_a/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_a/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_b/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_b/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_c/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_c/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_d/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_d/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_e/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_e/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_f/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_f/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_g/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_g/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_h/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_h/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_i/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_i/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_j/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_j/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_k/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_k/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_l/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_l/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_m/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_m/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_n/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_n/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_o/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_o/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_p/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_p/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_q/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_q/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_r/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_r/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_s/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_s/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_t/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_t/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_u/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_u/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_v/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_v/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_w/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_w/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_x/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_x/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_y/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_y/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_z/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/unown_z/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ursaring/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/ursaring/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/vaporeon/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/vaporeon/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/venomoth/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/venomoth/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/venonat/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/venonat/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/venusaur/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/venusaur/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/victreebel/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/victreebel/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/vileplume/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/vileplume/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/voltorb/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/voltorb/front.animated.2bpp.lz: LZFLAGS = --method 84
gfx/pokemon/vulpix/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/vulpix/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/wartortle/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/wartortle/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/weedle/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/weedle/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/weepinbell/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/weepinbell/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/weezing/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/weezing/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/wigglytuff/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/wigglytuff/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/wobbuffet/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/wobbuffet/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/wooper/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/wooper/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/xatu/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/xatu/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/yanma/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/yanma/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/zapdos/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/zapdos/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/zubat/back.2bpp.lz: LZFLAGS = --method 80
gfx/pokemon/zubat/front.animated.2bpp.lz: LZFLAGS = --method 80
gfx/sgb/gbc_only.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/slots/slots_1.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/slots/slots_2.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/slots/slots_3.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/aerodactyl_word_room.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/battle_tower_inside.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/battle_tower_outside.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/beta_word_room.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/cave.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/champions_room.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/dark_cave.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/elite_four_room.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/facility.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/forest.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/game_corner.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/gate.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/ho_oh_word_room.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/house.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/tilesets/ice_path.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/johto.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/johto_modern.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/kabuto_word_room.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/kanto.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/lab.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/lighthouse.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/mansion.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/tilesets/mart.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/tilesets/omanyte_word_room.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/park.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/players_house.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/players_room.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/pokecenter.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/pokecom_center.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/port.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/radio_tower.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/ruins_of_alph.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/tilesets/tower.2bpp.lz: LZFLAGS = --method 82 --align 4
gfx/tilesets/traditional_house.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/train_station.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/tilesets/underground.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/title/crystal.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/title/logo.2bpp.lz: LZFLAGS = --method 73 --align 1
gfx/title/suicune.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/trade/game_boy.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/beauty.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/biker.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/bird_keeper.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/blackbelt_t.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/blaine.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/blue.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/boarder.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/brock.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/bruno.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/bug_catcher.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/bugsy.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/burglar.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/cal.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/camper.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/champion.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/chuck.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/clair.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/cooltrainer_f.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/cooltrainer_m.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/erika.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/executive_f.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/executive_m.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/falkner.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/firebreather.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/fisher.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/gentleman.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/grunt_f.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/grunt_m.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/guitarist.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/hiker.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/janine.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/jasmine.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/juggler.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/karen.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/kimono_girl.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/koga.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/lass.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/lt_surge.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/medium.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/misty.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/morty.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/mysticalman.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/oak.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/officer.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/picnicker.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/pokefan_f.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/pokefan_m.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/pokemaniac.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/pryce.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/psychic_t.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/red.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/rival1.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/rival2.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/sabrina.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/sage.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/sailor.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/schoolboy.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/scientist.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/skier.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/super_nerd.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/swimmer_f.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/swimmer_m.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/teacher.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/twins.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/whitney.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/will.2bpp.lz: LZFLAGS = --method 80
gfx/trainers/youngster.2bpp.lz: LZFLAGS = --method 80
gfx/unown_puzzle/aerodactyl.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/unown_puzzle/hooh.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/unown_puzzle/kabuto.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/unown_puzzle/omanyte.2bpp.lz: LZFLAGS = --method 80 --align 4
gfx/unown_puzzle/start_cancel.2bpp.lz: LZFLAGS = --method 88 --align 1
