; specials
NUM_SPECIALS EQU $a8

SPECIAL_UPDATESPRITETILES EQU $0038

SPECIAL_WAITSFX           EQU $003b
SPECIAL_BIKESURFMUSIC     EQU $003c

SPECIAL_LOADFACESTEP      EQU $003f

SPECIAL_GIVESHUCKLE       EQU $004b

SPECIAL_SNORLAXAWAKE      EQU $0060

SPECIAL_GAMEBOYCHECK      EQU $0066
SPECIAL_TRAINERHOUSE      EQU $0067

SPECIAL_RUSTLETREE        EQU $006a

SPECIAL_ODDEGG            EQU $007d

SPECIAL_MOVETUTOR         EQU $0083
SPECIAL_OMANYTECHAMBER    EQU $0084

SPECIAL_RUINCHAMBERWALL   EQU $0087

SPECIAL_HOOHCHAMBER       EQU $008d

SPECIAL_CELEBI            EQU $008f

SPECIAL_AFTERCELEBI       EQU $0090
SPECIAL_POKESEER          EQU $0091

SPECIAL_DRATINI           EQU $0094

SPECIAL_BEASTSCHECK       EQU $0096
SPECIAL_MONCHECK          EQU $0097


; script vars
NUM_VARS EQU $1b
VAR_MOVEMENT EQU $08
