INCLUDE "charmap.inc"
INCLUDE "macros/code.inc"
INCLUDE "macros/coords.inc"
INCLUDE "macros/gfx.inc"
INCLUDE "macros/predef.inc"
INCLUDE "macros/rst.inc"
INCLUDE "macros/scripts/text.inc"
INCLUDE "constants/wram_constants.inc"
INCLUDE "constants/battle_constants.inc"
INCLUDE "constants/input_constants.inc"
INCLUDE "constants/map_data_constants.inc"
INCLUDE "constants/menu_constants.inc"
INCLUDE "constants/misc_constants.inc"
INCLUDE "constants/mobile_constants.inc"
INCLUDE "constants/move_constants.inc"
INCLUDE "constants/music_constants.inc"
INCLUDE "constants/pokemon_data_constants.inc"
INCLUDE "constants/scgb_constants.inc"
INCLUDE "constants/script_constants.inc"
INCLUDE "constants/sfx_constants.inc"
INCLUDE "constants/sprite_anim_constants.inc"
INCLUDE "constants/tileset_constants.inc"


SECTION "engine/crystal.asm", ROMX

INCLUDE "engine/menus/init_gender.inc"
INCLUDE "engine/items/pack_kris.inc"
INCLUDE "engine/events/move_tutor.inc"
INCLUDE "engine/gfx/crystal_layouts.inc"
INCLUDE "engine/events/celebi.inc"
INCLUDE "engine/menus/main_menu.inc"
INCLUDE "mobile/mobile_menu.inc"
