
	add_pic BulbasaurFrontpic
	add_pic BulbasaurBackpic
	add_pic IvysaurFrontpic
	add_pic IvysaurBackpic
	add_pic VenusaurFrontpic
	add_pic VenusaurBackpic
	add_pic CharmanderFrontpic
	add_pic CharmanderBackpic
	add_pic CharmeleonFrontpic
	add_pic CharmeleonBackpic
	add_pic CharizardFrontpic
	add_pic CharizardBackpic
	add_pic SquirtleFrontpic
	add_pic SquirtleBackpic
	add_pic WartortleFrontpic
	add_pic WartortleBackpic
	add_pic BlastoiseFrontpic
	add_pic BlastoiseBackpic
	add_pic CaterpieFrontpic
	add_pic CaterpieBackpic
	add_pic MetapodFrontpic
	add_pic MetapodBackpic
	add_pic ButterfreeFrontpic
	add_pic ButterfreeBackpic
	add_pic WeedleFrontpic
	add_pic WeedleBackpic
	add_pic KakunaFrontpic
	add_pic KakunaBackpic
	add_pic BeedrillFrontpic
	add_pic BeedrillBackpic
	add_pic PidgeyFrontpic
	add_pic PidgeyBackpic
	add_pic PidgeottoFrontpic
	add_pic PidgeottoBackpic
	add_pic PidgeotFrontpic
	add_pic PidgeotBackpic
	add_pic RattataFrontpic
	add_pic RattataBackpic
	add_pic RaticateFrontpic
	add_pic RaticateBackpic
	add_pic SpearowFrontpic
	add_pic SpearowBackpic
	add_pic FearowFrontpic
	add_pic FearowBackpic
	add_pic EkansFrontpic
	add_pic EkansBackpic
	add_pic ArbokFrontpic
	add_pic ArbokBackpic
	add_pic PikachuFrontpic
	add_pic PikachuBackpic
	add_pic RaichuFrontpic
	add_pic RaichuBackpic
	add_pic SandshrewFrontpic
	add_pic SandshrewBackpic
	add_pic SandslashFrontpic
	add_pic SandslashBackpic
	add_pic NidoranFFrontpic
	add_pic NidoranFBackpic
	add_pic NidorinaFrontpic
	add_pic NidorinaBackpic
	add_pic NidoqueenFrontpic
	add_pic NidoqueenBackpic
	add_pic NidoranMFrontpic
	add_pic NidoranMBackpic
	add_pic NidorinoFrontpic
	add_pic NidorinoBackpic
	add_pic NidokingFrontpic
	add_pic NidokingBackpic
	add_pic ClefairyFrontpic
	add_pic ClefairyBackpic
	add_pic ClefableFrontpic
	add_pic ClefableBackpic
	add_pic VulpixFrontpic
	add_pic VulpixBackpic
	add_pic NinetalesFrontpic
	add_pic NinetalesBackpic
	add_pic JigglypuffFrontpic
	add_pic JigglypuffBackpic
	add_pic WigglytuffFrontpic
	add_pic WigglytuffBackpic
	add_pic ZubatFrontpic
	add_pic ZubatBackpic
	add_pic GolbatFrontpic
	add_pic GolbatBackpic
	add_pic OddishFrontpic
	add_pic OddishBackpic
	add_pic GloomFrontpic
	add_pic GloomBackpic
	add_pic VileplumeFrontpic
	add_pic VileplumeBackpic
	add_pic ParasFrontpic
	add_pic ParasBackpic
	add_pic ParasectFrontpic
	add_pic ParasectBackpic
	add_pic VenonatFrontpic
	add_pic VenonatBackpic
	add_pic VenomothFrontpic
	add_pic VenomothBackpic
	add_pic DiglettFrontpic
	add_pic DiglettBackpic
	add_pic DugtrioFrontpic
	add_pic DugtrioBackpic
	add_pic MeowthFrontpic
	add_pic MeowthBackpic
	add_pic PersianFrontpic
	add_pic PersianBackpic
	add_pic PsyduckFrontpic
	add_pic PsyduckBackpic
	add_pic GolduckFrontpic
	add_pic GolduckBackpic
	add_pic MankeyFrontpic
	add_pic MankeyBackpic
	add_pic PrimeapeFrontpic
	add_pic PrimeapeBackpic
	add_pic GrowlitheFrontpic
	add_pic GrowlitheBackpic
	add_pic ArcanineFrontpic
	add_pic ArcanineBackpic
	add_pic PoliwagFrontpic
	add_pic PoliwagBackpic
	add_pic PoliwhirlFrontpic
	add_pic PoliwhirlBackpic
	add_pic PoliwrathFrontpic
	add_pic PoliwrathBackpic
	add_pic AbraFrontpic
	add_pic AbraBackpic
	add_pic KadabraFrontpic
	add_pic KadabraBackpic
	add_pic AlakazamFrontpic
	add_pic AlakazamBackpic
	add_pic MachopFrontpic
	add_pic MachopBackpic
	add_pic MachokeFrontpic
	add_pic MachokeBackpic
	add_pic MachampFrontpic
	add_pic MachampBackpic
	add_pic BellsproutFrontpic
	add_pic BellsproutBackpic
	add_pic WeepinbellFrontpic
	add_pic WeepinbellBackpic
	add_pic VictreebelFrontpic
	add_pic VictreebelBackpic
	add_pic TentacoolFrontpic
	add_pic TentacoolBackpic
	add_pic TentacruelFrontpic
	add_pic TentacruelBackpic
	add_pic GeodudeFrontpic
	add_pic GeodudeBackpic
	add_pic GravelerFrontpic
	add_pic GravelerBackpic
	add_pic GolemFrontpic
	add_pic GolemBackpic
	add_pic PonytaFrontpic
	add_pic PonytaBackpic
	add_pic RapidashFrontpic
	add_pic RapidashBackpic
	add_pic SlowpokeFrontpic
	add_pic SlowpokeBackpic
	add_pic SlowbroFrontpic
	add_pic SlowbroBackpic
	add_pic MagnemiteFrontpic
	add_pic MagnemiteBackpic
	add_pic MagnetonFrontpic
	add_pic MagnetonBackpic
	add_pic FarfetchDFrontpic
	add_pic FarfetchDBackpic
	add_pic DoduoFrontpic
	add_pic DoduoBackpic
	add_pic DodrioFrontpic
	add_pic DodrioBackpic
	add_pic SeelFrontpic
	add_pic SeelBackpic
	add_pic DewgongFrontpic
	add_pic DewgongBackpic
	add_pic GrimerFrontpic
	add_pic GrimerBackpic
	add_pic MukFrontpic
	add_pic MukBackpic
	add_pic ShellderFrontpic
	add_pic ShellderBackpic
	add_pic CloysterFrontpic
	add_pic CloysterBackpic
	add_pic GastlyFrontpic
	add_pic GastlyBackpic
	add_pic HaunterFrontpic
	add_pic HaunterBackpic
	add_pic GengarFrontpic
	add_pic GengarBackpic
	add_pic OnixFrontpic
	add_pic OnixBackpic
	add_pic DrowzeeFrontpic
	add_pic DrowzeeBackpic
	add_pic HypnoFrontpic
	add_pic HypnoBackpic
	add_pic KrabbyFrontpic
	add_pic KrabbyBackpic
	add_pic KinglerFrontpic
	add_pic KinglerBackpic
	add_pic VoltorbFrontpic
	add_pic VoltorbBackpic
	add_pic ElectrodeFrontpic
	add_pic ElectrodeBackpic
	add_pic ExeggcuteFrontpic
	add_pic ExeggcuteBackpic
	add_pic ExeggutorFrontpic
	add_pic ExeggutorBackpic
	add_pic CuboneFrontpic
	add_pic CuboneBackpic
	add_pic MarowakFrontpic
	add_pic MarowakBackpic
	add_pic HitmonleeFrontpic
	add_pic HitmonleeBackpic
	add_pic HitmonchanFrontpic
	add_pic HitmonchanBackpic
	add_pic LickitungFrontpic
	add_pic LickitungBackpic
	add_pic KoffingFrontpic
	add_pic KoffingBackpic
	add_pic WeezingFrontpic
	add_pic WeezingBackpic
	add_pic RhyhornFrontpic
	add_pic RhyhornBackpic
	add_pic RhydonFrontpic
	add_pic RhydonBackpic
	add_pic ChanseyFrontpic
	add_pic ChanseyBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic KangaskhanFrontpic
	add_pic KangaskhanBackpic
	add_pic HorseaFrontpic
	add_pic HorseaBackpic
	add_pic SeadraFrontpic
	add_pic SeadraBackpic
	add_pic GoldeenFrontpic
	add_pic GoldeenBackpic
	add_pic SeakingFrontpic
	add_pic SeakingBackpic
	add_pic StaryuFrontpic
	add_pic StaryuBackpic
	add_pic StarmieFrontpic
	add_pic StarmieBackpic
	add_pic MrMimeFrontpic
	add_pic MrMimeBackpic
	add_pic ScytherFrontpic
	add_pic ScytherBackpic
	add_pic JynxFrontpic
	add_pic JynxBackpic
	add_pic ElectabuzzFrontpic
	add_pic ElectabuzzBackpic
	add_pic MagmarFrontpic
	add_pic MagmarBackpic
	add_pic PinsirFrontpic
	add_pic PinsirBackpic
	add_pic TaurosFrontpic
	add_pic TaurosBackpic
	add_pic MagikarpFrontpic
	add_pic MagikarpBackpic
	add_pic GyaradosFrontpic
	add_pic GyaradosBackpic
	add_pic LaprasFrontpic
	add_pic LaprasBackpic
	add_pic DittoFrontpic
	add_pic DittoBackpic
	add_pic EeveeFrontpic
	add_pic EeveeBackpic
	add_pic VaporeonFrontpic
	add_pic VaporeonBackpic
	add_pic JolteonFrontpic
	add_pic JolteonBackpic
	add_pic FlareonFrontpic
	add_pic FlareonBackpic
	add_pic PorygonFrontpic
	add_pic PorygonBackpic
	add_pic OmanyteFrontpic
	add_pic OmanyteBackpic
	add_pic OmastarFrontpic
	add_pic OmastarBackpic
	add_pic KabutoFrontpic
	add_pic KabutoBackpic
	add_pic KabutopsFrontpic
	add_pic KabutopsBackpic
	add_pic AerodactylFrontpic
	add_pic AerodactylBackpic
	add_pic SnorlaxFrontpic
	add_pic SnorlaxBackpic
	add_pic ArticunoFrontpic
	add_pic ArticunoBackpic
	add_pic ZapdosFrontpic
	add_pic ZapdosBackpic
	add_pic MoltresFrontpic
	add_pic MoltresBackpic
	add_pic DratiniFrontpic
	add_pic DratiniBackpic
	add_pic DragonairFrontpic
	add_pic DragonairBackpic
	add_pic DragoniteFrontpic
	add_pic DragoniteBackpic
	add_pic MewtwoFrontpic
	add_pic MewtwoBackpic
	add_pic MewFrontpic
	add_pic MewBackpic
	add_pic ChikoritaFrontpic
	add_pic ChikoritaBackpic
	add_pic BayleefFrontpic
	add_pic BayleefBackpic
	add_pic MeganiumFrontpic
	add_pic MeganiumBackpic
	add_pic CyndaquilFrontpic
	add_pic CyndaquilBackpic
	add_pic QuilavaFrontpic
	add_pic QuilavaBackpic
	add_pic TyphlosionFrontpic
	add_pic TyphlosionBackpic
	add_pic TotodileFrontpic
	add_pic TotodileBackpic
	add_pic CroconawFrontpic
	add_pic CroconawBackpic
	add_pic FeraligatrFrontpic
	add_pic FeraligatrBackpic
	add_pic SentretFrontpic
	add_pic SentretBackpic
	add_pic FurretFrontpic
	add_pic FurretBackpic
	add_pic HoothootFrontpic
	add_pic HoothootBackpic
	add_pic NoctowlFrontpic
	add_pic NoctowlBackpic
	add_pic LedybaFrontpic
	add_pic LedybaBackpic
	add_pic LedianFrontpic
	add_pic LedianBackpic
	add_pic SpinarakFrontpic
	add_pic SpinarakBackpic
	add_pic AriadosFrontpic
	add_pic AriadosBackpic
	add_pic CrobatFrontpic
	add_pic CrobatBackpic
	add_pic ChinchouFrontpic
	add_pic ChinchouBackpic
	add_pic LanturnFrontpic
	add_pic LanturnBackpic
	add_pic PichuFrontpic
	add_pic PichuBackpic
	add_pic CleffaFrontpic
	add_pic CleffaBackpic
	add_pic IgglybuffFrontpic
	add_pic IgglybuffBackpic
	add_pic TogepiFrontpic
	add_pic TogepiBackpic
	add_pic TogeticFrontpic
	add_pic TogeticBackpic
	add_pic NatuFrontpic
	add_pic NatuBackpic
	add_pic XatuFrontpic
	add_pic XatuBackpic
	add_pic MareepFrontpic
	add_pic MareepBackpic
	add_pic FlaaffyFrontpic
	add_pic FlaaffyBackpic
	add_pic AmpharosFrontpic
	add_pic AmpharosBackpic
	add_pic BellossomFrontpic
	add_pic BellossomBackpic
	add_pic MarillFrontpic
	add_pic MarillBackpic
	add_pic AzumarillFrontpic
	add_pic AzumarillBackpic
	add_pic SudowoodoFrontpic
	add_pic SudowoodoBackpic
	add_pic PolitoedFrontpic
	add_pic PolitoedBackpic
	add_pic HoppipFrontpic
	add_pic HoppipBackpic
	add_pic SkiploomFrontpic
	add_pic SkiploomBackpic
	add_pic JumpluffFrontpic
	add_pic JumpluffBackpic
	add_pic AipomFrontpic
	add_pic AipomBackpic
	add_pic SunkernFrontpic
	add_pic SunkernBackpic
	add_pic SunfloraFrontpic
	add_pic SunfloraBackpic
	add_pic YanmaFrontpic
	add_pic YanmaBackpic
	add_pic WooperFrontpic
	add_pic WooperBackpic
	add_pic QuagsireFrontpic
	add_pic QuagsireBackpic
	add_pic EspeonFrontpic
	add_pic EspeonBackpic
	add_pic UmbreonFrontpic
	add_pic UmbreonBackpic
	add_pic MurkrowFrontpic
	add_pic MurkrowBackpic
	add_pic SlowkingFrontpic
	add_pic SlowkingBackpic
	add_pic MisdreavusFrontpic
	add_pic MisdreavusBackpic

	; Unown pics have their own table. See UnownPicPointers
	dbw -1, -1
	dbw -1, -1

	add_pic WobbuffetFrontpic
	add_pic WobbuffetBackpic
	add_pic GirafarigFrontpic
	add_pic GirafarigBackpic
	add_pic PinecoFrontpic
	add_pic PinecoBackpic
	add_pic ForretressFrontpic
	add_pic ForretressBackpic
	add_pic DunsparceFrontpic
	add_pic DunsparceBackpic
	add_pic GligarFrontpic
	add_pic GligarBackpic
	add_pic SteelixFrontpic
	add_pic SteelixBackpic
	add_pic SnubbullFrontpic
	add_pic SnubbullBackpic
	add_pic GranbullFrontpic
	add_pic GranbullBackpic
	add_pic QwilfishFrontpic
	add_pic QwilfishBackpic
	add_pic ScizorFrontpic
	add_pic ScizorBackpic
	add_pic ShuckleFrontpic
	add_pic ShuckleBackpic
	add_pic HeracrossFrontpic
	add_pic HeracrossBackpic
	add_pic SneaselFrontpic
	add_pic SneaselBackpic
	add_pic TeddiursaFrontpic
	add_pic TeddiursaBackpic
	add_pic UrsaringFrontpic
	add_pic UrsaringBackpic
	add_pic SlugmaFrontpic
	add_pic SlugmaBackpic
	add_pic MagcargoFrontpic
	add_pic MagcargoBackpic
	add_pic SwinubFrontpic
	add_pic SwinubBackpic
	add_pic PiloswineFrontpic
	add_pic PiloswineBackpic
	add_pic CorsolaFrontpic
	add_pic CorsolaBackpic
	add_pic RemoraidFrontpic
	add_pic RemoraidBackpic
	add_pic OctilleryFrontpic
	add_pic OctilleryBackpic
	add_pic DelibirdFrontpic
	add_pic DelibirdBackpic
	add_pic MantineFrontpic
	add_pic MantineBackpic
	add_pic SkarmoryFrontpic
	add_pic SkarmoryBackpic
	add_pic HoundourFrontpic
	add_pic HoundourBackpic
	add_pic HoundoomFrontpic
	add_pic HoundoomBackpic
	add_pic KingdraFrontpic
	add_pic KingdraBackpic
	add_pic PhanpyFrontpic
	add_pic PhanpyBackpic
	add_pic DonphanFrontpic
	add_pic DonphanBackpic
	add_pic Porygon2Frontpic
	add_pic Porygon2Backpic
	add_pic StantlerFrontpic
	add_pic StantlerBackpic
	add_pic SmeargleFrontpic
	add_pic SmeargleBackpic
	add_pic TyrogueFrontpic
	add_pic TyrogueBackpic
	add_pic HitmontopFrontpic
	add_pic HitmontopBackpic
	add_pic SmoochumFrontpic
	add_pic SmoochumBackpic
	add_pic ElekidFrontpic
	add_pic ElekidBackpic
	add_pic MagbyFrontpic
	add_pic MagbyBackpic
	add_pic MiltankFrontpic
	add_pic MiltankBackpic
	add_pic BlisseyFrontpic
	add_pic BlisseyBackpic
	add_pic RaikouFrontpic
	add_pic RaikouBackpic
	add_pic EnteiFrontpic
	add_pic EnteiBackpic
	add_pic SuicuneFrontpic
	add_pic SuicuneBackpic
	add_pic LarvitarFrontpic
	add_pic LarvitarBackpic
	add_pic PupitarFrontpic
	add_pic PupitarBackpic
	add_pic TyranitarFrontpic
	add_pic TyranitarBackpic
	add_pic LugiaFrontpic
	add_pic LugiaBackpic
	add_pic HoOhFrontpic
	add_pic HoOhBackpic
	add_pic CelebiFrontpic
	add_pic CelebiBackpic
	dbw -1, -1 ; unused
	dbw -1, -1 ; unused
	add_pic EggPic
	dbw -1, -1 ; unused
