
	dbw BANK(FalknerPic)          - $36, FalknerPic
	dbw BANK(WhitneyPic)          - $36, WhitneyPic
	dbw BANK(BugsyPic)            - $36, BugsyPic
	dbw BANK(MortyPic)            - $36, MortyPic
	dbw BANK(PrycePic)            - $36, PrycePic
	dbw BANK(JasminePic)          - $36, JasminePic
	dbw BANK(ChuckPic)            - $36, ChuckPic
	dbw BANK(ClairPic)            - $36, ClairPic
	dbw BANK(Rival1Pic)           - $36, Rival1Pic
	dbw BANK(PokemonProfPic)      - $36, PokemonProfPic
	dbw BANK(WillPic)             - $36, WillPic
	dbw BANK(CalPic)              - $36, CalPic
	dbw BANK(BrunoPic)            - $36, BrunoPic
	dbw BANK(KarenPic)            - $36, KarenPic
	dbw BANK(KogaPic)             - $36, KogaPic
	dbw BANK(ChampionPic)         - $36, ChampionPic
	dbw BANK(BrockPic)            - $36, BrockPic
	dbw BANK(MistyPic)            - $36, MistyPic
	dbw BANK(LtSurgePic)          - $36, LtSurgePic
	dbw BANK(ScientistPic)        - $36, ScientistPic
	dbw BANK(ErikaPic)            - $36, ErikaPic
	dbw BANK(YoungsterPic)        - $36, YoungsterPic
	dbw BANK(SchoolboyPic)        - $36, SchoolboyPic
	dbw BANK(BirdKeeperPic)       - $36, BirdKeeperPic
	dbw BANK(LassPic)             - $36, LassPic
	dbw BANK(JaninePic)           - $36, JaninePic
	dbw BANK(CooltrainermPic)     - $36, CooltrainermPic
	dbw BANK(CooltrainerfPic)     - $36, CooltrainerfPic
	dbw BANK(BeautyPic)           - $36, BeautyPic
	dbw BANK(PokemaniacPic)       - $36, PokemaniacPic
	dbw BANK(GruntmPic)           - $36, GruntmPic
	dbw BANK(GentlemanPic)        - $36, GentlemanPic
	dbw BANK(SkierPic)            - $36, SkierPic
	dbw BANK(TeacherPic)          - $36, TeacherPic
	dbw BANK(SabrinaPic)          - $36, SabrinaPic
	dbw BANK(BugCatcherPic)       - $36, BugCatcherPic
	dbw BANK(FisherPic)           - $36, FisherPic
	dbw BANK(SwimmermPic)         - $36, SwimmermPic
	dbw BANK(SwimmerfPic)         - $36, SwimmerfPic
	dbw BANK(SailorPic)           - $36, SailorPic
	dbw BANK(SuperNerdPic)        - $36, SuperNerdPic
	dbw BANK(Rival2Pic)           - $36, Rival2Pic
	dbw BANK(GuitaristPic)        - $36, GuitaristPic
	dbw BANK(HikerPic)            - $36, HikerPic
	dbw BANK(BikerPic)            - $36, BikerPic
	dbw BANK(BlainePic)           - $36, BlainePic
	dbw BANK(BurglarPic)          - $36, BurglarPic
	dbw BANK(FirebreatherPic)     - $36, FirebreatherPic
	dbw BANK(JugglerPic)          - $36, JugglerPic
	dbw BANK(BlackbeltTPic)       - $36, BlackbeltTPic
	dbw BANK(ExecutivemPic)       - $36, ExecutivemPic
	dbw BANK(PsychicTPic)         - $36, PsychicTPic
	dbw BANK(PicnickerPic)        - $36, PicnickerPic
	dbw BANK(CamperPic)           - $36, CamperPic
	dbw BANK(ExecutivefPic)       - $36, ExecutivefPic
	dbw BANK(SagePic)             - $36, SagePic
	dbw BANK(MediumPic)           - $36, MediumPic
	dbw BANK(BoarderPic)          - $36, BoarderPic
	dbw BANK(PokefanmPic)         - $36, PokefanmPic
	dbw BANK(KimonoGirlPic)       - $36, KimonoGirlPic
	dbw BANK(TwinsPic)            - $36, TwinsPic
	dbw BANK(PokefanfPic)         - $36, PokefanfPic
	dbw BANK(RedPic)              - $36, RedPic
	dbw BANK(BluePic)             - $36, BluePic
	dbw BANK(OfficerPic)          - $36, OfficerPic
	dbw BANK(GruntfPic)           - $36, GruntfPic
	dbw BANK(MysticalmanPic)      - $36, MysticalmanPic
