	tilepal 0, GRAY, RED, WATER, WATER, GRAY, GRAY, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, RED, WATER, WATER, GRAY, GRAY, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, RED, RED, RED, RED, WATER, GRAY, GRAY
	tilepal 0, WATER, WATER, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, RED, RED, RED, RED, WATER, GRAY, WATER
	tilepal 0, GRAY, GRAY, BROWN, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, BROWN, RED, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, WATER, WATER, WATER, RED, RED, RED, RED, WATER
	tilepal 0, BROWN, YELLOW, RED, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, WATER, RED, RED, RED, RED, GRAY, RED, WATER

rept 16
	db $ff
endr

	tilepal 1, GRAY, WATER, GRAY, WATER, WATER, WATER, ROOF, ROOF
	tilepal 1, YELLOW, YELLOW, GRAY, GRAY, WATER, WATER, RED, RED
	tilepal 1, GRAY, RED, RED, WATER, WATER, WATER, WATER, WATER
	tilepal 1, RED, GRAY, GRAY, GRAY, GREEN, YELLOW, RED, RED
	tilepal 1, GRAY, GRAY, RED, RED, WATER, WATER, GRAY, GRAY
	tilepal 1, YELLOW, YELLOW, BROWN, YELLOW, WATER, WATER, YELLOW, RED
	tilepal 1, GRAY, GRAY, RED, RED, GRAY, WATER, WATER, WATER
	tilepal 1, GRAY, GRAY, BROWN, YELLOW, RED, RED, YELLOW, RED
	tilepal 1, GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal 1, GRAY, GRAY, YELLOW, BROWN, WATER, WATER, GRAY, BROWN
	tilepal 1, RED, RED, RED, RED, RED, RED, GRAY, GRAY
	tilepal 1, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
