	tilepal 0, GRAY, GRAY, WATER, WATER, RED, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, WATER, GRAY, WATER, WATER, RED, BROWN, BROWN, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, BROWN, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, RED, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, WATER
	tilepal 1, GRAY, ROOF, RED, GRAY, GRAY, WATER, GRAY, GRAY
	tilepal 1, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, RED, WATER, WATER, WATER
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY
