	tilepal 0, GRAY, WATER, WATER, WATER, BROWN, WATER, WATER, RED
	tilepal 0, RED, ROOF, ROOF, BROWN, ROOF, RED, RED, RED
	tilepal 0, ROOF, WATER, ROOF, BROWN, ROOF, WATER, WATER, RED
	tilepal 0, RED, ROOF, ROOF, WATER, ROOF, RED, RED, RED
	tilepal 0, ROOF, ROOF, WATER, BROWN, RED, WATER, WATER, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, ROOF, ROOF, GRAY, GRAY
	tilepal 0, ROOF, ROOF, WATER, WATER, RED, ROOF, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, ROOF, BROWN, WATER
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, RED, GRAY, GRAY, GREEN, GREEN, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, RED, RED, GREEN, GREEN, ROOF, ROOF, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, ROOF, GRAY, GRAY, BROWN, BROWN, RED
	tilepal 1, RED, RED, RED, BROWN, RED, RED, RED, RED
	tilepal 1, ROOF, WATER, ROOF, BROWN, RED, WATER, WATER, RED
	tilepal 1, RED, RED, RED, WATER, RED, RED, RED, RED
	tilepal 1, ROOF, ROOF, WATER, BROWN, RED, WATER, WATER, GRAY
	tilepal 1, GRAY, GRAY, GRAY, BROWN, RED, ROOF, GRAY, GRAY
	tilepal 1, ROOF, ROOF, WATER, WATER, RED, RED, BROWN, GRAY
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, ROOF, BROWN, WATER
	tilepal 1, RED, RED, ROOF, ROOF, BROWN, BROWN, GRAY, GRAY
	tilepal 1, RED, RED, GRAY, GRAY, GREEN, GREEN, ROOF, ROOF
	tilepal 1, RED, RED, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 1, RED, RED, GREEN, GREEN, ROOF, ROOF, GRAY, GRAY
