; f2787
;                               index,          pitch, length
BulbasaurCryHeader:   cry_header CRY_BULBASAUR,   $080,  $081
IvysaurCryHeader:     cry_header CRY_BULBASAUR,   $020,  $100
VenusaurCryHeader:    cry_header CRY_BULBASAUR,   $000,  $140
CharmanderCryHeader:  cry_header CRY_CHARMANDER,  $060,  $0c0
CharmeleonCryHeader:  cry_header CRY_CHARMANDER,  $020,  $0c0
CharizardCryHeader:   cry_header CRY_CHARMANDER,  $000,  $100
SquirtleCryHeader:    cry_header CRY_SQUIRTLE,    $060,  $0c0
WartortleCryHeader:   cry_header CRY_SQUIRTLE,    $020,  $0c0
BlastoiseCryHeader:   cry_header CRY_BLASTOISE,   $000,  $100
CaterpieCryHeader:    cry_header CRY_CATERPIE,    $080,  $0a0
MetapodCryHeader:     cry_header CRY_METAPOD,     $0cc,  $081
ButterfreeCryHeader:  cry_header CRY_CATERPIE,    $077,  $0c0
WeedleCryHeader:      cry_header CRY_WEEDLE,      $0ee,  $081
KakunaCryHeader:      cry_header CRY_BLASTOISE,   $0ff,  $081
BeedrillCryHeader:    cry_header CRY_BLASTOISE,   $060,  $100
PidgeyCryHeader:      cry_header CRY_PIDGEY,      $0df,  $084
PidgeottoCryHeader:   cry_header CRY_PIDGEOTTO,   $028,  $140
PidgeotCryHeader:     cry_header CRY_PIDGEOTTO,   $011,  $17f
RattataCryHeader:     cry_header CRY_RATTATA,     $000,  $100
RaticateCryHeader:    cry_header CRY_RATTATA,     $020,  $17f
SpearowCryHeader:     cry_header CRY_SPEAROW,     $000,  $100
FearowCryHeader:      cry_header CRY_FEAROW,      $040,  $120
EkansCryHeader:       cry_header CRY_EKANS,       $012,  $0c0
ArbokCryHeader:       cry_header CRY_EKANS,       $0e0,  $090
PikachuCryHeader:     cry_header CRY_BULBASAUR,   $0ee,  $081
RaichuCryHeader:      cry_header CRY_RAICHU,      $0ee,  $088
SandshrewCryHeader:   cry_header CRY_NIDORAN_M,   $020,  $0c0
SandslashCryHeader:   cry_header CRY_NIDORAN_M,   $0ff,  $17f
NidoranFCryHeader:    cry_header CRY_NIDORAN_F,   $000,  $100
NidorinaCryHeader:    cry_header CRY_NIDORAN_F,   $02c,  $160
NidoqueenCryHeader:   cry_header CRY_NIDOQUEEN,   $000,  $100
NidoranMCryHeader:    cry_header CRY_NIDORAN_M,   $000,  $100
NidorinoCryHeader:    cry_header CRY_NIDORAN_M,   $02c,  $140
NidokingCryHeader:    cry_header CRY_RAICHU,      $000,  $100
ClefairyCryHeader:    cry_header CRY_CLEFAIRY,    $0cc,  $081
ClefableCryHeader:    cry_header CRY_CLEFAIRY,    $0aa,  $0a0
VulpixCryHeader:      cry_header CRY_VULPIX,      $04f,  $090
NinetalesCryHeader:   cry_header CRY_VULPIX,      $088,  $0e0
JigglypuffCryHeader:  cry_header CRY_PIDGEY,      $0ff,  $0b5
WigglytuffCryHeader:  cry_header CRY_PIDGEY,      $068,  $0e0
ZubatCryHeader:       cry_header CRY_SQUIRTLE,    $0e0,  $100
GolbatCryHeader:      cry_header CRY_SQUIRTLE,    $0fa,  $100
OddishCryHeader:      cry_header CRY_ODDISH,      $0dd,  $081
GloomCryHeader:       cry_header CRY_ODDISH,      $0aa,  $0c0
VileplumeCryHeader:   cry_header CRY_VILEPLUME,   $022,  $17f
ParasCryHeader:       cry_header CRY_PARAS,       $020,  $160
ParasectCryHeader:    cry_header CRY_PARAS,       $042,  $17f
VenonatCryHeader:     cry_header CRY_VENONAT,     $044,  $0c0
VenomothCryHeader:    cry_header CRY_VENONAT,     $029,  $100
DiglettCryHeader:     cry_header CRY_DIGLETT,     $0aa,  $081
DugtrioCryHeader:     cry_header CRY_DIGLETT,     $02a,  $090
MeowthCryHeader:      cry_header CRY_CLEFAIRY,    $077,  $090
PersianCryHeader:     cry_header CRY_CLEFAIRY,    $099,  $17f
PsyduckCryHeader:     cry_header CRY_PSYDUCK,     $020,  $0e0
GolduckCryHeader:     cry_header CRY_PSYDUCK,     $0ff,  $0c0
MankeyCryHeader:      cry_header CRY_NIDOQUEEN,   $0dd,  $0e0
PrimeapeCryHeader:    cry_header CRY_NIDOQUEEN,   $0af,  $0c0
GrowlitheCryHeader:   cry_header CRY_GROWLITHE,   $020,  $0c0
ArcanineCryHeader:    cry_header CRY_WEEDLE,      $000,  $100
PoliwagCryHeader:     cry_header CRY_PIDGEY,      $0ff,  $17f
PoliwhirlCryHeader:   cry_header CRY_PIDGEY,      $077,  $0e0
PoliwrathCryHeader:   cry_header CRY_PIDGEY,      $000,  $17f
AbraCryHeader:        cry_header CRY_METAPOD,     $0c0,  $081
KadabraCryHeader:     cry_header CRY_METAPOD,     $0a8,  $140
AlakazamCryHeader:    cry_header CRY_METAPOD,     $098,  $17f
MachopCryHeader:      cry_header CRY_GROWLITHE,   $0ee,  $081
MachokeCryHeader:     cry_header CRY_GROWLITHE,   $048,  $0e0
MachampCryHeader:     cry_header CRY_GROWLITHE,   $008,  $140
BellsproutCryHeader:  cry_header CRY_PSYDUCK,     $055,  $081
WeepinbellCryHeader:  cry_header CRY_WEEPINBELL,  $044,  $0a0
VictreebelCryHeader:  cry_header CRY_WEEPINBELL,  $066,  $14c
TentacoolCryHeader:   cry_header CRY_VENONAT,     $000,  $100
TentacruelCryHeader:  cry_header CRY_VENONAT,     $0ee,  $17f
GeodudeCryHeader:     cry_header CRY_VULPIX,      $0f0,  $090
GravelerCryHeader:    cry_header CRY_VULPIX,      $000,  $100
GolemCryHeader:       cry_header CRY_GOLEM,       $0e0,  $0c0
PonytaCryHeader:      cry_header CRY_WEEPINBELL,  $000,  $100
RapidashCryHeader:    cry_header CRY_WEEPINBELL,  $020,  $140
SlowpokeCryHeader:    cry_header CRY_SLOWPOKE,    $000,  $100
SlowbroCryHeader:     cry_header CRY_GROWLITHE,   $000,  $100
MagnemiteCryHeader:   cry_header CRY_METAPOD,     $080,  $0e0
MagnetonCryHeader:    cry_header CRY_METAPOD,     $020,  $140
FarfetchDCryHeader:   cry_header CRY_SPEAROW,     $0dd,  $081
DoduoCryHeader:       cry_header CRY_DIGLETT,     $0bb,  $081
DodrioCryHeader:      cry_header CRY_DIGLETT,     $099,  $0a0
SeelCryHeader:        cry_header CRY_SEEL,        $088,  $140
DewgongCryHeader:     cry_header CRY_SEEL,        $023,  $17f
GrimerCryHeader:      cry_header CRY_GRIMER,      $000,  $100
MukCryHeader:         cry_header CRY_MUK,         $0ef,  $17f
ShellderCryHeader:    cry_header CRY_FEAROW,      $000,  $100
CloysterCryHeader:    cry_header CRY_FEAROW,      $06f,  $160
GastlyCryHeader:      cry_header CRY_METAPOD,     $000,  $100
HaunterCryHeader:     cry_header CRY_METAPOD,     $030,  $0c0
GengarCryHeader:      cry_header CRY_MUK,         $000,  $17f
OnixCryHeader:        cry_header CRY_EKANS,       $0ff,  $140
DrowzeeCryHeader:     cry_header CRY_DROWZEE,     $088,  $0a0
HypnoCryHeader:       cry_header CRY_DROWZEE,     $0ee,  $0c0
KrabbyCryHeader:      cry_header CRY_KRABBY,      $020,  $160
KinglerCryHeader:     cry_header CRY_KRABBY,      $0ee,  $160
VoltorbCryHeader:     cry_header CRY_VOLTORB,     $0ed,  $100
ElectrodeCryHeader:   cry_header CRY_VOLTORB,     $0a8,  $110
ExeggcuteCryHeader:   cry_header CRY_DIGLETT,     $000,  $100
ExeggutorCryHeader:   cry_header CRY_DROWZEE,     $000,  $100
CuboneCryHeader:      cry_header CRY_CLEFAIRY,    $000,  $100
MarowakCryHeader:     cry_header CRY_ODDISH,      $04f,  $0e0
HitmonleeCryHeader:   cry_header CRY_GOLEM,       $080,  $140
HitmonchanCryHeader:  cry_header CRY_SEEL,        $0ee,  $140
LickitungCryHeader:   cry_header CRY_SEEL,        $000,  $100
KoffingCryHeader:     cry_header CRY_GOLEM,       $0e6,  $15d
WeezingCryHeader:     cry_header CRY_GOLEM,       $0ff,  $17f
RhyhornCryHeader:     cry_header CRY_CHARMANDER,  $000,  $100
RhydonCryHeader:      cry_header CRY_RHYDON,      $000,  $100
ChanseyCryHeader:     cry_header CRY_PIDGEOTTO,   $00a,  $140
TangelaCryHeader:     cry_header CRY_GOLEM,       $000,  $100
KangaskhanCryHeader:  cry_header CRY_KANGASKHAN,  $000,  $100
HorseaCryHeader:      cry_header CRY_CLEFAIRY,    $099,  $090
SeadraCryHeader:      cry_header CRY_CLEFAIRY,    $03c,  $081
GoldeenCryHeader:     cry_header CRY_CATERPIE,    $080,  $0c0
SeakingCryHeader:     cry_header CRY_CATERPIE,    $010,  $17f
StaryuCryHeader:      cry_header CRY_PARAS,       $002,  $0a0
StarmieCryHeader:     cry_header CRY_PARAS,       $000,  $100
MrMimeCryHeader:      cry_header CRY_KRABBY,      $008,  $0c0
ScytherCryHeader:     cry_header CRY_CATERPIE,    $000,  $100
JynxCryHeader:        cry_header CRY_DROWZEE,     $0ff,  $17f
ElectabuzzCryHeader:  cry_header CRY_VOLTORB,     $08f,  $17f
MagmarCryHeader:      cry_header CRY_CHARMANDER,  $0ff,  $0b0
PinsirCryHeader:      cry_header CRY_PIDGEOTTO,   $000,  $100
TaurosCryHeader:      cry_header CRY_SQUIRTLE,    $011,  $0c0
MagikarpCryHeader:    cry_header CRY_EKANS,       $080,  $080
GyaradosCryHeader:    cry_header CRY_EKANS,       $000,  $100
LaprasCryHeader:      cry_header CRY_LAPRAS,      $000,  $100
DittoCryHeader:       cry_header CRY_PIDGEY,      $0ff,  $17f
EeveeCryHeader:       cry_header CRY_VENONAT,     $088,  $0e0
VaporeonCryHeader:    cry_header CRY_VENONAT,     $0aa,  $17f
JolteonCryHeader:     cry_header CRY_VENONAT,     $03d,  $100
FlareonCryHeader:     cry_header CRY_VENONAT,     $010,  $0a0
PorygonCryHeader:     cry_header CRY_WEEPINBELL,  $0aa,  $17f
OmanyteCryHeader:     cry_header CRY_GROWLITHE,   $0f0,  $081
OmastarCryHeader:     cry_header CRY_GROWLITHE,   $0ff,  $0c0
KabutoCryHeader:      cry_header CRY_CATERPIE,    $0bb,  $0c0
KabutopsCryHeader:    cry_header CRY_FEAROW,      $0ee,  $081
AerodactylCryHeader:  cry_header CRY_VILEPLUME,   $020,  $170
SnorlaxCryHeader:     cry_header CRY_GRIMER,      $055,  $081
ArticunoCryHeader:    cry_header CRY_RAICHU,      $080,  $0c0
ZapdosCryHeader:      cry_header CRY_FEAROW,      $0ff,  $100
MoltresCryHeader:     cry_header CRY_RAICHU,      $0f8,  $0c0
DratiniCryHeader:     cry_header CRY_BULBASAUR,   $060,  $0c0
DragonairCryHeader:   cry_header CRY_BULBASAUR,   $040,  $100
DragoniteCryHeader:   cry_header CRY_BULBASAUR,   $03c,  $140
MewtwoCryHeader:      cry_header CRY_PARAS,       $099,  $17f
MewCryHeader:         cry_header CRY_PARAS,       $0ee,  $17f
ChikoritaCryHeader:   cry_header CRY_CHIKORITA,  -$010,  $0b0
BayleefCryHeader:     cry_header CRY_CHIKORITA,  -$022,  $120
MeganiumCryHeader:    cry_header CRY_CHIKORITA,  -$0b7,  $200
CyndaquilCryHeader:   cry_header CRY_CYNDAQUIL,   $347,  $080
QuilavaCryHeader:     cry_header CRY_CYNDAQUIL,   $321,  $120
TyphlosionCryHeader:  cry_header CRY_TYPHLOSION,  $f00,  $0d4
TotodileCryHeader:    cry_header CRY_TOTODILE,    $46c,  $0e8
CroconawCryHeader:    cry_header CRY_TOTODILE,    $440,  $110
FeraligatrCryHeader:  cry_header CRY_TOTODILE,    $3fc,  $180
SentretCryHeader:     cry_header CRY_SENTRET,     $08a,  $0b8
FurretCryHeader:      cry_header CRY_SENTRET,     $06b,  $102
HoothootCryHeader:    cry_header CRY_HOOTHOOT,    $091,  $0d8
NoctowlCryHeader:     cry_header CRY_HOOTHOOT,    $000,  $1a0
LedybaCryHeader:      cry_header CRY_LEDYBA,      $000,  $0de
LedianCryHeader:      cry_header CRY_LEDYBA,     -$096,  $138
SpinarakCryHeader:    cry_header CRY_SPINARAK,    $011,  $200
AriadosCryHeader:     cry_header CRY_SPINARAK,   -$0ae,  $1e2
CrobatCryHeader:      cry_header CRY_SQUIRTLE,   -$010,  $140
ChinchouCryHeader:    cry_header CRY_CYNDAQUIL,   $3c9,  $140
LanturnCryHeader:     cry_header CRY_CYNDAQUIL,   $2d0,  $110
PichuCryHeader:       cry_header CRY_PICHU,       $000,  $140
CleffaCryHeader:      cry_header CRY_CLEFFA,      $061,  $091
IgglybuffCryHeader:   cry_header CRY_CHIKORITA,   $0e8,  $0e8
TogepiCryHeader:      cry_header CRY_TOGEPI,      $010,  $100
TogeticCryHeader:     cry_header CRY_TOGETIC,     $03b,  $038
NatuCryHeader:        cry_header CRY_NATU,       -$067,  $100
XatuCryHeader:        cry_header CRY_NATU,       -$0a7,  $168
MareepCryHeader:      cry_header CRY_MAREEP,      $022,  $0d8
FlaaffyCryHeader:     cry_header CRY_MAREEP,     -$007,  $180
AmpharosCryHeader:    cry_header CRY_AMPHAROS,   -$07c,  $0e8
BellossomCryHeader:   cry_header CRY_CLEFFA,      $084,  $150
MarillCryHeader:      cry_header CRY_MARILL,      $11b,  $120
AzumarillCryHeader:   cry_header CRY_MARILL,      $0b6,  $180
SudowoodoCryHeader:   cry_header CRY_CLEFFA,      $f40,  $180
PolitoedCryHeader:    cry_header CRY_CLEFFA,     -$2a3,  $1c8
HoppipCryHeader:      cry_header CRY_CLEFFA,      $03b,  $0c8
SkiploomCryHeader:    cry_header CRY_CLEFFA,      $027,  $138
JumpluffCryHeader:    cry_header CRY_CLEFFA,      $000,  $180
AipomCryHeader:       cry_header CRY_AIPOM,      -$051,  $0e8
SunkernCryHeader:     cry_header CRY_MARILL,      $12b,  $0b8
SunfloraCryHeader:    cry_header CRY_SUNFLORA,   -$020,  $180
YanmaCryHeader:       cry_header CRY_TOTODILE,    $031,  $0c8
WooperCryHeader:      cry_header CRY_WOOPER,      $093,  $0af
QuagsireCryHeader:    cry_header CRY_WOOPER,     -$0c6,  $140
EspeonCryHeader:      cry_header CRY_AIPOM,       $0a2,  $140
UmbreonCryHeader:     cry_header CRY_VENONAT,    -$0e9,  $0f0
MurkrowCryHeader:     cry_header CRY_MARILL,     -$01f,  $180
SlowkingCryHeader:    cry_header CRY_SLOWKING,    $104,  $200
MisdreavusCryHeader:  cry_header CRY_HOOTHOOT,    $130,  $0e8
UnownCryHeader:       cry_header CRY_HOOTHOOT,    $162,  $100
WobbuffetCryHeader:   cry_header CRY_AMPHAROS,    $27b,  $144
GirafarigCryHeader:   cry_header CRY_GIRAFARIG,   $041,  $200
PinecoCryHeader:      cry_header CRY_SLOWKING,    $080,  $100
ForretressCryHeader:  cry_header CRY_SLOWKING,    $000,  $180
DunsparceCryHeader:   cry_header CRY_DUNSPARCE,   $1c4,  $100
GligarCryHeader:      cry_header CRY_GLIGAR,     -$102,  $100
SteelixCryHeader:     cry_header CRY_TYPHLOSION,  $0ef,  $0f7
SnubbullCryHeader:    cry_header CRY_DUNSPARCE,   $112,  $0e8
GranbullCryHeader:    cry_header CRY_DUNSPARCE,   $000,  $180
QwilfishCryHeader:    cry_header CRY_SLOWKING,    $160,  $0e0
ScizorCryHeader:      cry_header CRY_AMPHAROS,    $000,  $160
ShuckleCryHeader:     cry_header CRY_DUNSPARCE,   $290,  $0a8
HeracrossCryHeader:   cry_header CRY_AMPHAROS,    $035,  $0e0
SneaselCryHeader:     cry_header CRY_WOOPER,      $053,  $0af
TeddiursaCryHeader:   cry_header CRY_TEDDIURSA,   $7a2,  $06e
UrsaringCryHeader:    cry_header CRY_TEDDIURSA,   $640,  $0d8
SlugmaCryHeader:      cry_header CRY_SLUGMA,     -$1d8,  $140
MagcargoCryHeader:    cry_header CRY_MAGCARGO,   -$20d,  $1c0
SwinubCryHeader:      cry_header CRY_CYNDAQUIL,   $1fe,  $140
PiloswineCryHeader:   cry_header CRY_MAGCARGO,   -$109,  $100
CorsolaCryHeader:     cry_header CRY_MAGCARGO,    $0a1,  $0e8
RemoraidCryHeader:    cry_header CRY_SUNFLORA,    $00d,  $100
OctilleryCryHeader:   cry_header CRY_TOTODILE,    $000,  $180
DelibirdCryHeader:    cry_header CRY_TEDDIURSA,   $002,  $06a
MantineCryHeader:     cry_header CRY_MANTINE,    -$0be,  $0f0
SkarmoryCryHeader:    cry_header CRY_AMPHAROS,    $8a9,  $180
HoundourCryHeader:    cry_header CRY_CYNDAQUIL,   $039,  $140
HoundoomCryHeader:    cry_header CRY_TOTODILE,   -$10a,  $100
KingdraCryHeader:     cry_header CRY_SLUGMA,      $2fb,  $100
PhanpyCryHeader:      cry_header CRY_SENTRET,     $048,  $230
DonphanCryHeader:     cry_header CRY_DONPHAN,     $000,  $1a0
Porygon2CryHeader:    cry_header CRY_GIRAFARIG,   $073,  $240
StantlerCryHeader:    cry_header CRY_AIPOM,      -$160,  $180
SmeargleCryHeader:    cry_header CRY_PICHU,      -$21a,  $1f0
TyrogueCryHeader:     cry_header CRY_AIPOM,       $02c,  $108
HitmontopCryHeader:   cry_header CRY_SLUGMA,      $000,  $100
SmoochumCryHeader:    cry_header CRY_MARILL,      $068,  $100
ElekidCryHeader:      cry_header CRY_SUNFLORA,   -$2d8,  $0b4
MagbyCryHeader:       cry_header CRY_TEDDIURSA,   $176,  $03a
MiltankCryHeader:     cry_header CRY_GLIGAR,     -$1cd,  $1a0
BlisseyCryHeader:     cry_header CRY_SLOWKING,    $293,  $140
RaikouCryHeader:      cry_header CRY_RAIKOU,      $22e,  $120
EnteiCryHeader:       cry_header CRY_ENTEI,       $000,  $1a0
SuicuneCryHeader:     cry_header CRY_MAGCARGO,    $000,  $180
LarvitarCryHeader:    cry_header CRY_RAIKOU,      $05f,  $0d0
PupitarCryHeader:     cry_header CRY_SPINARAK,   -$1db,  $150
TyranitarCryHeader:   cry_header CRY_RAIKOU,     -$100,  $180
LugiaCryHeader:       cry_header CRY_TYPHLOSION,  $000,  $100
HoOhCryHeader:        cry_header CRY_AIPOM,       $000,  $180
CelebiCryHeader:      cry_header CRY_ENTEI,       $14a,  $111
CryHeader252:         cry_header CRY_NIDORAN_M,      0,     0
CryHeader253:         cry_header CRY_NIDORAN_M,      0,     0
CryHeader254:         cry_header CRY_NIDORAN_M,      0,     0
CryHeader255:         cry_header CRY_NIDORAN_M,      0,     0
; f2d81
