; These are all the asm constants needed to make the crystal11_vc patch.

; [fight begin]
EXPORT SCREEN_HEIGHT_PX

; [print forbid 2]
EXPORT PAD_A
; [print forbid 3]
EXPORT MAPGROUP_CIANWOOD
EXPORT MAP_CIANWOOD_PHOTO_STUDIO
; [print forbid 5]
EXPORT NO_INPUT
EXPORT PAD_B
EXPORT PAD_UP
EXPORT PAD_DOWN

; [FPA 001 Begin]
EXPORT FISSURE
; [FPA 002 Begin]
EXPORT SELFDESTRUCT
; [FPA 003 Begin]
EXPORT THUNDER
; [FPA 004 Begin]
EXPORT FLASH
; [FPA 005 Begin]
EXPORT EXPLOSION
; [FPA 006 Begin]
EXPORT HORN_DRILL
; [FPA 007 Begin]
EXPORT HYPER_BEAM

; [FPA 042801 Begin]
EXPORT PRESENT
EXPORT anim_1gfx_command
