; Characteristics of each move

; animation, effect, power, type, accuracy, PP, effect chance

Move0:
	db POUND,        EFFECT_NORMAL_HIT,            40, NORMAL,   $ff, 35, $00
Move1:
	db KARATE_CHOP,  EFFECT_NORMAL_HIT,            50, FIGHTING, $ff, 25, $00
	db DOUBLESLAP,   EFFECT_MULTI_HIT,             15, NORMAL,   $d8, 10, $00
	db COMET_PUNCH,  EFFECT_MULTI_HIT,             18, NORMAL,   $d8, 15, $00
	db MEGA_PUNCH,   EFFECT_NORMAL_HIT,            80, NORMAL,   $d8, 20, $00
	db PAY_DAY,      EFFECT_PAY_DAY,               40, NORMAL,   $ff, 20, $00
	db FIRE_PUNCH,   EFFECT_BURN_HIT,              75, FIRE,     $ff, 15, $19
	db ICE_PUNCH,    EFFECT_FREEZE_HIT,            75, ICE,      $ff, 15, $19
	db THUNDERPUNCH, EFFECT_PARALYZE_HIT,          75, ELECTRIC, $ff, 15, $19
	db SCRATCH,      EFFECT_NORMAL_HIT,            40, NORMAL,   $ff, 35, $00
	db VICEGRIP,     EFFECT_NORMAL_HIT,            55, NORMAL,   $ff, 30, $00
	db GUILLOTINE,   EFFECT_OHKO,                   0, NORMAL,   $4c,  5, $00
	db RAZOR_WIND,   EFFECT_RAZOR_WIND,            80, NORMAL,   $bf, 10, $00
	db SWORDS_DANCE, EFFECT_ATTACK_UP_2,            0, NORMAL,   $ff, 30, $00
	db CUT,          EFFECT_NORMAL_HIT,            50, NORMAL,   $f2, 30, $00
	db GUST,         EFFECT_GUST,                  40, FLYING,   $ff, 35, $00
	db WING_ATTACK,  EFFECT_NORMAL_HIT,            60, FLYING,   $ff, 35, $00
	db WHIRLWIND,    EFFECT_WHIRLWIND,              0, NORMAL,   $ff, 20, $00
	db FLY,          EFFECT_FLY,                   70, FLYING,   $f2, 15, $00
	db BIND,         EFFECT_BIND,                  15, NORMAL,   $bf, 20, $00
	db SLAM,         EFFECT_NORMAL_HIT,            80, NORMAL,   $bf, 20, $00
	db VINE_WHIP,    EFFECT_NORMAL_HIT,            35, GRASS,    $ff, 10, $00
	db STOMP,        EFFECT_STOMP,                 65, NORMAL,   $ff, 20, $4c
	db DOUBLE_KICK,  EFFECT_DOUBLE_HIT,            30, FIGHTING, $ff, 30, $00
	db MEGA_KICK,    EFFECT_NORMAL_HIT,           120, NORMAL,   $bf,  5, $00
	db JUMP_KICK,    EFFECT_JUMP_KICK,             70, FIGHTING, $f2, 25, $00
	db ROLLING_KICK, EFFECT_FLINCH_HIT,            60, FIGHTING, $d8, 15, $4c
	db SAND_ATTACK,  EFFECT_ACCURACY_DOWN,          0, GROUND,   $ff, 15, $00
	db HEADBUTT,     EFFECT_FLINCH_HIT,            70, NORMAL,   $ff, 15, $4c
	db HORN_ATTACK,  EFFECT_NORMAL_HIT,            65, NORMAL,   $ff, 25, $00
	db FURY_ATTACK,  EFFECT_MULTI_HIT,             15, NORMAL,   $d8, 20, $00
	db HORN_DRILL,   EFFECT_OHKO,                   1, NORMAL,   $4c,  5, $00
	db TACKLE,       EFFECT_NORMAL_HIT,            35, NORMAL,   $f2, 35, $00
	db BODY_SLAM,    EFFECT_PARALYZE_HIT,          85, NORMAL,   $ff, 15, $4c
	db WRAP,         EFFECT_BIND,                  15, NORMAL,   $d8, 20, $00
	db TAKE_DOWN,    EFFECT_RECOIL_HIT,            90, NORMAL,   $d8, 20, $00
	db THRASH,       EFFECT_RAMPAGE,               90, NORMAL,   $ff, 20, $00
	db DOUBLE_EDGE,  EFFECT_RECOIL_HIT,           120, NORMAL,   $ff, 15, $00
	db TAIL_WHIP,    EFFECT_DEFENSE_DOWN,           0, NORMAL,   $ff, 30, $00
	db POISON_STING, EFFECT_POISON_HIT,            15, POISON,   $ff, 35, $4c
	db TWINEEDLE,    EFFECT_TWINEEDLE,             25, BUG,      $ff, 20, $33
	db PIN_MISSILE,  EFFECT_MULTI_HIT,             14, BUG,      $d8, 20, $00
	db LEER,         EFFECT_DEFENSE_DOWN,           0, NORMAL,   $ff, 30, $00
	db BITE,         EFFECT_FLINCH_HIT,            60, DARK,     $ff, 25, $4c
	db GROWL,        EFFECT_ATTACK_DOWN,            0, NORMAL,   $ff, 40, $00
	db ROAR,         EFFECT_WHIRLWIND,              0, NORMAL,   $ff, 20, $00
	db SING,         EFFECT_SLEEP,                  0, NORMAL,   $8c, 15, $00
	db SUPERSONIC,   EFFECT_CONFUSE,                0, NORMAL,   $8c, 20, $00
	db SONICBOOM,    EFFECT_STATIC_DAMAGE,         20, NORMAL,   $e5, 20, $00
	db DISABLE,      EFFECT_DISABLE,                0, NORMAL,   $8c, 20, $00
	db ACID,         EFFECT_DEFENSE_DOWN_HIT,      40, POISON,   $ff, 30, $19
	db EMBER,        EFFECT_BURN_HIT,              40, FIRE,     $ff, 25, $19
	db FLAMETHROWER, EFFECT_BURN_HIT,              95, FIRE,     $ff, 15, $19
	db MIST,         EFFECT_MIST,                   0, ICE,      $ff, 30, $00
	db WATER_GUN,    EFFECT_NORMAL_HIT,            40, WATER,    $ff, 25, $00
	db HYDRO_PUMP,   EFFECT_NORMAL_HIT,           120, WATER,    $cc,  5, $00
	db SURF,         EFFECT_NORMAL_HIT,            95, WATER,    $ff, 15, $00
	db ICE_BEAM,     EFFECT_FREEZE_HIT,            95, ICE,      $ff, 10, $19
	db BLIZZARD,     EFFECT_FREEZE_HIT,           120, ICE,      $b2,  5, $19
	db PSYBEAM,      EFFECT_CONFUSE_HIT,           65, PSYCHIC,  $ff, 20, $19
	db BUBBLEBEAM,   EFFECT_SPEED_DOWN_HIT,        65, WATER,    $ff, 20, $19
	db AURORA_BEAM,  EFFECT_ATTACK_DOWN_HIT,       65, ICE,      $ff, 20, $19
	db HYPER_BEAM,   EFFECT_HYPER_BEAM,           150, NORMAL,   $e5,  5, $00
	db PECK,         EFFECT_NORMAL_HIT,            35, FLYING,   $ff, 35, $00
	db DRILL_PECK,   EFFECT_NORMAL_HIT,            80, FLYING,   $ff, 20, $00
	db SUBMISSION,   EFFECT_RECOIL_HIT,            80, FIGHTING, $cc, 25, $00
	db LOW_KICK,     EFFECT_FLINCH_HIT,            50, FIGHTING, $e5, 20, $4c
	db COUNTER,      EFFECT_COUNTER,                1, FIGHTING, $ff, 20, $00
	db SEISMIC_TOSS, EFFECT_LEVEL_DAMAGE,           1, FIGHTING, $ff, 20, $00
	db STRENGTH,     EFFECT_NORMAL_HIT,            80, NORMAL,   $ff, 15, $00
	db ABSORB,       EFFECT_LEECH_HIT,             20, GRASS,    $ff, 20, $00
	db MEGA_DRAIN,   EFFECT_LEECH_HIT,             40, GRASS,    $ff, 10, $00
	db LEECH_SEED,   EFFECT_LEECH_SEED,             0, GRASS,    $e5, 10, $00
	db GROWTH,       EFFECT_SP_ATTACK_UP,           0, NORMAL,   $ff, 40, $00
	db RAZOR_LEAF,   EFFECT_NORMAL_HIT,            55, GRASS,    $f2, 25, $00
	db SOLARBEAM,    EFFECT_SOLARBEAM,            120, GRASS,    $ff, 10, $00
	db POISONPOWDER, EFFECT_POISON,                 0, POISON,   $bf, 35, $00
	db STUN_SPORE,   EFFECT_PARALYZE,               0, GRASS,    $bf, 30, $00
	db SLEEP_POWDER, EFFECT_SLEEP,                  0, GRASS,    $bf, 15, $00
	db PETAL_DANCE,  EFFECT_RAMPAGE,               70, GRASS,    $ff, 20, $00
	db STRING_SHOT,  EFFECT_SPEED_DOWN,             0, BUG,      $f2, 40, $00
	db DRAGON_RAGE,  EFFECT_STATIC_DAMAGE,         40, DRAGON,   $ff, 10, $00
	db FIRE_SPIN,    EFFECT_BIND,                  15, FIRE,     $b2, 15, $00
	db THUNDERSHOCK, EFFECT_PARALYZE_HIT,          40, ELECTRIC, $ff, 30, $19
	db THUNDERBOLT,  EFFECT_PARALYZE_HIT,          95, ELECTRIC, $ff, 15, $19
	db THUNDER_WAVE, EFFECT_PARALYZE,               0, ELECTRIC, $ff, 20, $00
	db THUNDER,      EFFECT_THUNDER,              120, ELECTRIC, $b2, 10, $4c
	db ROCK_THROW,   EFFECT_NORMAL_HIT,            50, ROCK,     $e5, 15, $00
	db EARTHQUAKE,   EFFECT_EARTHQUAKE,           100, GROUND,   $ff, 10, $00
	db FISSURE,      EFFECT_OHKO,                   1, GROUND,   $4c,  5, $00
	db DIG,          EFFECT_FLY,                   60, GROUND,   $ff, 10, $00
	db TOXIC,        EFFECT_TOXIC,                  0, POISON,   $d8, 10, $00
	db CONFUSION,    EFFECT_CONFUSE_HIT,           50, PSYCHIC,  $ff, 25, $19
	db PSYCHIC_M,    EFFECT_SP_DEFENSE_DOWN_HIT,   90, PSYCHIC,  $ff, 10, $19
	db HYPNOSIS,     EFFECT_SLEEP,                  0, PSYCHIC,  $99, 20, $00
	db MEDITATE,     EFFECT_ATTACK_UP,              0, PSYCHIC,  $ff, 40, $00
	db AGILITY,      EFFECT_SPEED_UP_2,             0, PSYCHIC,  $ff, 30, $00
	db QUICK_ATTACK, EFFECT_PRIORITY_HIT,          40, NORMAL,   $ff, 30, $00
	db RAGE,         EFFECT_RAGE,                  20, NORMAL,   $ff, 20, $00
	db TELEPORT,     EFFECT_TELEPORT,               0, PSYCHIC,  $ff, 20, $00
	db NIGHT_SHADE,  EFFECT_LEVEL_DAMAGE,           1, GHOST,    $ff, 15, $00
	db MIMIC,        EFFECT_MIMIC,                  0, NORMAL,   $ff, 10, $00
	db SCREECH,      EFFECT_DEFENSE_DOWN_2,         0, NORMAL,   $d8, 40, $00
	db DOUBLE_TEAM,  EFFECT_EVASION_UP,             0, NORMAL,   $ff, 15, $00
	db RECOVER,      EFFECT_HEAL,                   0, NORMAL,   $ff, 20, $00
	db HARDEN,       EFFECT_DEFENSE_UP,             0, NORMAL,   $ff, 30, $00
	db MINIMIZE,     EFFECT_EVASION_UP,             0, NORMAL,   $ff, 20, $00
	db SMOKESCREEN,  EFFECT_ACCURACY_DOWN,          0, NORMAL,   $ff, 20, $00
	db CONFUSE_RAY,  EFFECT_CONFUSE,                0, GHOST,    $ff, 10, $00
	db WITHDRAW,     EFFECT_DEFENSE_UP,             0, WATER,    $ff, 40, $00
	db DEFENSE_CURL, EFFECT_DEFENSE_CURL,           0, NORMAL,   $ff, 40, $00
	db BARRIER,      EFFECT_DEFENSE_UP_2,           0, PSYCHIC,  $ff, 30, $00
	db LIGHT_SCREEN, EFFECT_LIGHT_SCREEN,           0, PSYCHIC,  $ff, 30, $00
	db HAZE,         EFFECT_HAZE,                   0, ICE,      $ff, 30, $00
	db REFLECT,      EFFECT_REFLECT,                0, PSYCHIC,  $ff, 20, $00
	db FOCUS_ENERGY, EFFECT_FOCUS_ENERGY,           0, NORMAL,   $ff, 30, $00
	db BIDE,         EFFECT_BIDE,                   0, NORMAL,   $ff, 10, $00
	db METRONOME,    EFFECT_METRONOME,              0, NORMAL,   $ff, 10, $00
	db MIRROR_MOVE,  EFFECT_MIRROR_MOVE,            0, FLYING,   $ff, 20, $00
	db SELFDESTRUCT, EFFECT_EXPLOSION,            200, NORMAL,   $ff,  5, $00
	db EGG_BOMB,     EFFECT_NORMAL_HIT,           100, NORMAL,   $bf, 10, $00
	db LICK,         EFFECT_PARALYZE_HIT,          20, GHOST,    $ff, 30, $4c
	db SMOG,         EFFECT_POISON_HIT,            20, POISON,   $b2, 20, $66
	db SLUDGE,       EFFECT_POISON_HIT,            65, POISON,   $ff, 20, $4c
	db BONE_CLUB,    EFFECT_FLINCH_HIT,            65, GROUND,   $d8, 20, $19
	db FIRE_BLAST,   EFFECT_BURN_HIT,             120, FIRE,     $d8,  5, $19
	db WATERFALL,    EFFECT_NORMAL_HIT,            80, WATER,    $ff, 15, $00
	db CLAMP,        EFFECT_BIND,                  35, WATER,    $bf, 10, $00
	db SWIFT,        EFFECT_ALWAYS_HIT,            60, NORMAL,   $ff, 20, $00
	db SKULL_BASH,   EFFECT_SKULL_BASH,           100, NORMAL,   $ff, 15, $00
	db SPIKE_CANNON, EFFECT_MULTI_HIT,             20, NORMAL,   $ff, 15, $00
	db CONSTRICT,    EFFECT_SPEED_DOWN_HIT,        10, NORMAL,   $ff, 35, $19
	db AMNESIA,      EFFECT_SP_DEFENSE_UP_2,        0, PSYCHIC,  $ff, 20, $00
	db KINESIS,      EFFECT_ACCURACY_DOWN,          0, PSYCHIC,  $cc, 15, $00
	db SOFTBOILED,   EFFECT_HEAL,                   0, NORMAL,   $ff, 10, $00
	db HI_JUMP_KICK, EFFECT_JUMP_KICK,             85, FIGHTING, $e5, 20, $00
	db GLARE,        EFFECT_PARALYZE,               0, NORMAL,   $bf, 30, $00
	db DREAM_EATER,  EFFECT_DREAM_EATER,          100, PSYCHIC,  $ff, 15, $00
	db POISON_GAS,   EFFECT_POISON,                 0, POISON,   $8c, 40, $00
	db BARRAGE,      EFFECT_MULTI_HIT,             15, NORMAL,   $d8, 20, $00
	db LEECH_LIFE,   EFFECT_LEECH_HIT,             20, BUG,      $ff, 15, $00
	db LOVELY_KISS,  EFFECT_SLEEP,                  0, NORMAL,   $bf, 10, $00
	db SKY_ATTACK,   EFFECT_SKY_ATTACK,           140, FLYING,   $e5,  5, $00
	db TRANSFORM,    EFFECT_TRANSFORM,              0, NORMAL,   $ff, 10, $00
	db BUBBLE,       EFFECT_SPEED_DOWN_HIT,        20, WATER,    $ff, 30, $19
	db DIZZY_PUNCH,  EFFECT_CONFUSE_HIT,           70, NORMAL,   $ff, 10, $33
	db SPORE,        EFFECT_SLEEP,                  0, GRASS,    $ff, 15, $00
	db FLASH,        EFFECT_ACCURACY_DOWN,          0, NORMAL,   $b2, 20, $00
	db PSYWAVE,      EFFECT_PSYWAVE,                1, PSYCHIC,  $cc, 15, $00
	db SPLASH,       EFFECT_SPLASH,                 0, NORMAL,   $ff, 40, $00
	db ACID_ARMOR,   EFFECT_DEFENSE_UP_2,           0, POISON,   $ff, 40, $00
	db CRABHAMMER,   EFFECT_NORMAL_HIT,            90, WATER,    $d8, 10, $00
	db EXPLOSION,    EFFECT_EXPLOSION,            250, NORMAL,   $ff,  5, $00
	db FURY_SWIPES,  EFFECT_MULTI_HIT,             18, NORMAL,   $cc, 15, $00
	db BONEMERANG,   EFFECT_DOUBLE_HIT,            50, GROUND,   $e5, 10, $00
	db REST,         EFFECT_HEAL,                   0, PSYCHIC,  $ff, 10, $00
	db ROCK_SLIDE,   EFFECT_FLINCH_HIT,            75, ROCK,     $e5, 10, $4c
	db HYPER_FANG,   EFFECT_FLINCH_HIT,            80, NORMAL,   $e5, 15, $19
	db SHARPEN,      EFFECT_ATTACK_UP,              0, NORMAL,   $ff, 30, $00
	db CONVERSION,   EFFECT_CONVERSION,             0, NORMAL,   $ff, 30, $00
	db TRI_ATTACK,   EFFECT_TRI_ATTACK,            80, NORMAL,   $ff, 10, $33
	db SUPER_FANG,   EFFECT_SUPER_FANG,             1, NORMAL,   $e5, 10, $00
	db SLASH,        EFFECT_NORMAL_HIT,            70, NORMAL,   $ff, 20, $00
	db SUBSTITUTE,   EFFECT_SUBSTITUTE,             0, NORMAL,   $ff, 10, $00
	db STRUGGLE,     EFFECT_RECOIL_HIT,            50, NORMAL,   $ff,  1, $00
	db SKETCH,       EFFECT_SKETCH,                 0, NORMAL,   $ff,  1, $00
	db TRIPLE_KICK,  EFFECT_TRIPLE_KICK,           10, FIGHTING, $e5, 10, $00
	db THIEF,        EFFECT_THIEF,                 40, DARK,     $ff, 10, $ff
	db SPIDER_WEB,   EFFECT_MEAN_LOOK,              0, BUG,      $ff, 10, $00
	db MIND_READER,  EFFECT_LOCK_ON,                0, NORMAL,   $ff,  5, $00
	db NIGHTMARE,    EFFECT_NIGHTMARE,              0, GHOST,    $ff, 15, $00
	db FLAME_WHEEL,  EFFECT_FLAME_WHEEL,           60, FIRE,     $ff, 25, $19
	db SNORE,        EFFECT_SNORE,                 40, NORMAL,   $ff, 15, $4c
	db CURSE,        EFFECT_CURSE,                  0, CURSE_T,  $ff, 10, $00
	db FLAIL,        EFFECT_REVERSAL,               1, NORMAL,   $ff, 15, $00
	db CONVERSION2,  EFFECT_CONVERSION2,            0, NORMAL,   $ff, 30, $00
	db AEROBLAST,    EFFECT_NORMAL_HIT,           100, FLYING,   $f2,  5, $00
	db COTTON_SPORE, EFFECT_SPEED_DOWN_2,           0, GRASS,    $d8, 40, $00
	db REVERSAL,     EFFECT_REVERSAL,               1, FIGHTING, $ff, 15, $00
	db SPITE,        EFFECT_SPITE,                  0, GHOST,    $ff, 10, $00
	db POWDER_SNOW,  EFFECT_FREEZE_HIT,            40, ICE,      $ff, 25, $19
	db PROTECT,      EFFECT_PROTECT,                0, NORMAL,   $ff, 10, $00
	db MACH_PUNCH,   EFFECT_PRIORITY_HIT,          40, FIGHTING, $ff, 30, $00
	db SCARY_FACE,   EFFECT_SPEED_DOWN_2,           0, NORMAL,   $e5, 10, $00
	db FAINT_ATTACK, EFFECT_ALWAYS_HIT,            60, DARK,     $ff, 20, $00
	db SWEET_KISS,   EFFECT_CONFUSE,                0, NORMAL,   $bf, 10, $00
	db BELLY_DRUM,   EFFECT_BELLY_DRUM,             0, NORMAL,   $ff, 10, $00
	db SLUDGE_BOMB,  EFFECT_POISON_HIT,            90, POISON,   $ff, 10, $4c
	db MUD_SLAP,     EFFECT_ACCURACY_DOWN_HIT,     20, GROUND,   $ff, 10, $ff
	db OCTAZOOKA,    EFFECT_ACCURACY_DOWN_HIT,     65, WATER,    $d8, 10, $7f
	db SPIKES,       EFFECT_SPIKES,                 0, GROUND,   $ff, 20, $00
	db ZAP_CANNON,   EFFECT_PARALYZE_HIT,         100, ELECTRIC, $7f,  5, $ff
	db FORESIGHT,    EFFECT_FORESIGHT,              0, NORMAL,   $ff, 40, $00
	db DESTINY_BOND, EFFECT_DESTINY_BOND,           0, GHOST,    $ff,  5, $00
	db PERISH_SONG,  EFFECT_PERISH_SONG,            0, NORMAL,   $ff,  5, $00
	db ICY_WIND,     EFFECT_SPEED_DOWN_HIT,        55, ICE,      $f2, 15, $ff
	db DETECT,       EFFECT_PROTECT,                0, FIGHTING, $ff,  5, $00
	db BONE_RUSH,    EFFECT_MULTI_HIT,             25, GROUND,   $cc, 10, $00
	db LOCK_ON,      EFFECT_LOCK_ON,                0, NORMAL,   $ff,  5, $00
	db OUTRAGE,      EFFECT_RAMPAGE,               90, DRAGON,   $ff, 15, $00
	db SANDSTORM,    EFFECT_SANDSTORM,              0, ROCK,     $ff, 10, $00
	db GIGA_DRAIN,   EFFECT_LEECH_HIT,             60, GRASS,    $ff,  5, $00
	db ENDURE,       EFFECT_ENDURE,                 0, NORMAL,   $ff, 10, $00
	db CHARM,        EFFECT_ATTACK_DOWN_2,          0, NORMAL,   $ff, 20, $00
	db ROLLOUT,      EFFECT_ROLLOUT,               30, ROCK,     $e5, 20, $00
	db FALSE_SWIPE,  EFFECT_FALSE_SWIPE,           40, NORMAL,   $ff, 40, $00
	db SWAGGER,      EFFECT_SWAGGER,                0, NORMAL,   $e5, 15, $ff
	db MILK_DRINK,   EFFECT_HEAL,                   0, NORMAL,   $ff, 10, $00
	db SPARK,        EFFECT_PARALYZE_HIT,          65, ELECTRIC, $ff, 20, $4c
	db FURY_CUTTER,  EFFECT_FURY_CUTTER,           10, BUG,      $f2, 20, $00
	db STEEL_WING,   EFFECT_STEEL_WING,            70, STEEL,    $e5, 25, $19
	db MEAN_LOOK,    EFFECT_MEAN_LOOK,              0, NORMAL,   $ff,  5, $00
	db ATTRACT,      EFFECT_ATTRACT,                0, NORMAL,   $ff, 15, $00
	db SLEEP_TALK,   EFFECT_SLEEP_TALK,             0, NORMAL,   $ff, 10, $00
	db HEAL_BELL,    EFFECT_HEAL_BELL,              0, NORMAL,   $ff,  5, $00
	db RETURN,       EFFECT_RETURN,                 1, NORMAL,   $ff, 20, $00
	db PRESENT,      EFFECT_PRESENT,                1, NORMAL,   $e5, 15, $00
	db FRUSTRATION,  EFFECT_FRUSTRATION,            1, NORMAL,   $ff, 20, $00
	db SAFEGUARD,    EFFECT_SAFEGUARD,              0, NORMAL,   $ff, 25, $00
	db PAIN_SPLIT,   EFFECT_PAIN_SPLIT,             0, NORMAL,   $ff, 20, $00
	db SACRED_FIRE,  EFFECT_SACRED_FIRE,          100, FIRE,     $f2,  5, $7f
	db MAGNITUDE,    EFFECT_MAGNITUDE,              1, GROUND,   $ff, 30, $00
	db DYNAMICPUNCH, EFFECT_CONFUSE_HIT,          100, FIGHTING, $7f,  5, $ff
	db MEGAHORN,     EFFECT_NORMAL_HIT,           120, BUG,      $d8, 10, $00
	db DRAGONBREATH, EFFECT_PARALYZE_HIT,          60, DRAGON,   $ff, 20, $4c
	db BATON_PASS,   EFFECT_BATON_PASS,             0, NORMAL,   $ff, 40, $00
	db ENCORE,       EFFECT_ENCORE,                 0, NORMAL,   $ff,  5, $00
	db PURSUIT,      EFFECT_PURSUIT,               40, DARK,     $ff, 20, $00
	db RAPID_SPIN,   EFFECT_RAPID_SPIN,            20, NORMAL,   $ff, 40, $00
	db SWEET_SCENT,  EFFECT_EVASION_DOWN,           0, NORMAL,   $ff, 20, $00
	db IRON_TAIL,    EFFECT_DEFENSE_DOWN_HIT,     100, STEEL,    $bf, 15, $4c
	db METAL_CLAW,   EFFECT_METAL_CLAW,            50, STEEL,    $f2, 35, $19
	db VITAL_THROW,  EFFECT_ALWAYS_HIT,            70, FIGHTING, $ff, 10, $00
	db MORNING_SUN,  EFFECT_MORNING_SUN,            0, NORMAL,   $ff,  5, $00
	db SYNTHESIS,    EFFECT_SYNTHESIS,              0, GRASS,    $ff,  5, $00
	db MOONLIGHT,    EFFECT_MOONLIGHT,              0, NORMAL,   $ff,  5, $00
	db HIDDEN_POWER, EFFECT_HIDDEN_POWER,           1, NORMAL,   $ff, 15, $00
	db CROSS_CHOP,   EFFECT_NORMAL_HIT,           100, FIGHTING, $cc,  5, $00
	db TWISTER,      EFFECT_TWISTER,               40, DRAGON,   $ff, 20, $33
	db RAIN_DANCE,   EFFECT_RAIN_DANCE,             0, WATER,    $e5,  5, $00
	db SUNNY_DAY,    EFFECT_SUNNY_DAY,              0, FIRE,     $e5,  5, $00
	db CRUNCH,       EFFECT_SP_DEFENSE_DOWN_HIT,   80, DARK,     $ff, 15, $33
	db MIRROR_COAT,  EFFECT_MIRROR_COAT,            1, PSYCHIC,  $ff, 20, $00
	db PSYCH_UP,     EFFECT_PSYCH_UP,               0, NORMAL,   $ff, 10, $00
	db EXTREMESPEED, EFFECT_PRIORITY_HIT,          80, NORMAL,   $ff,  5, $00
	db ANCIENTPOWER, EFFECT_ANCIENTPOWER,          60, ROCK,     $ff,  5, $19
	db SHADOW_BALL,  EFFECT_SP_DEFENSE_DOWN_HIT,   80, GHOST,    $ff, 15, $33
	db FUTURE_SIGHT, EFFECT_FUTURE_SIGHT,          80, PSYCHIC,  $e5, 15, $00
	db ROCK_SMASH,   EFFECT_DEFENSE_DOWN_HIT,      20, FIGHTING, $ff, 15, $7f
	db WHIRLPOOL,    EFFECT_BIND,                  15, WATER,    $b2, 15, $00
	db BEAT_UP,      EFFECT_BEAT_UP,               10, DARK,     $ff, 10, $00

