SECTION "gfx/pokemon/unown_frames.asm", ROMX

INCLUDE "gfx/pokemon/unown_frame_pointers.inc"

UnownsFrames:: ; used only for BANK(UnownsFrames)

UnownAFrames: INCLUDE "gfx/pokemon/unown_a/frames.inc"
UnownBFrames: INCLUDE "gfx/pokemon/unown_b/frames.inc"
UnownCFrames: INCLUDE "gfx/pokemon/unown_c/frames.inc"
UnownDFrames: INCLUDE "gfx/pokemon/unown_d/frames.inc"
UnownEFrames: INCLUDE "gfx/pokemon/unown_e/frames.inc"
UnownFFrames: INCLUDE "gfx/pokemon/unown_f/frames.inc"
UnownGFrames: INCLUDE "gfx/pokemon/unown_g/frames.inc"
UnownHFrames: INCLUDE "gfx/pokemon/unown_h/frames.inc"
UnownIFrames: INCLUDE "gfx/pokemon/unown_i/frames.inc"
UnownJFrames: INCLUDE "gfx/pokemon/unown_j/frames.inc"
UnownKFrames: INCLUDE "gfx/pokemon/unown_k/frames.inc"
UnownLFrames: INCLUDE "gfx/pokemon/unown_l/frames.inc"
UnownMFrames: INCLUDE "gfx/pokemon/unown_m/frames.inc"
UnownNFrames: INCLUDE "gfx/pokemon/unown_n/frames.inc"
UnownOFrames: INCLUDE "gfx/pokemon/unown_o/frames.inc"
UnownPFrames: INCLUDE "gfx/pokemon/unown_p/frames.inc"
UnownQFrames: INCLUDE "gfx/pokemon/unown_q/frames.inc"
UnownRFrames: INCLUDE "gfx/pokemon/unown_r/frames.inc"
UnownSFrames: INCLUDE "gfx/pokemon/unown_s/frames.inc"
UnownTFrames: INCLUDE "gfx/pokemon/unown_t/frames.inc"
UnownUFrames: INCLUDE "gfx/pokemon/unown_u/frames.inc"
UnownVFrames: INCLUDE "gfx/pokemon/unown_v/frames.inc"
UnownWFrames: INCLUDE "gfx/pokemon/unown_w/frames.inc"
UnownXFrames: INCLUDE "gfx/pokemon/unown_x/frames.inc"
UnownYFrames: INCLUDE "gfx/pokemon/unown_y/frames.inc"
UnownZFrames: INCLUDE "gfx/pokemon/unown_z/frames.inc"
