SECTION "gfx/pokemon/unown_bitmasks.asm", ROMX

INCLUDE "gfx/pokemon/unown_bitmask_pointers.inc"

UnownABitmasks: INCLUDE "gfx/pokemon/unown_a/bitmask.inc"
UnownBBitmasks: INCLUDE "gfx/pokemon/unown_b/bitmask.inc"
UnownCBitmasks: INCLUDE "gfx/pokemon/unown_c/bitmask.inc"
UnownDBitmasks: INCLUDE "gfx/pokemon/unown_d/bitmask.inc"
UnownEBitmasks: INCLUDE "gfx/pokemon/unown_e/bitmask.inc"
UnownFBitmasks: INCLUDE "gfx/pokemon/unown_f/bitmask.inc"
UnownGBitmasks: INCLUDE "gfx/pokemon/unown_g/bitmask.inc"
UnownHBitmasks: INCLUDE "gfx/pokemon/unown_h/bitmask.inc"
UnownIBitmasks: INCLUDE "gfx/pokemon/unown_i/bitmask.inc"
UnownJBitmasks: INCLUDE "gfx/pokemon/unown_j/bitmask.inc"
UnownKBitmasks: INCLUDE "gfx/pokemon/unown_k/bitmask.inc"
UnownLBitmasks: INCLUDE "gfx/pokemon/unown_l/bitmask.inc"
UnownMBitmasks: INCLUDE "gfx/pokemon/unown_m/bitmask.inc"
UnownNBitmasks: INCLUDE "gfx/pokemon/unown_n/bitmask.inc"
UnownOBitmasks: INCLUDE "gfx/pokemon/unown_o/bitmask.inc"
UnownPBitmasks: INCLUDE "gfx/pokemon/unown_p/bitmask.inc"
UnownQBitmasks: INCLUDE "gfx/pokemon/unown_q/bitmask.inc"
UnownRBitmasks: INCLUDE "gfx/pokemon/unown_r/bitmask.inc"
UnownSBitmasks: INCLUDE "gfx/pokemon/unown_s/bitmask.inc"
UnownTBitmasks: INCLUDE "gfx/pokemon/unown_t/bitmask.inc"
UnownUBitmasks: INCLUDE "gfx/pokemon/unown_u/bitmask.inc"
UnownVBitmasks: INCLUDE "gfx/pokemon/unown_v/bitmask.inc"
UnownWBitmasks: INCLUDE "gfx/pokemon/unown_w/bitmask.inc"
UnownXBitmasks: INCLUDE "gfx/pokemon/unown_x/bitmask.inc"
UnownYBitmasks: INCLUDE "gfx/pokemon/unown_y/bitmask.inc"
UnownZBitmasks: INCLUDE "gfx/pokemon/unown_z/bitmask.inc"
