UnownBitmasksPointers:
	table_width 2
	dw UnownABitmasks
	dw UnownBBitmasks
	dw UnownCBitmasks
	dw UnownDBitmasks
	dw UnownEBitmasks
	dw UnownFBitmasks
	dw UnownGBitmasks
	dw UnownHBitmasks
	dw UnownIBitmasks
	dw UnownJBitmasks
	dw UnownKBitmasks
	dw UnownLBitmasks
	dw UnownMBitmasks
	dw UnownNBitmasks
	dw UnownOBitmasks
	dw UnownPBitmasks
	dw UnownQBitmasks
	dw UnownRBitmasks
	dw UnownSBitmasks
	dw UnownTBitmasks
	dw UnownUBitmasks
	dw UnownVBitmasks
	dw UnownWBitmasks
	dw UnownXBitmasks
	dw UnownYBitmasks
	dw UnownZBitmasks
	assert_table_length NUM_UNOWN
