UnownAnimationPointers:
	table_width 2, UnownAnimationPointers
	dw UnownAAnimation
	dw UnownBAnimation
	dw UnownCAnimation
	dw UnownDAnimation
	dw UnownEAnimation
	dw UnownFAnimation
	dw UnownGAnimation
	dw UnownHAnimation
	dw UnownIAnimation
	dw UnownJAnimation
	dw UnownKAnimation
	dw UnownLAnimation
	dw UnownMAnimation
	dw UnownNAnimation
	dw UnownOAnimation
	dw UnownPAnimation
	dw UnownQAnimation
	dw UnownRAnimation
	dw UnownSAnimation
	dw UnownTAnimation
	dw UnownUAnimation
	dw UnownVAnimation
	dw UnownWAnimation
	dw UnownXAnimation
	dw UnownYAnimation
	dw UnownZAnimation
	assert_table_length NUM_UNOWN
