UnownAnimationIdlePointers:
	table_width 2, UnownAnimationIdlePointers
	dw UnownAAnimationIdle
	dw UnownBAnimationIdle
	dw UnownCAnimationIdle
	dw UnownDAnimationIdle
	dw UnownEAnimationIdle
	dw UnownFAnimationIdle
	dw UnownGAnimationIdle
	dw UnownHAnimationIdle
	dw UnownIAnimationIdle
	dw UnownJAnimationIdle
	dw UnownKAnimationIdle
	dw UnownLAnimationIdle
	dw UnownMAnimationIdle
	dw UnownNAnimationIdle
	dw UnownOAnimationIdle
	dw UnownPAnimationIdle
	dw UnownQAnimationIdle
	dw UnownRAnimationIdle
	dw UnownSAnimationIdle
	dw UnownTAnimationIdle
	dw UnownUAnimationIdle
	dw UnownVAnimationIdle
	dw UnownWAnimationIdle
	dw UnownXAnimationIdle
	dw UnownYAnimationIdle
	dw UnownZAnimationIdle
	assert_table_length NUM_UNOWN
