UnownAnimationExtraPointers:
	dw UnownAAnimationExtra
	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
