INCLUDE "constants.inc"


SECTION "gfx/pokemon/unown_anims.asm", ROMX

INCLUDE "gfx/pokemon/unown_anim_pointers.inc"

UnownAAnimation: INCLUDE "gfx/pokemon/unown_a/anim.inc"
UnownBAnimation: INCLUDE "gfx/pokemon/unown_b/anim.inc"
UnownCAnimation: INCLUDE "gfx/pokemon/unown_c/anim.inc"
UnownDAnimation: INCLUDE "gfx/pokemon/unown_d/anim.inc"
UnownEAnimation: INCLUDE "gfx/pokemon/unown_e/anim.inc"
UnownFAnimation: INCLUDE "gfx/pokemon/unown_f/anim.inc"
UnownGAnimation: INCLUDE "gfx/pokemon/unown_g/anim.inc"
UnownHAnimation: INCLUDE "gfx/pokemon/unown_h/anim.inc"
UnownIAnimation: INCLUDE "gfx/pokemon/unown_i/anim.inc"
UnownJAnimation: INCLUDE "gfx/pokemon/unown_j/anim.inc"
UnownKAnimation: INCLUDE "gfx/pokemon/unown_k/anim.inc"
UnownLAnimation: INCLUDE "gfx/pokemon/unown_l/anim.inc"
UnownMAnimation: INCLUDE "gfx/pokemon/unown_m/anim.inc"
UnownNAnimation: INCLUDE "gfx/pokemon/unown_n/anim.inc"
UnownOAnimation: INCLUDE "gfx/pokemon/unown_o/anim.inc"
UnownPAnimation: INCLUDE "gfx/pokemon/unown_p/anim.inc"
UnownQAnimation: INCLUDE "gfx/pokemon/unown_q/anim.inc"
UnownRAnimation: INCLUDE "gfx/pokemon/unown_r/anim.inc"
UnownSAnimation: INCLUDE "gfx/pokemon/unown_s/anim.inc"
UnownTAnimation: INCLUDE "gfx/pokemon/unown_t/anim.inc"
UnownUAnimation: INCLUDE "gfx/pokemon/unown_u/anim.inc"
UnownVAnimation: INCLUDE "gfx/pokemon/unown_v/anim.inc"
UnownWAnimation: INCLUDE "gfx/pokemon/unown_w/anim.inc"
UnownXAnimation: INCLUDE "gfx/pokemon/unown_x/anim.inc"
UnownYAnimation: INCLUDE "gfx/pokemon/unown_y/anim.inc"
UnownZAnimation: INCLUDE "gfx/pokemon/unown_z/anim.inc"

INCLUDE "gfx/pokemon/unown_idles.inc"
