	enum_start 1

	short_command checkturn
	short_command checkobedience
	short_command usedmovetext
	short_command doturn
	short_command critical
	short_command damagestats
	short_command stab
	short_command damagevariation
	short_command checkhit
	short_command lowersub
	short_command hittargetnosub
	short_command raisesub
	short_command failuretext
	short_command checkfaint
	short_command criticaltext
	short_command supereffectivetext
	short_command checkdestinybond
	short_command buildopponentrage
	short_command poisontarget
	short_command sleeptarget
	short_command draintarget
	short_command eatdream
	short_command burntarget
	short_command freezetarget
	short_command paralyzetarget
	short_command selfdestruct
	short_command mirrormove
	short_command statup
	short_command statdown
	short_command payday
	short_command conversion
	short_command resetstats
	short_command storeenergy
	short_command unleashenergy
	short_command forceswitch
	short_command endloop
	short_command flinchtarget
	short_command ohko
	short_command recoil
	short_command mist
	short_command focusenergy
	short_command confuse
	short_command confusetarget
	short_command heal
	short_command transform
	short_command screen
	short_command poison
	short_command paralyze
	short_command substitute
	short_command rechargenextturn
	short_command mimic
	short_command metronome
	short_command leechseed
	short_command splash
	short_command disable
	short_command cleartext
	short_command charge
	short_command checkcharge
	short_command traptarget
	short_command effect0x3c
	short_command rampage
	short_command checkrampage
	short_command constantdamage
	short_command counter
	short_command encore
	short_command painsplit
	short_command snore
	short_command conversion2
	short_command lockon
	short_command sketch
	short_command defrostopponent
	short_command sleeptalk
	short_command destinybond
	short_command spite
	short_command falseswipe
	short_command healbell
	short_command kingsrock
	short_command triplekick
	short_command kickcounter
	short_command thief
	short_command arenatrap
	short_command nightmare
	short_command defrost
	short_command curse
	short_command protect
	short_command spikes
	short_command foresight
	short_command perishsong
	short_command startsandstorm
	short_command endure
	short_command checkcurl
	short_command rolloutpower
	short_command effect0x5d
	short_command furycutter
	short_command attract
	short_command happinesspower
	short_command present
	short_command damagecalc
	short_command frustrationpower
	short_command safeguard
	short_command checksafeguard
	short_command getmagnitude
	short_command batonpass
	short_command pursuit
	short_command clearhazards
	short_command healmorn
	short_command healday
	short_command healnite
	short_command hiddenpower
	short_command startrain
	short_command startsun
	short_command attackup
	short_command defenseup
	short_command speedup
	short_command specialattackup
	short_command specialdefenseup
	short_command accuracyup
	short_command evasionup
	short_command attackup2
	short_command defenseup2
	short_command speedup2
	short_command specialattackup2
	short_command specialdefenseup2
	short_command accuracyup2
	short_command evasionup2
	short_command attackdown
	short_command defensedown
	short_command speeddown
	short_command specialattackdown
	short_command specialdefensedown
	short_command accuracydown
	short_command evasiondown
	short_command attackdown2
	short_command defensedown2
	short_command speeddown2
	short_command specialattackdown2
	short_command specialdefensedown2
	short_command accuracydown2
	short_command evasiondown2
	short_command statupmessage
	short_command statdownmessage
	short_command statupfailtext
	short_command statdownfailtext
	short_command effectchance
	short_command statdownanim
	short_command statupanim
	short_command switchturn
	short_command fakeout
	short_command bellydrum
	short_command psychup
	short_command rage
	short_command doubleflyingdamage
	short_command doubleundergrounddamage
	short_command mirrorcoat
	short_command checkfuturesight
	short_command futuresight
	short_command doubleminimizedamage
	short_command skipsuncharge
	short_command thunderaccuracy
	short_command teleport
	short_command beatup
	short_command ragedamage
	short_command resettypematchup
	short_command allstatsup
	short_command effect0xa5
	short_command raisesubnoanim
	short_command lowersubnoanim
	short_command effect0xa8
	short_command clearmissdamage
	short_command movedelay
	short_command hittarget
	short_command tristatuschance
	short_command supereffectivelooptext
	short_command startloop
	short_command curl

	enum_start -1, -1
	short_command endmove
	short_command endturn
