	enum_start
	short_command tradeanim_next
	short_command tradeanim_show_givemon_data
	short_command tradeanim_show_getmon_data
	short_command tradeanim_enter_link_tube
	short_command tradeanim_04 ; unused
	short_command tradeanim_exit_link_tube
	short_command tradeanim_tube_to_ot
	short_command tradeanim_tube_to_ot_2 ; unused
	short_command tradeanim_tube_to_ot_3 ; unused
	short_command tradeanim_tube_to_ot_4 ; unused
	short_command tradeanim_tube_to_ot_5 ; unused
	short_command tradeanim_tube_to_ot_6 ; unused
	short_command tradeanim_tube_to_ot_7 ; unused
	short_command tradeanim_tube_to_ot_8 ; unused
	short_command tradeanim_tube_to_player
	short_command tradeanim_tube_to_player_2 ; unused
	short_command tradeanim_tube_to_player_3 ; unused
	short_command tradeanim_tube_to_player_4 ; unused
	short_command tradeanim_tube_to_player_5 ; unused
	short_command tradeanim_tube_to_player_6 ; unused
	short_command tradeanim_tube_to_player_7 ; unused
	short_command tradeanim_tube_to_player_8 ; unused
	short_command tradeanim_sent_to_ot_text
	short_command tradeanim_ot_bids_farewell
	short_command tradeanim_take_care_of_text
	short_command tradeanim_ot_sends_text_1
	short_command tradeanim_ot_sends_text_2
	short_command tradeanim_setup_givemon_scroll
	short_command tradeanim_do_givemon_scroll
	short_command tradeanim_1d
	short_command tradeanim_1e
	short_command tradeanim_scroll_out_right
	short_command tradeanim_scroll_out_right_2 ; unused
	short_command tradeanim_wait_80
	short_command tradeanim_wait_40
	short_command tradeanim_rocking_ball
	short_command tradeanim_drop_ball
	short_command tradeanim_wait_anim
	short_command tradeanim_wait_anim_2 ; unused
	short_command tradeanim_poof
	short_command tradeanim_bulge_through_tube
	short_command tradeanim_give_trademon_sfx
	short_command tradeanim_get_trademon_sfx
	short_command tradeanim_end
	short_command tradeanim_animate_frontpic
	short_command tradeanim_wait_96
	short_command tradeanim_wait_80_if_ot_egg
	short_command tradeanim_wait_180_if_ot_egg
