	enum_start
	short_command tradeanim_next
	short_command tradeanim_show_givemon_data
	short_command tradeanim_show_getmon_data
	short_command tradeanim_enter_link_tube
__enum__ set $5
	short_command tradeanim_exit_link_tube
	short_command tradeanim_tube_to_ot
__enum__ set $e
	short_command tradeanim_tube_to_player
__enum__ set $16
	short_command tradeanim_sent_to_ot_text
	short_command tradeanim_ot_bids_farewell
	short_command tradeanim_take_care_of_text
	short_command tradeanim_ot_sends_text_1
	short_command tradeanim_ot_sends_text_2
	short_command tradeanim_setup_givemon_scroll
	short_command tradeanim_do_givemon_scroll
	short_command tradeanim_1d
	short_command tradeanim_1e
	short_command tradeanim_scroll_out_right
__enum__ set $21
	short_command tradeanim_wait_80
	short_command tradeanim_wait_40
	short_command tradeanim_rocking_ball
	short_command tradeanim_drop_ball
	short_command tradeanim_wait_anim
__enum__ set $27
	short_command tradeanim_poof
	short_command tradeanim_bulge_through_tube
	short_command tradeanim_give_trademon_sfx
	short_command tradeanim_get_trademon_sfx
	short_command tradeanim_end
	short_command tradeanim_animate_frontpic
	short_command tradeanim_wait_96
	short_command tradeanim_wait_80_if_ot_egg
	short_command tradeanim_wait_180_if_ot_egg
