Icons:
NullIcon:
PoliwagIcon:      INCBIN "gfx/icons/poliwag.2bpp" ; 0x8ec0d
JigglypuffIcon:   INCBIN "gfx/icons/jigglypuff.2bpp" ; 0x8ec8d
DiglettIcon:      INCBIN "gfx/icons/diglett.2bpp" ; 0x8ed0d
PikachuIcon:      INCBIN "gfx/icons/pikachu.2bpp" ; 0x8ed8d
StaryuIcon:       INCBIN "gfx/icons/staryu.2bpp" ; 0x8ee0d
FishIcon:         INCBIN "gfx/icons/fish.2bpp" ; 0x8ee8d
BirdIcon:         INCBIN "gfx/icons/bird.2bpp" ; 0x8ef0d
MonsterIcon:      INCBIN "gfx/icons/monster.2bpp" ; 0x8ef8d
ClefairyIcon:     INCBIN "gfx/icons/clefairy.2bpp" ; 0x8f00d
OddishIcon:       INCBIN "gfx/icons/oddish.2bpp" ; 0x8f08d
BugIcon:          INCBIN "gfx/icons/bug.2bpp" ; 0x8f10d
GhostIcon:        INCBIN "gfx/icons/ghost.2bpp" ; 0x8f18d
LaprasIcon:       INCBIN "gfx/icons/lapras.2bpp" ; 0x8f20d
HumanshapeIcon:   INCBIN "gfx/icons/humanshape.2bpp" ; 0x8f28d
FoxIcon:          INCBIN "gfx/icons/fox.2bpp" ; 0x8f30d
EquineIcon:       INCBIN "gfx/icons/equine.2bpp" ; 0x8f38d
ShellIcon:        INCBIN "gfx/icons/shell.2bpp" ; 0x8f40d
BlobIcon:         INCBIN "gfx/icons/blob.2bpp" ; 0x8f48d
SerpentIcon:      INCBIN "gfx/icons/serpent.2bpp" ; 0x8f50d
VoltorbIcon:      INCBIN "gfx/icons/voltorb.2bpp" ; 0x8f58d
SquirtleIcon:     INCBIN "gfx/icons/squirtle.2bpp" ; 0x8f60d
BulbasaurIcon:    INCBIN "gfx/icons/bulbasaur.2bpp" ; 0x8f68d
CharmanderIcon:   INCBIN "gfx/icons/charmander.2bpp" ; 0x8f70d
CaterpillarIcon:  INCBIN "gfx/icons/caterpillar.2bpp" ; 0x8f78d
UnownIcon:        INCBIN "gfx/icons/unown.2bpp" ; 0x8f80d
GeodudeIcon:      INCBIN "gfx/icons/geodude.2bpp" ; 0x8f88d
FighterIcon:      INCBIN "gfx/icons/fighter.2bpp" ; 0x8f90d
EggIcon:          INCBIN "gfx/icons/egg.2bpp" ; 0x8f98d
JellyfishIcon:    INCBIN "gfx/icons/jellyfish.2bpp" ; 0x8fa0d
MothIcon:         INCBIN "gfx/icons/moth.2bpp" ; 0x8fa8d
BatIcon:          INCBIN "gfx/icons/bat.2bpp" ; 0x8fb0d
SnorlaxIcon:      INCBIN "gfx/icons/snorlax.2bpp" ; 0x8fb8d
HoOhIcon:         INCBIN "gfx/icons/ho_oh.2bpp" ; 0x8fc0d
LugiaIcon:        INCBIN "gfx/icons/lugia.2bpp" ; 0x8fc8d
GyaradosIcon:     INCBIN "gfx/icons/gyarados.2bpp" ; 0x8fd0d
SlowpokeIcon:     INCBIN "gfx/icons/slowpoke.2bpp" ; 0x8fd8d
SudowoodoIcon:    INCBIN "gfx/icons/sudowoodo.2bpp" ; 0x8fe0d
BigmonIcon:       INCBIN "gfx/icons/bigmon.2bpp" ; 0x8fe8d
