INCLUDE "includes.asm"


SECTION "Pic Pointers", ROMX, BANK[PIC_POINTERS]

PicPointers:
INCLUDE "gfx/pics/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX, BANK[UNOWN_PIC_POINTERS]

UnownPicPointers:
INCLUDE "gfx/pics/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX, BANK[TRAINER_PIC_POINTERS]

TrainerPicPointers:
INCLUDE "gfx/pics/trainer_pic_pointers.asm"



SECTION "Pics 1", ROMX, BANK[PICS_1]

HoOhFrontpic:        INCBIN "gfx/pics/250/front.7x7.2bpp.lz"
MachampFrontpic:     INCBIN "gfx/pics/068/front.7x7.2bpp.lz"
NinetalesFrontpic:   INCBIN "gfx/pics/038/front.7x7.2bpp.lz"
FeraligatrFrontpic:  INCBIN "gfx/pics/160/front.7x7.2bpp.lz"
NidokingFrontpic:    INCBIN "gfx/pics/034/front.7x7.2bpp.lz"
RaikouFrontpic:      INCBIN "gfx/pics/243/front.7x7.2bpp.lz"
LugiaFrontpic:       INCBIN "gfx/pics/249/front.7x7.2bpp.lz"
ArticunoFrontpic:    INCBIN "gfx/pics/144/front.7x7.2bpp.lz"
TaurosFrontpic:      INCBIN "gfx/pics/128/front.7x7.2bpp.lz"
VenusaurFrontpic:    INCBIN "gfx/pics/003/front.7x7.2bpp.lz"
EnteiFrontpic:       INCBIN "gfx/pics/244/front.7x7.2bpp.lz"
SuicuneFrontpic:     INCBIN "gfx/pics/245/front.7x7.2bpp.lz"
TyphlosionFrontpic:  INCBIN "gfx/pics/157/front.7x7.2bpp.lz"
; 123ffa


SECTION "Pics 2", ROMX, BANK[PICS_2]

BlastoiseFrontpic:   INCBIN "gfx/pics/009/front.7x7.2bpp.lz"
RapidashFrontpic:    INCBIN "gfx/pics/078/front.7x7.2bpp.lz"
MeganiumFrontpic:    INCBIN "gfx/pics/154/front.7x7.2bpp.lz"
NidoqueenFrontpic:   INCBIN "gfx/pics/031/front.7x7.2bpp.lz"
HitmonleeFrontpic:   INCBIN "gfx/pics/106/front.7x7.2bpp.lz"
ScizorFrontpic:      INCBIN "gfx/pics/212/front.7x7.2bpp.lz"
BeedrillFrontpic:    INCBIN "gfx/pics/015/front.7x7.2bpp.lz"
ArcanineFrontpic:    INCBIN "gfx/pics/059/front.7x7.2bpp.lz"
TyranitarFrontpic:   INCBIN "gfx/pics/248/front.7x7.2bpp.lz"
MoltresFrontpic:     INCBIN "gfx/pics/146/front.7x7.2bpp.lz"
ZapdosFrontpic:      INCBIN "gfx/pics/145/front.7x7.2bpp.lz"
ArbokFrontpic:       INCBIN "gfx/pics/024/front.7x7.2bpp.lz"
MewtwoFrontpic:      INCBIN "gfx/pics/150/front.7x7.2bpp.lz"
FearowFrontpic:      INCBIN "gfx/pics/022/front.7x7.2bpp.lz"
CharizardFrontpic:   INCBIN "gfx/pics/006/front.7x7.2bpp.lz"
QuilavaFrontpic:     INCBIN "gfx/pics/156/front.6x6.2bpp.lz"
; 127ffe


SECTION "Pics 3", ROMX, BANK[PICS_3]

SteelixFrontpic:     INCBIN "gfx/pics/208/front.7x7.2bpp.lz"
AlakazamFrontpic:    INCBIN "gfx/pics/065/front.7x7.2bpp.lz"
GyaradosFrontpic:    INCBIN "gfx/pics/130/front.7x7.2bpp.lz"
KangaskhanFrontpic:  INCBIN "gfx/pics/115/front.7x7.2bpp.lz"
RhydonFrontpic:      INCBIN "gfx/pics/112/front.7x7.2bpp.lz"
GolduckFrontpic:     INCBIN "gfx/pics/055/front.7x7.2bpp.lz"
RhyhornFrontpic:     INCBIN "gfx/pics/111/front.7x7.2bpp.lz"
PidgeotFrontpic:     INCBIN "gfx/pics/018/front.7x7.2bpp.lz"
SlowbroFrontpic:     INCBIN "gfx/pics/080/front.7x7.2bpp.lz"
ButterfreeFrontpic:  INCBIN "gfx/pics/012/front.7x7.2bpp.lz"
WeezingFrontpic:     INCBIN "gfx/pics/110/front.7x7.2bpp.lz"
CloysterFrontpic:    INCBIN "gfx/pics/091/front.7x7.2bpp.lz"
SkarmoryFrontpic:    INCBIN "gfx/pics/227/front.7x7.2bpp.lz"
DewgongFrontpic:     INCBIN "gfx/pics/087/front.7x7.2bpp.lz"
VictreebelFrontpic:  INCBIN "gfx/pics/071/front.7x7.2bpp.lz"
RaichuFrontpic:      INCBIN "gfx/pics/026/front.7x7.2bpp.lz"
PrimeapeFrontpic:    INCBIN "gfx/pics/057/front.7x7.2bpp.lz"
OmastarBackpic:      INCBIN "gfx/pics/139/back.6x6.2bpp.lz"
; 12bffe


SECTION "Pics 4", ROMX, BANK[PICS_4]

DodrioFrontpic:      INCBIN "gfx/pics/085/front.7x7.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pics/199/front.7x7.2bpp.lz"
HitmontopFrontpic:   INCBIN "gfx/pics/237/front.7x7.2bpp.lz"
OnixFrontpic:        INCBIN "gfx/pics/095/front.7x7.2bpp.lz"
BlisseyFrontpic:     INCBIN "gfx/pics/242/front.7x7.2bpp.lz"
MachokeFrontpic:     INCBIN "gfx/pics/067/front.7x7.2bpp.lz"
DragoniteFrontpic:   INCBIN "gfx/pics/149/front.7x7.2bpp.lz"
PoliwrathFrontpic:   INCBIN "gfx/pics/062/front.7x7.2bpp.lz"
ScytherFrontpic:     INCBIN "gfx/pics/123/front.7x7.2bpp.lz"
AerodactylFrontpic:  INCBIN "gfx/pics/142/front.7x7.2bpp.lz"
SeakingFrontpic:     INCBIN "gfx/pics/119/front.7x7.2bpp.lz"
MukFrontpic:         INCBIN "gfx/pics/089/front.7x7.2bpp.lz"
CroconawFrontpic:    INCBIN "gfx/pics/159/front.6x6.2bpp.lz"
HypnoFrontpic:       INCBIN "gfx/pics/097/front.7x7.2bpp.lz"
NidorinoFrontpic:    INCBIN "gfx/pics/033/front.6x6.2bpp.lz"
SandslashFrontpic:   INCBIN "gfx/pics/028/front.6x6.2bpp.lz"
JolteonFrontpic:     INCBIN "gfx/pics/135/front.6x6.2bpp.lz"
DonphanFrontpic:     INCBIN "gfx/pics/232/front.7x7.2bpp.lz"
PinsirFrontpic:      INCBIN "gfx/pics/127/front.7x7.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pics/201e/front.5x5.2bpp.lz"
; 130000


SECTION "Pics 5", ROMX, BANK[PICS_5]

GolbatFrontpic:      INCBIN "gfx/pics/042/front.7x7.2bpp.lz"
KinglerFrontpic:     INCBIN "gfx/pics/099/front.7x7.2bpp.lz"
ExeggcuteFrontpic:   INCBIN "gfx/pics/102/front.7x7.2bpp.lz"
MagcargoFrontpic:    INCBIN "gfx/pics/219/front.6x6.2bpp.lz"
PersianFrontpic:     INCBIN "gfx/pics/053/front.7x7.2bpp.lz"
StantlerFrontpic:    INCBIN "gfx/pics/234/front.7x7.2bpp.lz"
RaticateFrontpic:    INCBIN "gfx/pics/020/front.6x6.2bpp.lz"
VenomothFrontpic:    INCBIN "gfx/pics/049/front.7x7.2bpp.lz"
PolitoedFrontpic:    INCBIN "gfx/pics/186/front.7x7.2bpp.lz"
ElectabuzzFrontpic:  INCBIN "gfx/pics/125/front.6x6.2bpp.lz"
MantineFrontpic:     INCBIN "gfx/pics/226/front.7x7.2bpp.lz"
LickitungFrontpic:   INCBIN "gfx/pics/108/front.7x7.2bpp.lz"
KingdraFrontpic:     INCBIN "gfx/pics/230/front.7x7.2bpp.lz"
CharmeleonFrontpic:  INCBIN "gfx/pics/005/front.6x6.2bpp.lz"
KadabraFrontpic:     INCBIN "gfx/pics/064/front.6x6.2bpp.lz"
ExeggutorFrontpic:   INCBIN "gfx/pics/103/front.7x7.2bpp.lz"
GastlyFrontpic:      INCBIN "gfx/pics/092/front.7x7.2bpp.lz"
AzumarillFrontpic:   INCBIN "gfx/pics/184/front.7x7.2bpp.lz"
ParasectFrontpic:    INCBIN "gfx/pics/047/front.7x7.2bpp.lz"
MrMimeFrontpic:      INCBIN "gfx/pics/122/front.6x6.2bpp.lz"
HeracrossFrontpic:   INCBIN "gfx/pics/214/front.6x6.2bpp.lz"
; 133fff


SECTION "Pics 6", ROMX, BANK[PICS_6]

AriadosFrontpic:     INCBIN "gfx/pics/168/front.7x7.2bpp.lz"
NoctowlFrontpic:     INCBIN "gfx/pics/164/front.7x7.2bpp.lz"
WartortleFrontpic:   INCBIN "gfx/pics/008/front.6x6.2bpp.lz"
LaprasFrontpic:      INCBIN "gfx/pics/131/front.7x7.2bpp.lz"
GolemFrontpic:       INCBIN "gfx/pics/076/front.6x6.2bpp.lz"
PoliwhirlFrontpic:   INCBIN "gfx/pics/061/front.6x6.2bpp.lz"
UrsaringFrontpic:    INCBIN "gfx/pics/217/front.7x7.2bpp.lz"
HoundoomFrontpic:    INCBIN "gfx/pics/229/front.7x7.2bpp.lz"
KabutopsFrontpic:    INCBIN "gfx/pics/141/front.6x6.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pics/181/front.7x7.2bpp.lz"
NidorinaFrontpic:    INCBIN "gfx/pics/030/front.6x6.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pics/136/front.6x6.2bpp.lz"
FarfetchDFrontpic:   INCBIN "gfx/pics/083/front.6x6.2bpp.lz"
VileplumeFrontpic:   INCBIN "gfx/pics/045/front.7x7.2bpp.lz"
BayleefFrontpic:     INCBIN "gfx/pics/153/front.6x6.2bpp.lz"
MagmarFrontpic:      INCBIN "gfx/pics/126/front.6x6.2bpp.lz"
TentacruelFrontpic:  INCBIN "gfx/pics/073/front.6x6.2bpp.lz"
ElekidFrontpic:      INCBIN "gfx/pics/239/front.6x6.2bpp.lz"
JumpluffFrontpic:    INCBIN "gfx/pics/189/front.7x7.2bpp.lz"
MarowakFrontpic:     INCBIN "gfx/pics/105/front.6x6.2bpp.lz"
VulpixFrontpic:      INCBIN "gfx/pics/037/front.6x6.2bpp.lz"
GligarFrontpic:      INCBIN "gfx/pics/207/front.6x6.2bpp.lz"
DunsparceFrontpic:   INCBIN "gfx/pics/206/front.6x6.2bpp.lz"
; 137fff


SECTION "Pics 7", ROMX, BANK[PICS_7]

VaporeonFrontpic:    INCBIN "gfx/pics/134/front.6x6.2bpp.lz"
GirafarigFrontpic:   INCBIN "gfx/pics/203/front.7x7.2bpp.lz"
DrowzeeFrontpic:     INCBIN "gfx/pics/096/front.6x6.2bpp.lz"
SneaselFrontpic:     INCBIN "gfx/pics/215/front.6x6.2bpp.lz"
BellossomFrontpic:   INCBIN "gfx/pics/182/front.7x7.2bpp.lz"
SnorlaxFrontpic:     INCBIN "gfx/pics/143/front.7x7.2bpp.lz"
WigglytuffFrontpic:  INCBIN "gfx/pics/040/front.6x6.2bpp.lz"
YanmaFrontpic:       INCBIN "gfx/pics/193/front.6x6.2bpp.lz"
SmeargleFrontpic:    INCBIN "gfx/pics/235/front.7x7.2bpp.lz"
ClefableFrontpic:    INCBIN "gfx/pics/036/front.6x6.2bpp.lz"
PonytaFrontpic:      INCBIN "gfx/pics/077/front.6x6.2bpp.lz"
MurkrowFrontpic:     INCBIN "gfx/pics/198/front.6x6.2bpp.lz"
GravelerFrontpic:    INCBIN "gfx/pics/075/front.6x6.2bpp.lz"
StarmieFrontpic:     INCBIN "gfx/pics/121/front.6x6.2bpp.lz"
PidgeottoFrontpic:   INCBIN "gfx/pics/017/front.6x6.2bpp.lz"
LedybaFrontpic:      INCBIN "gfx/pics/165/front.6x6.2bpp.lz"
GengarFrontpic:      INCBIN "gfx/pics/094/front.6x6.2bpp.lz"
OmastarFrontpic:     INCBIN "gfx/pics/139/front.6x6.2bpp.lz"
PiloswineFrontpic:   INCBIN "gfx/pics/221/front.6x6.2bpp.lz"
DugtrioFrontpic:     INCBIN "gfx/pics/051/front.7x7.2bpp.lz"
MagnetonFrontpic:    INCBIN "gfx/pics/082/front.6x6.2bpp.lz"
DragonairFrontpic:   INCBIN "gfx/pics/148/front.6x6.2bpp.lz"
ForretressFrontpic:  INCBIN "gfx/pics/205/front.7x7.2bpp.lz"
TogeticFrontpic:     INCBIN "gfx/pics/176/front.7x7.2bpp.lz"
KangaskhanBackpic:   INCBIN "gfx/pics/115/back.6x6.2bpp.lz"
; 13c000


SECTION "Pics 8", ROMX, BANK[PICS_8]

SeelFrontpic:        INCBIN "gfx/pics/086/front.6x6.2bpp.lz"
CrobatFrontpic:      INCBIN "gfx/pics/169/front.7x7.2bpp.lz"
ChanseyFrontpic:     INCBIN "gfx/pics/113/front.6x6.2bpp.lz"
TangelaFrontpic:     INCBIN "gfx/pics/114/front.6x6.2bpp.lz"
SnubbullFrontpic:    INCBIN "gfx/pics/209/front.6x6.2bpp.lz"
GranbullFrontpic:    INCBIN "gfx/pics/210/front.6x6.2bpp.lz"
MiltankFrontpic:     INCBIN "gfx/pics/241/front.6x6.2bpp.lz"
HaunterFrontpic:     INCBIN "gfx/pics/093/front.6x6.2bpp.lz"
SunfloraFrontpic:    INCBIN "gfx/pics/192/front.6x6.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pics/197/front.6x6.2bpp.lz"
ChikoritaFrontpic:   INCBIN "gfx/pics/152/front.5x5.2bpp.lz"
GoldeenFrontpic:     INCBIN "gfx/pics/118/front.6x6.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pics/196/front.6x6.2bpp.lz"
XatuFrontpic:        INCBIN "gfx/pics/178/front.6x6.2bpp.lz"
MewFrontpic:         INCBIN "gfx/pics/151/front.5x5.2bpp.lz"
OctilleryFrontpic:   INCBIN "gfx/pics/224/front.6x6.2bpp.lz"
JynxFrontpic:        INCBIN "gfx/pics/124/front.6x6.2bpp.lz"
WobbuffetFrontpic:   INCBIN "gfx/pics/202/front.6x6.2bpp.lz"
DelibirdFrontpic:    INCBIN "gfx/pics/225/front.6x6.2bpp.lz"
LedianFrontpic:      INCBIN "gfx/pics/166/front.6x6.2bpp.lz"
GloomFrontpic:       INCBIN "gfx/pics/044/front.6x6.2bpp.lz"
FlaaffyFrontpic:     INCBIN "gfx/pics/180/front.6x6.2bpp.lz"
IvysaurFrontpic:     INCBIN "gfx/pics/002/front.6x6.2bpp.lz"
FurretFrontpic:      INCBIN "gfx/pics/162/front.6x6.2bpp.lz"
CyndaquilFrontpic:   INCBIN "gfx/pics/155/front.5x5.2bpp.lz"
HitmonchanFrontpic:  INCBIN "gfx/pics/107/front.6x6.2bpp.lz"
QuagsireFrontpic:    INCBIN "gfx/pics/195/front.6x6.2bpp.lz"
; 13fff7


SECTION "Pics 9", ROMX, BANK[PICS_9]

EkansFrontpic:       INCBIN "gfx/pics/023/front.5x5.2bpp.lz"
SudowoodoFrontpic:   INCBIN "gfx/pics/185/front.6x6.2bpp.lz"
PikachuFrontpic:     INCBIN "gfx/pics/025/front.5x5.2bpp.lz"
SeadraFrontpic:      INCBIN "gfx/pics/117/front.6x6.2bpp.lz"
MagbyFrontpic:       INCBIN "gfx/pics/240/front.6x6.2bpp.lz"
WeepinbellFrontpic:  INCBIN "gfx/pics/070/front.6x6.2bpp.lz"
TotodileFrontpic:    INCBIN "gfx/pics/158/front.5x5.2bpp.lz"
CorsolaFrontpic:     INCBIN "gfx/pics/222/front.6x6.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/047.lz"
MachopFrontpic:      INCBIN "gfx/pics/066/front.5x5.2bpp.lz"
ChinchouFrontpic:    INCBIN "gfx/pics/170/front.6x6.2bpp.lz"
RattataFrontpic:     INCBIN "gfx/pics/019/front.5x5.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/015.lz"
SpearowFrontpic:     INCBIN "gfx/pics/021/front.5x5.2bpp.lz"
MagikarpFrontpic:    INCBIN "gfx/pics/129/front.6x6.2bpp.lz"
CharmanderFrontpic:  INCBIN "gfx/pics/004/front.5x5.2bpp.lz"
CuboneFrontpic:      INCBIN "gfx/pics/104/front.5x5.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/049.lz"
BikerPic:            INCBIN "gfx/trainers/044.lz"
NidoranMFrontpic:    INCBIN "gfx/pics/032/front.5x5.2bpp.lz"
PorygonFrontpic:     INCBIN "gfx/pics/137/front.6x6.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/012.lz"
GrimerFrontpic:      INCBIN "gfx/pics/088/front.5x5.2bpp.lz"
StaryuFrontpic:      INCBIN "gfx/pics/120/front.6x6.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/043.lz"
MeowthFrontpic:      INCBIN "gfx/pics/052/front.5x5.2bpp.lz"
Porygon2Frontpic:    INCBIN "gfx/pics/233/front.6x6.2bpp.lz"
SandshrewFrontpic:   INCBIN "gfx/pics/027/front.5x5.2bpp.lz"
NidoranFFrontpic:    INCBIN "gfx/pics/029/front.5x5.2bpp.lz"
PidgeyFrontpic:      INCBIN "gfx/pics/016/front.5x5.2bpp.lz"
ParasectBackpic:     INCBIN "gfx/pics/047/back.6x6.2bpp.lz"
; 144000


SECTION "Pics 10", ROMX, BANK[PICS_10]

MisdreavusFrontpic:  INCBIN "gfx/pics/200/front.6x6.2bpp.lz"
HoundourFrontpic:    INCBIN "gfx/pics/228/front.6x6.2bpp.lz"
MankeyFrontpic:      INCBIN "gfx/pics/056/front.5x5.2bpp.lz"
CelebiFrontpic:      INCBIN "gfx/pics/251/front.5x5.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/056.lz"
PinecoFrontpic:      INCBIN "gfx/pics/204/front.5x5.2bpp.lz"
KrabbyFrontpic:      INCBIN "gfx/pics/098/front.5x5.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/036.lz"
JigglypuffFrontpic:  INCBIN "gfx/pics/039/front.5x5.2bpp.lz"
ParasFrontpic:       INCBIN "gfx/pics/046/front.5x5.2bpp.lz"
NidokingBackpic:     INCBIN "gfx/pics/034/back.6x6.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/058.lz"
BoarderPic:          INCBIN "gfx/trainers/057.lz"
PsyduckFrontpic:     INCBIN "gfx/pics/054/front.5x5.2bpp.lz"
SquirtleFrontpic:    INCBIN "gfx/pics/007/front.5x5.2bpp.lz"
MachampBackpic:      INCBIN "gfx/pics/068/back.6x6.2bpp.lz"
KoffingFrontpic:     INCBIN "gfx/pics/109/front.6x6.2bpp.lz"
VenonatFrontpic:     INCBIN "gfx/pics/048/front.5x5.2bpp.lz"
ExeggutorBackpic:    INCBIN "gfx/pics/103/back.6x6.2bpp.lz"
LanturnFrontpic:     INCBIN "gfx/pics/171/front.6x6.2bpp.lz"
TyrogueFrontpic:     INCBIN "gfx/pics/236/front.5x5.2bpp.lz"
SkiploomFrontpic:    INCBIN "gfx/pics/188/front.6x6.2bpp.lz"
MareepFrontpic:      INCBIN "gfx/pics/179/front.5x5.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/006.lz"
EeveeFrontpic:       INCBIN "gfx/pics/133/front.5x5.2bpp.lz"
ButterfreeBackpic:   INCBIN "gfx/pics/012/back.6x6.2bpp.lz"
ZubatFrontpic:       INCBIN "gfx/pics/041/front.5x5.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/059.lz"
AlakazamBackpic:     INCBIN "gfx/pics/065/back.6x6.2bpp.lz"
AipomFrontpic:       INCBIN "gfx/pics/190/front.5x5.2bpp.lz"
AbraFrontpic:        INCBIN "gfx/pics/063/front.5x5.2bpp.lz"
HitmontopBackpic:    INCBIN "gfx/pics/237/back.6x6.2bpp.lz"
CloysterBackpic:     INCBIN "gfx/pics/091/back.6x6.2bpp.lz"
HoothootFrontpic:    INCBIN "gfx/pics/163/front.5x5.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pics/201f/back.6x6.2bpp.lz"
; 148000


SECTION "Pics 11", ROMX, BANK[PICS_11]

DodrioBackpic:       INCBIN "gfx/pics/085/back.6x6.2bpp.lz"
ClefairyFrontpic:    INCBIN "gfx/pics/035/front.5x5.2bpp.lz"
SlugmaFrontpic:      INCBIN "gfx/pics/218/front.5x5.2bpp.lz"
GrowlitheFrontpic:   INCBIN "gfx/pics/058/front.5x5.2bpp.lz"
SlowpokeFrontpic:    INCBIN "gfx/pics/079/front.5x5.2bpp.lz"
SmoochumFrontpic:    INCBIN "gfx/pics/238/front.5x5.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/048.lz"
MarillFrontpic:      INCBIN "gfx/pics/183/front.5x5.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/042.lz"
PokefanfPic:         INCBIN "gfx/trainers/061.lz"
VenomothBackpic:     INCBIN "gfx/pics/049/back.6x6.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/007.lz"
PokemaniacPic:       INCBIN "gfx/trainers/029.lz"
OmanyteFrontpic:     INCBIN "gfx/pics/138/front.5x5.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/032.lz"
PupitarFrontpic:     INCBIN "gfx/pics/247/front.6x6.2bpp.lz"
BellsproutFrontpic:  INCBIN "gfx/pics/069/front.5x5.2bpp.lz"
ShellderFrontpic:    INCBIN "gfx/pics/090/front.5x5.2bpp.lz"
TentacoolFrontpic:   INCBIN "gfx/pics/072/front.5x5.2bpp.lz"
CleffaFrontpic:      INCBIN "gfx/pics/173/front.5x5.2bpp.lz"
GyaradosBackpic:     INCBIN "gfx/pics/130/back.6x6.2bpp.lz"
NinetalesBackpic:    INCBIN "gfx/pics/038/back.6x6.2bpp.lz"
YanmaBackpic:        INCBIN "gfx/pics/193/back.6x6.2bpp.lz"
PinsirBackpic:       INCBIN "gfx/pics/127/back.6x6.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/024.lz"
ClefableBackpic:     INCBIN "gfx/pics/036/back.6x6.2bpp.lz"
DoduoFrontpic:       INCBIN "gfx/pics/084/front.5x5.2bpp.lz"
FeraligatrBackpic:   INCBIN "gfx/pics/160/back.6x6.2bpp.lz"
DratiniFrontpic:     INCBIN "gfx/pics/147/front.5x5.2bpp.lz"
MagnetonBackpic:     INCBIN "gfx/pics/082/back.6x6.2bpp.lz"
QwilfishFrontpic:    INCBIN "gfx/pics/211/front.5x5.2bpp.lz"
SuicuneBackpic:      INCBIN "gfx/pics/245/back.6x6.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pics/199/back.6x6.2bpp.lz"
ElekidBackpic:       INCBIN "gfx/pics/239/back.6x6.2bpp.lz"
CelebiBackpic:       INCBIN "gfx/pics/251/back.6x6.2bpp.lz"
KrabbyBackpic:       INCBIN "gfx/pics/098/back.6x6.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/035.lz"
SnorlaxBackpic:      INCBIN "gfx/pics/143/back.6x6.2bpp.lz"
; 14bffb


SECTION "Pics 12", ROMX, BANK[PICS_12]

VenusaurBackpic:     INCBIN "gfx/pics/003/back.6x6.2bpp.lz"
MoltresBackpic:      INCBIN "gfx/pics/146/back.6x6.2bpp.lz"
SunfloraBackpic:     INCBIN "gfx/pics/192/back.6x6.2bpp.lz"
PhanpyFrontpic:      INCBIN "gfx/pics/231/front.5x5.2bpp.lz"
RhydonBackpic:       INCBIN "gfx/pics/112/back.6x6.2bpp.lz"
LarvitarFrontpic:    INCBIN "gfx/pics/246/front.5x5.2bpp.lz"
TyranitarBackpic:    INCBIN "gfx/pics/248/back.6x6.2bpp.lz"
SandslashBackpic:    INCBIN "gfx/pics/028/back.6x6.2bpp.lz"
SeadraBackpic:       INCBIN "gfx/pics/117/back.6x6.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/060.lz"
FarfetchDBackpic:    INCBIN "gfx/pics/083/back.6x6.2bpp.lz"
NidoranMBackpic:     INCBIN "gfx/pics/032/back.6x6.2bpp.lz"
LedybaBackpic:       INCBIN "gfx/pics/165/back.6x6.2bpp.lz"
CyndaquilBackpic:    INCBIN "gfx/pics/155/back.6x6.2bpp.lz"
BayleefBackpic:      INCBIN "gfx/pics/153/back.6x6.2bpp.lz"
OddishFrontpic:      INCBIN "gfx/pics/043/front.5x5.2bpp.lz"
RapidashBackpic:     INCBIN "gfx/pics/078/back.6x6.2bpp.lz"
DoduoBackpic:        INCBIN "gfx/pics/084/back.6x6.2bpp.lz"
HoppipFrontpic:      INCBIN "gfx/pics/187/front.5x5.2bpp.lz"
MankeyBackpic:       INCBIN "gfx/pics/056/back.6x6.2bpp.lz"
MagmarBackpic:       INCBIN "gfx/pics/126/back.6x6.2bpp.lz"
HypnoBackpic:        INCBIN "gfx/pics/097/back.6x6.2bpp.lz"
QuilavaBackpic:      INCBIN "gfx/pics/156/back.6x6.2bpp.lz"
CroconawBackpic:     INCBIN "gfx/pics/159/back.6x6.2bpp.lz"
SandshrewBackpic:    INCBIN "gfx/pics/027/back.6x6.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/039.lz"
BeautyPic:           INCBIN "gfx/trainers/028.lz"
ShellderBackpic:     INCBIN "gfx/pics/090/back.6x6.2bpp.lz"
ZubatBackpic:        INCBIN "gfx/pics/041/back.6x6.2bpp.lz"
TeddiursaFrontpic:   INCBIN "gfx/pics/216/front.5x5.2bpp.lz"
CuboneBackpic:       INCBIN "gfx/pics/104/back.6x6.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/030.lz"
GloomBackpic:        INCBIN "gfx/pics/044/back.6x6.2bpp.lz"
MagcargoBackpic:     INCBIN "gfx/pics/219/back.6x6.2bpp.lz"
KabutopsBackpic:     INCBIN "gfx/pics/141/back.6x6.2bpp.lz"
BeedrillBackpic:     INCBIN "gfx/pics/015/back.6x6.2bpp.lz"
ArcanineBackpic:     INCBIN "gfx/pics/059/back.6x6.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pics/136/back.6x6.2bpp.lz"
GoldeenBackpic:      INCBIN "gfx/pics/118/back.6x6.2bpp.lz"
BulbasaurFrontpic:   INCBIN "gfx/pics/001/front.5x5.2bpp.lz"
StarmieBackpic:      INCBIN "gfx/pics/121/back.6x6.2bpp.lz"
; 150000


SECTION "Pics 13", ROMX, BANK[PICS_13]

OmanyteBackpic:      INCBIN "gfx/pics/138/back.6x6.2bpp.lz"
PidgeyBackpic:       INCBIN "gfx/pics/016/back.6x6.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/019.lz"
QwilfishBackpic:     INCBIN "gfx/pics/211/back.6x6.2bpp.lz"
GligarBackpic:       INCBIN "gfx/pics/207/back.6x6.2bpp.lz"
TyphlosionBackpic:   INCBIN "gfx/pics/157/back.6x6.2bpp.lz"
CharmeleonBackpic:   INCBIN "gfx/pics/005/back.6x6.2bpp.lz"
NidoqueenBackpic:    INCBIN "gfx/pics/031/back.6x6.2bpp.lz"
PichuFrontpic:       INCBIN "gfx/pics/172/front.5x5.2bpp.lz"
ElectabuzzBackpic:   INCBIN "gfx/pics/125/back.6x6.2bpp.lz"
LedianBackpic:       INCBIN "gfx/pics/166/back.6x6.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pics/247/back.6x6.2bpp.lz"
HeracrossBackpic:    INCBIN "gfx/pics/214/back.6x6.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pics/201d/front.5x5.2bpp.lz"
MiltankBackpic:      INCBIN "gfx/pics/241/back.6x6.2bpp.lz"
SteelixBackpic:      INCBIN "gfx/pics/208/back.6x6.2bpp.lz"
PersianBackpic:      INCBIN "gfx/pics/053/back.6x6.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/018.lz"
TeacherPic:          INCBIN "gfx/trainers/033.lz"
EggPic:              INCBIN "gfx/pics/egg/front.5x5.2bpp.lz"
EeveeBackpic:        INCBIN "gfx/pics/133/back.6x6.2bpp.lz"
ShuckleFrontpic:     INCBIN "gfx/pics/213/front.5x5.2bpp.lz"
PonytaBackpic:       INCBIN "gfx/pics/077/back.6x6.2bpp.lz"
RemoraidFrontpic:    INCBIN "gfx/pics/223/front.5x5.2bpp.lz"
PoliwagFrontpic:     INCBIN "gfx/pics/060/front.5x5.2bpp.lz"
OnixBackpic:         INCBIN "gfx/pics/095/back.6x6.2bpp.lz"
KoffingBackpic:      INCBIN "gfx/pics/109/back.6x6.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/023.lz"
FalknerPic:          INCBIN "gfx/trainers/000.lz"
KarenPic:            INCBIN "gfx/trainers/013.lz"
NidorinaBackpic:     INCBIN "gfx/pics/030/back.6x6.2bpp.lz"
TentacruelBackpic:   INCBIN "gfx/pics/073/back.6x6.2bpp.lz"
GrowlitheBackpic:    INCBIN "gfx/pics/058/back.6x6.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/014.lz"
MachokeBackpic:      INCBIN "gfx/pics/067/back.6x6.2bpp.lz"
RaichuBackpic:       INCBIN "gfx/pics/026/back.6x6.2bpp.lz"
PoliwrathBackpic:    INCBIN "gfx/pics/062/back.6x6.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/037.lz"
SunkernFrontpic:     INCBIN "gfx/pics/191/front.5x5.2bpp.lz"
NidorinoBackpic:     INCBIN "gfx/pics/033/back.6x6.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/066.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/027.lz"
ElectrodeFrontpic:   INCBIN "gfx/pics/101/front.5x5.2bpp.lz"
; 153fe3


SECTION "Pics 14", ROMX, BANK[PICS_14]

SudowoodoBackpic:    INCBIN "gfx/pics/185/back.6x6.2bpp.lz"
FlaaffyBackpic:      INCBIN "gfx/pics/180/back.6x6.2bpp.lz"
SentretFrontpic:     INCBIN "gfx/pics/161/front.6x6.2bpp.lz"
TogeticBackpic:      INCBIN "gfx/pics/176/back.6x6.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/002.lz"
MarowakBackpic:      INCBIN "gfx/pics/105/back.6x6.2bpp.lz"
GeodudeBackpic:      INCBIN "gfx/pics/074/back.6x6.2bpp.lz"
ScytherBackpic:      INCBIN "gfx/pics/123/back.6x6.2bpp.lz"
VileplumeBackpic:    INCBIN "gfx/pics/045/back.6x6.2bpp.lz"
HitmonchanBackpic:   INCBIN "gfx/pics/107/back.6x6.2bpp.lz"
JumpluffBackpic:     INCBIN "gfx/pics/189/back.6x6.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/026.lz"
BlastoiseBackpic:    INCBIN "gfx/pics/009/back.6x6.2bpp.lz"
MisdreavusBackpic:   INCBIN "gfx/pics/200/back.6x6.2bpp.lz"
TyrogueBackpic:      INCBIN "gfx/pics/236/back.6x6.2bpp.lz"
GeodudeFrontpic:     INCBIN "gfx/pics/074/front.5x5.2bpp.lz"
ScizorBackpic:       INCBIN "gfx/pics/212/back.6x6.2bpp.lz"
GirafarigBackpic:    INCBIN "gfx/pics/203/back.6x6.2bpp.lz"
StantlerBackpic:     INCBIN "gfx/pics/234/back.6x6.2bpp.lz"
SmeargleBackpic:     INCBIN "gfx/pics/235/back.6x6.2bpp.lz"
CharizardBackpic:    INCBIN "gfx/pics/006/back.6x6.2bpp.lz"
KadabraBackpic:      INCBIN "gfx/pics/064/back.6x6.2bpp.lz"
PrimeapeBackpic:     INCBIN "gfx/pics/057/back.6x6.2bpp.lz"
FurretBackpic:       INCBIN "gfx/pics/162/back.6x6.2bpp.lz"
WartortleBackpic:    INCBIN "gfx/pics/008/back.6x6.2bpp.lz"
ExeggcuteBackpic:    INCBIN "gfx/pics/102/back.6x6.2bpp.lz"
IgglybuffFrontpic:   INCBIN "gfx/pics/174/front.5x5.2bpp.lz"
RaticateBackpic:     INCBIN "gfx/pics/020/back.6x6.2bpp.lz"
VulpixBackpic:       INCBIN "gfx/pics/037/back.6x6.2bpp.lz"
EkansBackpic:        INCBIN "gfx/pics/023/back.6x6.2bpp.lz"
SeakingBackpic:      INCBIN "gfx/pics/119/back.6x6.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/046.lz"
PsyduckBackpic:      INCBIN "gfx/pics/054/back.6x6.2bpp.lz"
PikachuBackpic:      INCBIN "gfx/pics/025/back.6x6.2bpp.lz"
KabutoFrontpic:      INCBIN "gfx/pics/140/front.5x5.2bpp.lz"
MareepBackpic:       INCBIN "gfx/pics/179/back.6x6.2bpp.lz"
RemoraidBackpic:     INCBIN "gfx/pics/223/back.6x6.2bpp.lz"
DittoFrontpic:       INCBIN "gfx/pics/132/front.5x5.2bpp.lz"
KingdraBackpic:      INCBIN "gfx/pics/230/back.6x6.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/053.lz"
WooperFrontpic:      INCBIN "gfx/pics/194/front.5x5.2bpp.lz"
ClefairyBackpic:     INCBIN "gfx/pics/035/back.6x6.2bpp.lz"
VenonatBackpic:      INCBIN "gfx/pics/048/back.6x6.2bpp.lz"
BellossomBackpic:    INCBIN "gfx/pics/182/back.6x6.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/008.lz"
SwinubBackpic:       INCBIN "gfx/pics/220/back.6x6.2bpp.lz"
; 158000


SECTION "Pics 15", ROMX, BANK[PICS_15]

MewtwoBackpic:       INCBIN "gfx/pics/150/back.6x6.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/009.lz"
CalPic:              INCBIN "gfx/trainers/011.lz"
SwimmerfPic:         INCBIN "gfx/trainers/038.lz"
DiglettFrontpic:     INCBIN "gfx/pics/050/front.5x5.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/064.lz"
MukBackpic:          INCBIN "gfx/pics/089/back.6x6.2bpp.lz"
DelibirdBackpic:     INCBIN "gfx/pics/225/back.6x6.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/034.lz"
MagikarpBackpic:     INCBIN "gfx/pics/129/back.6x6.2bpp.lz"
AriadosBackpic:      INCBIN "gfx/pics/168/back.6x6.2bpp.lz"
SneaselBackpic:      INCBIN "gfx/pics/215/back.6x6.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pics/197/back.6x6.2bpp.lz"
MurkrowBackpic:      INCBIN "gfx/pics/198/back.6x6.2bpp.lz"
IvysaurBackpic:      INCBIN "gfx/pics/002/back.6x6.2bpp.lz"
SlowbroBackpic:      INCBIN "gfx/pics/080/back.6x6.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/051.lz"
GolduckBackpic:      INCBIN "gfx/pics/055/back.6x6.2bpp.lz"
WeezingBackpic:      INCBIN "gfx/pics/110/back.6x6.2bpp.lz"
EnteiBackpic:        INCBIN "gfx/pics/244/back.6x6.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/065.lz"
HorseaFrontpic:      INCBIN "gfx/pics/116/front.5x5.2bpp.lz"
PidgeotBackpic:      INCBIN "gfx/pics/018/back.6x6.2bpp.lz"
HoOhBackpic:         INCBIN "gfx/pics/250/back.6x6.2bpp.lz"
PoliwhirlBackpic:    INCBIN "gfx/pics/061/back.6x6.2bpp.lz"
MewBackpic:          INCBIN "gfx/pics/151/back.6x6.2bpp.lz"
MachopBackpic:       INCBIN "gfx/pics/066/back.6x6.2bpp.lz"
AbraBackpic:         INCBIN "gfx/pics/063/back.6x6.2bpp.lz"
AerodactylBackpic:   INCBIN "gfx/pics/142/back.6x6.2bpp.lz"
KakunaFrontpic:      INCBIN "gfx/pics/014/front.5x5.2bpp.lz"
DugtrioBackpic:      INCBIN "gfx/pics/051/back.6x6.2bpp.lz"
WeepinbellBackpic:   INCBIN "gfx/pics/070/back.6x6.2bpp.lz"
NidoranFBackpic:     INCBIN "gfx/pics/029/back.6x6.2bpp.lz"
GravelerBackpic:     INCBIN "gfx/pics/075/back.6x6.2bpp.lz"
AipomBackpic:        INCBIN "gfx/pics/190/back.6x6.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pics/196/back.6x6.2bpp.lz"
WeedleFrontpic:      INCBIN "gfx/pics/013/front.5x5.2bpp.lz"
TotodileBackpic:     INCBIN "gfx/pics/158/back.6x6.2bpp.lz"
SnubbullBackpic:     INCBIN "gfx/pics/209/back.6x6.2bpp.lz"
KinglerBackpic:      INCBIN "gfx/pics/099/back.6x6.2bpp.lz"
GengarBackpic:       INCBIN "gfx/pics/094/back.6x6.2bpp.lz"
RattataBackpic:      INCBIN "gfx/pics/019/back.6x6.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/021.lz"
WillPic:             INCBIN "gfx/trainers/010.lz"
SchoolboyPic:        INCBIN "gfx/trainers/022.lz"
MagnemiteFrontpic:   INCBIN "gfx/pics/081/front.5x5.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/020.lz"
JaninePic:           INCBIN "gfx/trainers/025.lz"
MagnemiteBackpic:    INCBIN "gfx/pics/081/back.6x6.2bpp.lz"
; 15bffa


SECTION "Pics 16", ROMX, BANK[PICS_16]

HoothootBackpic:     INCBIN "gfx/pics/163/back.6x6.2bpp.lz"
NoctowlBackpic:      INCBIN "gfx/pics/164/back.6x6.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/003.lz"
SlugmaBackpic:       INCBIN "gfx/pics/218/back.6x6.2bpp.lz"
KabutoBackpic:       INCBIN "gfx/pics/140/back.6x6.2bpp.lz"
VictreebelBackpic:   INCBIN "gfx/pics/071/back.6x6.2bpp.lz"
MeowthBackpic:       INCBIN "gfx/pics/052/back.6x6.2bpp.lz"
MeganiumBackpic:     INCBIN "gfx/pics/154/back.6x6.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/052.lz"
LickitungBackpic:    INCBIN "gfx/pics/108/back.6x6.2bpp.lz"
TogepiFrontpic:      INCBIN "gfx/pics/175/front.5x5.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/040.lz"
HaunterBackpic:      INCBIN "gfx/pics/093/back.6x6.2bpp.lz"
XatuBackpic:         INCBIN "gfx/pics/178/back.6x6.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/062.lz"
Porygon2Backpic:     INCBIN "gfx/pics/233/back.6x6.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/005.lz"
PinecoBackpic:       INCBIN "gfx/pics/204/back.6x6.2bpp.lz"
MetapodFrontpic:     INCBIN "gfx/pics/011/front.5x5.2bpp.lz"
SeelBackpic:         INCBIN "gfx/pics/086/back.6x6.2bpp.lz"
QuagsireBackpic:     INCBIN "gfx/pics/195/back.6x6.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/001.lz"
JolteonBackpic:      INCBIN "gfx/pics/135/back.6x6.2bpp.lz"
CaterpieFrontpic:    INCBIN "gfx/pics/010/front.5x5.2bpp.lz"
HoppipBackpic:       INCBIN "gfx/pics/187/back.6x6.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/063.lz"
GranbullBackpic:     INCBIN "gfx/pics/210/back.6x6.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/031.lz"
ExecutivemPic:       INCBIN "gfx/trainers/050.lz"
SpearowBackpic:      INCBIN "gfx/pics/021/back.6x6.2bpp.lz"
SunkernBackpic:      INCBIN "gfx/pics/191/back.6x6.2bpp.lz"
LaprasBackpic:       INCBIN "gfx/pics/131/back.6x6.2bpp.lz"
MagbyBackpic:        INCBIN "gfx/pics/240/back.6x6.2bpp.lz"
DragonairBackpic:    INCBIN "gfx/pics/148/back.6x6.2bpp.lz"
ZapdosBackpic:       INCBIN "gfx/pics/145/back.6x6.2bpp.lz"
ChikoritaBackpic:    INCBIN "gfx/pics/152/back.6x6.2bpp.lz"
CorsolaBackpic:      INCBIN "gfx/pics/222/back.6x6.2bpp.lz"
ChinchouBackpic:     INCBIN "gfx/pics/170/back.6x6.2bpp.lz"
ChanseyBackpic:      INCBIN "gfx/pics/113/back.6x6.2bpp.lz"
SkiploomBackpic:     INCBIN "gfx/pics/188/back.6x6.2bpp.lz"
SpinarakFrontpic:    INCBIN "gfx/pics/167/front.5x5.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/041.lz"
UnownWFrontpic:      INCBIN "gfx/pics/201w/front.5x5.2bpp.lz"
CharmanderBackpic:   INCBIN "gfx/pics/004/back.6x6.2bpp.lz"
RhyhornBackpic:      INCBIN "gfx/pics/111/back.6x6.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pics/201c/front.5x5.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/017.lz"
BlainePic:           INCBIN "gfx/trainers/045.lz"
UnownZFrontpic:      INCBIN "gfx/pics/201z/front.5x5.2bpp.lz"
SwinubFrontpic:      INCBIN "gfx/pics/220/front.5x5.2bpp.lz"
LarvitarBackpic:     INCBIN "gfx/pics/246/back.6x6.2bpp.lz"
PorygonBackpic:      INCBIN "gfx/pics/137/back.6x6.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pics/201h/back.6x6.2bpp.lz"
; 15ffff


SECTION "Pics 17", ROMX, BANK[PICS_17]

ParasBackpic:        INCBIN "gfx/pics/046/back.6x6.2bpp.lz"
VaporeonBackpic:     INCBIN "gfx/pics/134/back.6x6.2bpp.lz"
TentacoolBackpic:    INCBIN "gfx/pics/072/back.6x6.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/054.lz"
BulbasaurBackpic:    INCBIN "gfx/pics/001/back.6x6.2bpp.lz"
SmoochumBackpic:     INCBIN "gfx/pics/238/back.6x6.2bpp.lz"
PichuBackpic:        INCBIN "gfx/pics/172/back.6x6.2bpp.lz"
HoundoomBackpic:     INCBIN "gfx/pics/229/back.6x6.2bpp.lz"
BellsproutBackpic:   INCBIN "gfx/pics/069/back.6x6.2bpp.lz"
GrimerBackpic:       INCBIN "gfx/pics/088/back.6x6.2bpp.lz"
LanturnBackpic:      INCBIN "gfx/pics/171/back.6x6.2bpp.lz"
PidgeottoBackpic:    INCBIN "gfx/pics/017/back.6x6.2bpp.lz"
StaryuBackpic:       INCBIN "gfx/pics/120/back.6x6.2bpp.lz"
MrMimeBackpic:       INCBIN "gfx/pics/122/back.6x6.2bpp.lz"
CaterpieBackpic:     INCBIN "gfx/pics/010/back.6x6.2bpp.lz"
VoltorbFrontpic:     INCBIN "gfx/pics/100/front.5x5.2bpp.lz"
LugiaBackpic:        INCBIN "gfx/pics/249/back.6x6.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/004.lz"
BrockPic:            INCBIN "gfx/trainers/016.lz"
UnownGFrontpic:      INCBIN "gfx/pics/201g/front.5x5.2bpp.lz"
ArbokBackpic:        INCBIN "gfx/pics/024/back.6x6.2bpp.lz"
PolitoedBackpic:     INCBIN "gfx/pics/186/back.6x6.2bpp.lz"
DragoniteBackpic:    INCBIN "gfx/pics/149/back.6x6.2bpp.lz"
HitmonleeBackpic:    INCBIN "gfx/pics/106/back.6x6.2bpp.lz"
NatuFrontpic:        INCBIN "gfx/pics/177/front.5x5.2bpp.lz"
UrsaringBackpic:     INCBIN "gfx/pics/217/back.6x6.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/055.lz"
TeddiursaBackpic:    INCBIN "gfx/pics/216/back.6x6.2bpp.lz"
PhanpyBackpic:       INCBIN "gfx/pics/231/back.6x6.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pics/201v/front.5x5.2bpp.lz"
KakunaBackpic:       INCBIN "gfx/pics/014/back.6x6.2bpp.lz"
WobbuffetBackpic:    INCBIN "gfx/pics/202/back.6x6.2bpp.lz"
TogepiBackpic:       INCBIN "gfx/pics/175/back.6x6.2bpp.lz"
CrobatBackpic:       INCBIN "gfx/pics/169/back.6x6.2bpp.lz"
BlisseyBackpic:      INCBIN "gfx/pics/242/back.6x6.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pics/181/back.6x6.2bpp.lz"
IgglybuffBackpic:    INCBIN "gfx/pics/174/back.6x6.2bpp.lz"
AzumarillBackpic:    INCBIN "gfx/pics/184/back.6x6.2bpp.lz"
OctilleryBackpic:    INCBIN "gfx/pics/224/back.6x6.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pics/201s/front.5x5.2bpp.lz"
HorseaBackpic:       INCBIN "gfx/pics/116/back.6x6.2bpp.lz"
SentretBackpic:      INCBIN "gfx/pics/161/back.6x6.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pics/201o/front.5x5.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pics/201t/front.5x5.2bpp.lz"
WigglytuffBackpic:   INCBIN "gfx/pics/040/back.6x6.2bpp.lz"
ArticunoBackpic:     INCBIN "gfx/pics/144/back.6x6.2bpp.lz"
DittoBackpic:        INCBIN "gfx/pics/132/back.6x6.2bpp.lz"
WeedleBackpic:       INCBIN "gfx/pics/013/back.6x6.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pics/201h/front.5x5.2bpp.lz"
CleffaBackpic:       INCBIN "gfx/pics/173/back.6x6.2bpp.lz"
DrowzeeBackpic:      INCBIN "gfx/pics/096/back.6x6.2bpp.lz"
GastlyBackpic:       INCBIN "gfx/pics/092/back.6x6.2bpp.lz"
FearowBackpic:       INCBIN "gfx/pics/022/back.6x6.2bpp.lz"
MarillBackpic:       INCBIN "gfx/pics/183/back.6x6.2bpp.lz"
DratiniBackpic:      INCBIN "gfx/pics/147/back.6x6.2bpp.lz"
ElectrodeBackpic:    INCBIN "gfx/pics/101/back.6x6.2bpp.lz"
SkarmoryBackpic:     INCBIN "gfx/pics/227/back.6x6.2bpp.lz"
MetapodBackpic:      INCBIN "gfx/pics/011/back.6x6.2bpp.lz"
JigglypuffBackpic:   INCBIN "gfx/pics/039/back.6x6.2bpp.lz"
OddishBackpic:       INCBIN "gfx/pics/043/back.6x6.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pics/201d/back.6x6.2bpp.lz"
; 163ffc


SECTION "Pics 18", ROMX, BANK[PICS_18]

SpinarakBackpic:     INCBIN "gfx/pics/167/back.6x6.2bpp.lz"
RaikouBackpic:       INCBIN "gfx/pics/243/back.6x6.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pics/201k/front.5x5.2bpp.lz"
HoundourBackpic:     INCBIN "gfx/pics/228/back.6x6.2bpp.lz"
PoliwagBackpic:      INCBIN "gfx/pics/060/back.6x6.2bpp.lz"
SquirtleBackpic:     INCBIN "gfx/pics/007/back.6x6.2bpp.lz"
ShuckleBackpic:      INCBIN "gfx/pics/213/back.6x6.2bpp.lz"
DewgongBackpic:      INCBIN "gfx/pics/087/back.6x6.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pics/201b/front.5x5.2bpp.lz"
SlowpokeBackpic:     INCBIN "gfx/pics/079/back.6x6.2bpp.lz"
DunsparceBackpic:    INCBIN "gfx/pics/206/back.6x6.2bpp.lz"
DonphanBackpic:      INCBIN "gfx/pics/232/back.6x6.2bpp.lz"
WooperBackpic:       INCBIN "gfx/pics/194/back.6x6.2bpp.lz"
TaurosBackpic:       INCBIN "gfx/pics/128/back.6x6.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pics/201x/front.5x5.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pics/201n/front.5x5.2bpp.lz"
TangelaBackpic:      INCBIN "gfx/pics/114/back.6x6.2bpp.lz"
VoltorbBackpic:      INCBIN "gfx/pics/100/back.6x6.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pics/201j/front.5x5.2bpp.lz"
MantineBackpic:      INCBIN "gfx/pics/226/back.6x6.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pics/201l/front.5x5.2bpp.lz"
PiloswineBackpic:    INCBIN "gfx/pics/221/back.6x6.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pics/201m/front.5x5.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pics/201f/front.5x5.2bpp.lz"
NatuBackpic:         INCBIN "gfx/pics/177/back.6x6.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pics/201a/front.5x5.2bpp.lz"
GolemBackpic:        INCBIN "gfx/pics/076/back.6x6.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pics/201u/front.5x5.2bpp.lz"
DiglettBackpic:      INCBIN "gfx/pics/050/back.6x6.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pics/201q/front.5x5.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pics/201p/front.5x5.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pics/201c/back.6x6.2bpp.lz"
JynxBackpic:         INCBIN "gfx/pics/124/back.6x6.2bpp.lz"
GolbatBackpic:       INCBIN "gfx/pics/042/back.6x6.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pics/201y/front.5x5.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pics/201g/back.6x6.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pics/201i/front.5x5.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pics/201v/back.6x6.2bpp.lz"
ForretressBackpic:   INCBIN "gfx/pics/205/back.6x6.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pics/201s/back.6x6.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pics/201r/front.5x5.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pics/201e/back.6x6.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pics/201j/back.6x6.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pics/201b/back.6x6.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pics/201o/back.6x6.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pics/201z/back.6x6.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pics/201w/back.6x6.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pics/201n/back.6x6.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pics/201a/back.6x6.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pics/201m/back.6x6.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pics/201k/back.6x6.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pics/201t/back.6x6.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pics/201x/back.6x6.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pics/201l/back.6x6.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pics/201u/back.6x6.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pics/201q/back.6x6.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pics/201y/back.6x6.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pics/201p/back.6x6.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pics/201i/back.6x6.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pics/201r/back.6x6.2bpp.lz"
; 1669d3


SECTION "Pics 19", ROMX, BANK[PICS_19]

; Seems to be an accidental copy of the previous bank

INCBIN "gfx/pics/167/back.6x6.2bpp.lz"
INCBIN "gfx/pics/243/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201k/front.5x5.2bpp.lz"
INCBIN "gfx/pics/228/back.6x6.2bpp.lz"
INCBIN "gfx/pics/060/back.6x6.2bpp.lz"
INCBIN "gfx/pics/007/back.6x6.2bpp.lz"
INCBIN "gfx/pics/213/back.6x6.2bpp.lz"
INCBIN "gfx/pics/087/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201b/front.5x5.2bpp.lz"
INCBIN "gfx/pics/079/back.6x6.2bpp.lz"
INCBIN "gfx/pics/206/back.6x6.2bpp.lz"
INCBIN "gfx/pics/232/back.6x6.2bpp.lz"
INCBIN "gfx/pics/194/back.6x6.2bpp.lz"
INCBIN "gfx/pics/128/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201x/front.5x5.2bpp.lz"
INCBIN "gfx/pics/201n/front.5x5.2bpp.lz"
INCBIN "gfx/pics/114/back.6x6.2bpp.lz"
INCBIN "gfx/pics/100/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201j/front.5x5.2bpp.lz"
INCBIN "gfx/pics/226/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201l/front.5x5.2bpp.lz"
INCBIN "gfx/pics/221/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201m/front.5x5.2bpp.lz"
INCBIN "gfx/pics/201f/front.5x5.2bpp.lz"
INCBIN "gfx/pics/177/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201a/front.5x5.2bpp.lz"
INCBIN "gfx/pics/076/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201u/front.5x5.2bpp.lz"
INCBIN "gfx/pics/050/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201q/front.5x5.2bpp.lz"
INCBIN "gfx/pics/201p/front.5x5.2bpp.lz"
INCBIN "gfx/pics/201c/back.6x6.2bpp.lz"
INCBIN "gfx/pics/124/back.6x6.2bpp.lz"
INCBIN "gfx/pics/042/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201y/front.5x5.2bpp.lz"
INCBIN "gfx/pics/201g/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201i/front.5x5.2bpp.lz"
INCBIN "gfx/pics/201v/back.6x6.2bpp.lz"
INCBIN "gfx/pics/205/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201s/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201r/front.5x5.2bpp.lz"
INCBIN "gfx/pics/201e/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201j/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201b/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201o/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201z/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201w/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201n/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201a/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201m/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201k/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201t/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201x/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201l/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201u/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201q/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201y/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201p/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201i/back.6x6.2bpp.lz"
INCBIN "gfx/pics/201r/back.6x6.2bpp.lz"



