SECTION "Sprites 1", ROMX

ChrisSpriteGFX::               INCBIN "gfx/sprites/chris.2bpp" ; c0000
ChrisBikeSpriteGFX::           INCBIN "gfx/sprites/chris_bike.2bpp" ; c0180
GameboyKidSpriteGFX::          INCBIN "gfx/sprites/gameboy_kid.2bpp" ; c0300
SilverSpriteGFX::              INCBIN "gfx/sprites/silver.2bpp" ; c03c0
OakSpriteGFX::                 INCBIN "gfx/sprites/oak.2bpp" ; c0540
RedSpriteGFX::                 INCBIN "gfx/sprites/red.2bpp" ; c06c0
BlueSpriteGFX::                INCBIN "gfx/sprites/blue.2bpp" ; c0840
BillSpriteGFX::                INCBIN "gfx/sprites/bill.2bpp" ; c09c0
ElderSpriteGFX::               INCBIN "gfx/sprites/elder.2bpp" ; c0b40
JanineSpriteGFX::              INCBIN "gfx/sprites/janine.2bpp" ; c0cc0
KurtSpriteGFX::                INCBIN "gfx/sprites/kurt.2bpp" ; c0e40
MomSpriteGFX::                 INCBIN "gfx/sprites/mom.2bpp" ; c0fc0
BlaineSpriteGFX::              INCBIN "gfx/sprites/blaine.2bpp" ; c1140
RedsMomSpriteGFX::             INCBIN "gfx/sprites/reds_mom.2bpp" ; c12c0
DaisySpriteGFX::               INCBIN "gfx/sprites/daisy.2bpp" ; c1440
ElmSpriteGFX::                 INCBIN "gfx/sprites/elm.2bpp" ; c15c0
WillSpriteGFX::                INCBIN "gfx/sprites/will.2bpp" ; c1740
FalknerSpriteGFX::             INCBIN "gfx/sprites/falkner.2bpp" ; c1800
WhitneySpriteGFX::             INCBIN "gfx/sprites/whitney.2bpp" ; c1980
BugsySpriteGFX::               INCBIN "gfx/sprites/bugsy.2bpp" ; c1b00
MortySpriteGFX::               INCBIN "gfx/sprites/morty.2bpp" ; c1c80
ChuckSpriteGFX::               INCBIN "gfx/sprites/chuck.2bpp" ; c1e00
JasmineSpriteGFX::             INCBIN "gfx/sprites/jasmine.2bpp" ; c1f80
PryceSpriteGFX::               INCBIN "gfx/sprites/pryce.2bpp" ; c2100
ClairSpriteGFX::               INCBIN "gfx/sprites/clair.2bpp" ; c2280
BrockSpriteGFX::               INCBIN "gfx/sprites/brock.2bpp" ; c2400
KarenSpriteGFX::               INCBIN "gfx/sprites/karen.2bpp" ; c2580
BrunoSpriteGFX::               INCBIN "gfx/sprites/bruno.2bpp" ; c2640
MistySpriteGFX::               INCBIN "gfx/sprites/misty.2bpp" ; c27c0
LanceSpriteGFX::               INCBIN "gfx/sprites/lance.2bpp" ; c2940
SurgeSpriteGFX::               INCBIN "gfx/sprites/surge.2bpp" ; c2ac0
ErikaSpriteGFX::               INCBIN "gfx/sprites/erika.2bpp" ; c2c40
KogaSpriteGFX::                INCBIN "gfx/sprites/koga.2bpp" ; c2dc0
SabrinaSpriteGFX::             INCBIN "gfx/sprites/sabrina.2bpp" ; c2f40
CooltrainerMSpriteGFX::        INCBIN "gfx/sprites/cooltrainer_m.2bpp" ; c30c0
CooltrainerFSpriteGFX::        INCBIN "gfx/sprites/cooltrainer_f.2bpp" ; c3240
BugCatcherSpriteGFX::          INCBIN "gfx/sprites/bug_catcher.2bpp" ; c33c0
TwinSpriteGFX::                INCBIN "gfx/sprites/twin.2bpp" ; c3540
YoungsterSpriteGFX::           INCBIN "gfx/sprites/youngster.2bpp" ; c36c0
LassSpriteGFX::                INCBIN "gfx/sprites/lass.2bpp" ; c3840
TeacherSpriteGFX::             INCBIN "gfx/sprites/teacher.2bpp" ; c39c0
BuenaSpriteGFX::               INCBIN "gfx/sprites/buena.2bpp" ; c3b40
SuperNerdSpriteGFX::           INCBIN "gfx/sprites/super_nerd.2bpp" ; c3cc0
RockerSpriteGFX::              INCBIN "gfx/sprites/rocker.2bpp" ; c3e40


SECTION "Sprites 2", ROMX

PokefanMSpriteGFX::            INCBIN "gfx/sprites/pokefan_m.2bpp" ; c4000
PokefanFSpriteGFX::            INCBIN "gfx/sprites/pokefan_f.2bpp" ; c4180
GrampsSpriteGFX::              INCBIN "gfx/sprites/gramps.2bpp" ; c4300
GrannySpriteGFX::              INCBIN "gfx/sprites/granny.2bpp" ; c4480
SwimmerGuySpriteGFX::          INCBIN "gfx/sprites/swimmer_guy.2bpp" ; c4600
SwimmerGirlSpriteGFX::         INCBIN "gfx/sprites/swimmer_girl.2bpp" ; c4780
BigSnorlaxSpriteGFX::          INCBIN "gfx/sprites/big_snorlax.2bpp" ; c4900
SurfingPikachuSpriteGFX::      INCBIN "gfx/sprites/surfing_pikachu.2bpp" ; c4980
RocketSpriteGFX::              INCBIN "gfx/sprites/rocket.2bpp" ; c4b00
RocketGirlSpriteGFX::          INCBIN "gfx/sprites/rocket_girl.2bpp" ; c4c80
NurseSpriteGFX::               INCBIN "gfx/sprites/nurse.2bpp" ; c4e00
LinkReceptionistSpriteGFX::    INCBIN "gfx/sprites/link_receptionist.2bpp" ; c4ec0
ClerkSpriteGFX::               INCBIN "gfx/sprites/clerk.2bpp" ; c5040
FisherSpriteGFX::              INCBIN "gfx/sprites/fisher.2bpp" ; c51c0
FishingGuruSpriteGFX::         INCBIN "gfx/sprites/fishing_guru.2bpp" ; c5340
ScientistSpriteGFX::           INCBIN "gfx/sprites/scientist.2bpp" ; c54c0
KimonoGirlSpriteGFX::          INCBIN "gfx/sprites/kimono_girl.2bpp" ; c5640
SageSpriteGFX::                INCBIN "gfx/sprites/sage.2bpp" ; c57c0
UnusedGuySpriteGFX::           INCBIN "gfx/sprites/unused_guy.2bpp" ; c5940
GentlemanSpriteGFX::           INCBIN "gfx/sprites/gentleman.2bpp" ; c5ac0
BlackBeltSpriteGFX::           INCBIN "gfx/sprites/black_belt.2bpp" ; c5c40
ReceptionistSpriteGFX::        INCBIN "gfx/sprites/receptionist.2bpp" ; c5dc0
OfficerSpriteGFX::             INCBIN "gfx/sprites/officer.2bpp" ; c5f40
CalSpriteGFX::                 INCBIN "gfx/sprites/cal.2bpp" ; c60c0
SlowpokeSpriteGFX::            INCBIN "gfx/sprites/slowpoke.2bpp" ; c6240
CaptainSpriteGFX::             INCBIN "gfx/sprites/captain.2bpp" ; c6280
BigLaprasSpriteGFX::           INCBIN "gfx/sprites/big_lapras.2bpp" ; c6400
GymGuySpriteGFX::              INCBIN "gfx/sprites/gym_guy.2bpp" ; c6480
SailorSpriteGFX::              INCBIN "gfx/sprites/sailor.2bpp" ; c6600
BikerSpriteGFX::               INCBIN "gfx/sprites/biker.2bpp" ; c6780
PharmacistSpriteGFX::          INCBIN "gfx/sprites/pharmacist.2bpp" ; c6900
MonsterSpriteGFX::             INCBIN "gfx/sprites/monster.2bpp" ; c6a80
FairySpriteGFX::               INCBIN "gfx/sprites/fairy.2bpp" ; c6c00
BirdSpriteGFX::                INCBIN "gfx/sprites/bird.2bpp" ; c6d80
DragonSpriteGFX::              INCBIN "gfx/sprites/dragon.2bpp" ; c6f00
BigOnixSpriteGFX::             INCBIN "gfx/sprites/big_onix.2bpp" ; c7080
N64SpriteGFX::                 INCBIN "gfx/sprites/n64.2bpp" ; c7140
SudowoodoSpriteGFX::           INCBIN "gfx/sprites/sudowoodo.2bpp" ; c7180
SurfSpriteGFX::                INCBIN "gfx/sprites/surf.2bpp" ; c7200
PokeBallSpriteGFX::            INCBIN "gfx/sprites/poke_ball.2bpp" ; c7380
PokedexSpriteGFX::             INCBIN "gfx/sprites/pokedex.2bpp" ; c7500
PaperSpriteGFX::               INCBIN "gfx/sprites/paper.2bpp" ; c7680
VirtualBoySpriteGFX::          INCBIN "gfx/sprites/virtual_boy.2bpp" ; c7800
OldLinkReceptionistSpriteGFX:: INCBIN "gfx/sprites/old_link_receptionist.2bpp" ; c7840
RockSpriteGFX::                INCBIN "gfx/sprites/rock.2bpp" ; c7880
BoulderSpriteGFX::             INCBIN "gfx/sprites/boulder.2bpp" ; c78c0
SnesSpriteGFX::                INCBIN "gfx/sprites/snes.2bpp" ; c7900
FamicomSpriteGFX::             INCBIN "gfx/sprites/famicom.2bpp" ; c7940
FruitTreeSpriteGFX::           INCBIN "gfx/sprites/fruit_tree.2bpp" ; c7980
GoldTrophySpriteGFX::          INCBIN "gfx/sprites/gold_trophy.2bpp" ; c79c0
SilverTrophySpriteGFX::        INCBIN "gfx/sprites/silver_trophy.2bpp" ; c7a00
KrisSpriteGFX::                INCBIN "gfx/sprites/kris.2bpp" ; c7a40
KrisBikeSpriteGFX::            INCBIN "gfx/sprites/kris_bike.2bpp" ; c7bc0
KurtOutsideSpriteGFX::         INCBIN "gfx/sprites/kurt_outside.2bpp" ; c7d40
SuicuneSpriteGFX::             INCBIN "gfx/sprites/suicune.2bpp" ; c7e00
EnteiSpriteGFX::               INCBIN "gfx/sprites/entei.2bpp" ; c7e40
RaikouSpriteGFX::              INCBIN "gfx/sprites/raikou.2bpp" ; c7e80
StandingYoungsterSpriteGFX::   INCBIN "gfx/sprites/standing_youngster.2bpp" ; c7ec0
