
	add_pic FalknerPic
	add_pic WhitneyPic
	add_pic BugsyPic
	add_pic MortyPic
	add_pic PrycePic
	add_pic JasminePic
	add_pic ChuckPic
	add_pic ClairPic
	add_pic Rival1Pic
	add_pic PokemonProfPic
	add_pic WillPic
	add_pic CalPic
	add_pic BrunoPic
	add_pic KarenPic
	add_pic KogaPic
	add_pic ChampionPic
	add_pic BrockPic
	add_pic MistyPic
	add_pic LtSurgePic
	add_pic ScientistPic
	add_pic ErikaPic
	add_pic YoungsterPic
	add_pic SchoolboyPic
	add_pic BirdKeeperPic
	add_pic LassPic
	add_pic JaninePic
	add_pic CooltrainermPic
	add_pic CooltrainerfPic
	add_pic BeautyPic
	add_pic PokemaniacPic
	add_pic GruntmPic
	add_pic GentlemanPic
	add_pic SkierPic
	add_pic TeacherPic
	add_pic SabrinaPic
	add_pic BugCatcherPic
	add_pic FisherPic
	add_pic SwimmermPic
	add_pic SwimmerfPic
	add_pic SailorPic
	add_pic SuperNerdPic
	add_pic Rival2Pic
	add_pic GuitaristPic
	add_pic HikerPic
	add_pic BikerPic
	add_pic BlainePic
	add_pic BurglarPic
	add_pic FirebreatherPic
	add_pic JugglerPic
	add_pic BlackbeltTPic
	add_pic ExecutivemPic
	add_pic PsychicTPic
	add_pic PicnickerPic
	add_pic CamperPic
	add_pic ExecutivefPic
	add_pic SagePic
	add_pic MediumPic
	add_pic BoarderPic
	add_pic PokefanmPic
	add_pic KimonoGirlPic
	add_pic TwinsPic
	add_pic PokefanfPic
	add_pic RedPic
	add_pic BluePic
	add_pic OfficerPic
	add_pic GruntfPic
	add_pic MysticalmanPic
