EggMovePointers:: ; 0x23b11
	dw BulbasaurEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw CharmanderEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw SquirtleEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw PidgeyEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw RattataEggMoves
	dw NoEggMoves
	dw SpearowEggMoves
	dw NoEggMoves
	dw EkansEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw SandshrewEggMoves
	dw NoEggMoves
	dw NidoranFEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NidoranMEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw VulpixEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw ZubatEggMoves
	dw NoEggMoves
	dw OddishEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw ParasEggMoves
	dw NoEggMoves
	dw VenonatEggMoves
	dw NoEggMoves
	dw DiglettEggMoves
	dw NoEggMoves
	dw MeowthEggMoves
	dw NoEggMoves
	dw PsyduckEggMoves
	dw NoEggMoves
	dw MankeyEggMoves
	dw NoEggMoves
	dw GrowlitheEggMoves
	dw NoEggMoves
	dw PoliwagEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw AbraEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw MachopEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw BellsproutEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw TentacoolEggMoves
	dw NoEggMoves
	dw GeodudeEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw PonytaEggMoves
	dw NoEggMoves
	dw SlowpokeEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw FarfetchDEggMoves
	dw DoduoEggMoves
	dw NoEggMoves
	dw SeelEggMoves
	dw NoEggMoves
	dw GrimerEggMoves
	dw NoEggMoves
	dw ShellderEggMoves
	dw NoEggMoves
	dw GastlyEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw OnixEggMoves
	dw DrowzeeEggMoves
	dw NoEggMoves
	dw KrabbyEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw ExeggcuteEggMoves
	dw NoEggMoves
	dw CuboneEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw LickitungEggMoves
	dw KoffingEggMoves
	dw NoEggMoves
	dw RhyhornEggMoves
	dw NoEggMoves
	dw ChanseyEggMoves
	dw TangelaEggMoves
	dw KangaskhanEggMoves
	dw HorseaEggMoves
	dw NoEggMoves
	dw GoldeenEggMoves
	dw NoEggMoves
if _CRYSTAL
	dw NoEggMoves
else
	dw StaryuEggMoves
endc
	dw NoEggMoves
	dw MrMimeEggMoves
	dw ScytherEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw PinsirEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw LaprasEggMoves
	dw NoEggMoves
	dw EeveeEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw OmanyteEggMoves
	dw NoEggMoves
	dw KabutoEggMoves
	dw NoEggMoves
	dw AerodactylEggMoves
	dw SnorlaxEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw DratiniEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw ChikoritaEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw CyndaquilEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw TotodileEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw SentretEggMoves
	dw NoEggMoves
	dw HoothootEggMoves
	dw NoEggMoves
	dw LedybaEggMoves
	dw NoEggMoves
	dw SpinarakEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw ChinchouEggMoves
	dw NoEggMoves
	dw PichuEggMoves
	dw CleffaEggMoves
	dw IgglybuffEggMoves
	dw TogepiEggMoves
	dw NoEggMoves
	dw NatuEggMoves
	dw NoEggMoves
	dw MareepEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw MarillEggMoves
	dw NoEggMoves
	dw SudowoodoEggMoves
	dw NoEggMoves
	dw HoppipEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw AipomEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw YanmaEggMoves
	dw WooperEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw MurkrowEggMoves
	dw NoEggMoves
	dw MisdreavusEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw GirafarigEggMoves
	dw PinecoEggMoves
	dw NoEggMoves
	dw DunsparceEggMoves
	dw GligarEggMoves
	dw NoEggMoves
	dw SnubbullEggMoves
	dw NoEggMoves
	dw QwilfishEggMoves
	dw NoEggMoves
	dw ShuckleEggMoves
	dw HeracrossEggMoves
	dw SneaselEggMoves
	dw TeddiursaEggMoves
	dw NoEggMoves
	dw SlugmaEggMoves
	dw NoEggMoves
	dw SwinubEggMoves
	dw NoEggMoves
	dw CorsolaEggMoves
	dw RemoraidEggMoves
	dw NoEggMoves
	dw DelibirdEggMoves
	dw MantineEggMoves
	dw SkarmoryEggMoves
	dw HoundourEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw PhanpyEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw StantlerEggMoves
	dw NoEggMoves
	dw TyrogueEggMoves
	dw NoEggMoves
	dw SmoochumEggMoves
	dw ElekidEggMoves
	dw MagbyEggMoves
	dw MiltankEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw LarvitarEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
	dw NoEggMoves
